// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// PlayerState 玩家状态
type PlayerState int32

const (
	PlayerState_PS_NIL      PlayerState = 0
	PlayerState_PS_IDIE     PlayerState = 1
	PlayerState_PS_GAMEING  PlayerState = 2
	PlayerState_PS_MATCHING PlayerState = 3
)

var PlayerState_name = map[int32]string{
	0: "PS_NIL",
	1: "PS_IDIE",
	2: "PS_GAMEING",
	3: "PS_MATCHING",
}
var PlayerState_value = map[string]int32{
	"PS_NIL":      0,
	"PS_IDIE":     1,
	"PS_GAMEING":  2,
	"PS_MATCHING": 3,
}

func (x PlayerState) String() string {
	return proto.EnumName(PlayerState_name, int32(x))
}
func (PlayerState) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

// ServerType 服务类型
type ServerType int32

const (
	ServerType_ST_NIL   ServerType = 0
	ServerType_ST_GATE  ServerType = 1
	ServerType_ST_MATCH ServerType = 2
	ServerType_ST_ROOM  ServerType = 3
)

var ServerType_name = map[int32]string{
	0: "ST_NIL",
	1: "ST_GATE",
	2: "ST_MATCH",
	3: "ST_ROOM",
}
var ServerType_value = map[string]int32{
	"ST_NIL":   0,
	"ST_GATE":  1,
	"ST_MATCH": 2,
	"ST_ROOM":  3,
}

func (x ServerType) String() string {
	return proto.EnumName(ServerType_name, int32(x))
}
func (ServerType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

// GameConfig 游戏玩法信息
type GameConfig struct {
	GameId    uint32 `protobuf:"varint,1,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	GameName  string `protobuf:"bytes,2,opt,name=game_name,json=gameName" json:"game_name,omitempty"`
	GameType  uint32 `protobuf:"varint,3,opt,name=game_type,json=gameType" json:"game_type,omitempty"`
	MinPeople uint32 `protobuf:"varint,4,opt,name=min_people,json=minPeople" json:"min_people,omitempty"`
	MaxPeople uint32 `protobuf:"varint,5,opt,name=max_people,json=maxPeople" json:"max_people,omitempty"`
}

func (m *GameConfig) Reset()                    { *m = GameConfig{} }
func (m *GameConfig) String() string            { return proto.CompactTextString(m) }
func (*GameConfig) ProtoMessage()               {}
func (*GameConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *GameConfig) GetGameId() uint32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GameConfig) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *GameConfig) GetGameType() uint32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *GameConfig) GetMinPeople() uint32 {
	if m != nil {
		return m.MinPeople
	}
	return 0
}

func (m *GameConfig) GetMaxPeople() uint32 {
	if m != nil {
		return m.MaxPeople
	}
	return 0
}

// GameConfigLevel 游戏场次信息
type GameLevelConfig struct {
	GameId     uint32 `protobuf:"varint,1,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId    uint32 `protobuf:"varint,2,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	LevelName  string `protobuf:"bytes,3,opt,name=level_name,json=levelName" json:"level_name,omitempty"`
	BaseScores uint32 `protobuf:"varint,4,opt,name=base_scores,json=baseScores" json:"base_scores,omitempty"`
	LowScores  uint32 `protobuf:"varint,5,opt,name=low_scores,json=lowScores" json:"low_scores,omitempty"`
	HighScores uint32 `protobuf:"varint,6,opt,name=high_scores,json=highScores" json:"high_scores,omitempty"`
}

func (m *GameLevelConfig) Reset()                    { *m = GameLevelConfig{} }
func (m *GameLevelConfig) String() string            { return proto.CompactTextString(m) }
func (*GameLevelConfig) ProtoMessage()               {}
func (*GameLevelConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GameLevelConfig) GetGameId() uint32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GameLevelConfig) GetLevelId() uint32 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

func (m *GameLevelConfig) GetLevelName() string {
	if m != nil {
		return m.LevelName
	}
	return ""
}

func (m *GameLevelConfig) GetBaseScores() uint32 {
	if m != nil {
		return m.BaseScores
	}
	return 0
}

func (m *GameLevelConfig) GetLowScores() uint32 {
	if m != nil {
		return m.LowScores
	}
	return 0
}

func (m *GameLevelConfig) GetHighScores() uint32 {
	if m != nil {
		return m.HighScores
	}
	return 0
}

// GetPlayerByAccountReq 根据账号获取玩家请求
type GetPlayerByAccountReq struct {
	AccountId uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
}

func (m *GetPlayerByAccountReq) Reset()                    { *m = GetPlayerByAccountReq{} }
func (m *GetPlayerByAccountReq) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerByAccountReq) ProtoMessage()               {}
func (*GetPlayerByAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GetPlayerByAccountReq) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

// GetPlayerByAccountRsp 根据账号获取玩家应答
type GetPlayerByAccountRsp struct {
	ErrCode  int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	PlayerId uint64 `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *GetPlayerByAccountRsp) Reset()                    { *m = GetPlayerByAccountRsp{} }
func (m *GetPlayerByAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerByAccountRsp) ProtoMessage()               {}
func (*GetPlayerByAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GetPlayerByAccountRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GetPlayerByAccountRsp) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// GetPlayerInfoReq 获取玩家信息
type GetPlayerInfoReq struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *GetPlayerInfoReq) Reset()                    { *m = GetPlayerInfoReq{} }
func (m *GetPlayerInfoReq) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerInfoReq) ProtoMessage()               {}
func (*GetPlayerInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *GetPlayerInfoReq) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// GetPlayerInfoRsp 获取玩家信息应答
type GetPlayerInfoRsp struct {
	ErrCode    int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	PlayerId   uint64 `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	NickName   string `protobuf:"bytes,3,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	Avatar     string `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
	Gender     uint32 `protobuf:"varint,5,opt,name=gender" json:"gender,omitempty"`
	ChannelId  uint32 `protobuf:"varint,6,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	ProvinceId uint32 `protobuf:"varint,7,opt,name=province_id,json=provinceId" json:"province_id,omitempty"`
	CityId     uint32 `protobuf:"varint,8,opt,name=city_id,json=cityId" json:"city_id,omitempty"`
	ShowUid    uint64 `protobuf:"varint,9,opt,name=show_uid,json=showUid" json:"show_uid,omitempty"`
}

func (m *GetPlayerInfoRsp) Reset()                    { *m = GetPlayerInfoRsp{} }
func (m *GetPlayerInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerInfoRsp) ProtoMessage()               {}
func (*GetPlayerInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *GetPlayerInfoRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GetPlayerInfoRsp) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GetPlayerInfoRsp) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *GetPlayerInfoRsp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GetPlayerInfoRsp) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *GetPlayerInfoRsp) GetChannelId() uint32 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *GetPlayerInfoRsp) GetProvinceId() uint32 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *GetPlayerInfoRsp) GetCityId() uint32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *GetPlayerInfoRsp) GetShowUid() uint64 {
	if m != nil {
		return m.ShowUid
	}
	return 0
}

// UpdatePlayerInfoReq 修改玩家信息
type UpdatePlayerInfoReq struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Gender   uint32 `protobuf:"varint,4,opt,name=gender" json:"gender,omitempty"`
	Name     string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Phone    string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
}

func (m *UpdatePlayerInfoReq) Reset()                    { *m = UpdatePlayerInfoReq{} }
func (m *UpdatePlayerInfoReq) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlayerInfoReq) ProtoMessage()               {}
func (*UpdatePlayerInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *UpdatePlayerInfoReq) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *UpdatePlayerInfoReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UpdatePlayerInfoReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UpdatePlayerInfoReq) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UpdatePlayerInfoReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePlayerInfoReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// UpdatePlayerInfoRsp 修改玩家信息应答
type UpdatePlayerInfoRsp struct {
	ErrCode int32 `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	Result  bool  `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
}

func (m *UpdatePlayerInfoRsp) Reset()                    { *m = UpdatePlayerInfoRsp{} }
func (m *UpdatePlayerInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlayerInfoRsp) ProtoMessage()               {}
func (*UpdatePlayerInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *UpdatePlayerInfoRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *UpdatePlayerInfoRsp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// GetPlayerStateReq 获取玩家状态
type GetPlayerStateReq struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *GetPlayerStateReq) Reset()                    { *m = GetPlayerStateReq{} }
func (m *GetPlayerStateReq) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerStateReq) ProtoMessage()               {}
func (*GetPlayerStateReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *GetPlayerStateReq) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// GetPlayerStateRsp 获取玩家状态应答
type GetPlayerStateRsp struct {
	ErrCode   int32       `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	State     PlayerState `protobuf:"varint,2,opt,name=state,enum=user.PlayerState" json:"state,omitempty"`
	GameId    uint32      `protobuf:"varint,3,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId   uint32      `protobuf:"varint,4,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	IpAddr    string      `protobuf:"bytes,5,opt,name=ip_addr,json=ipAddr" json:"ip_addr,omitempty"`
	MatchAddr string      `protobuf:"bytes,6,opt,name=match_addr,json=matchAddr" json:"match_addr,omitempty"`
	GateAddr  string      `protobuf:"bytes,7,opt,name=gate_addr,json=gateAddr" json:"gate_addr,omitempty"`
	RoomAddr  string      `protobuf:"bytes,8,opt,name=room_addr,json=roomAddr" json:"room_addr,omitempty"`
}

func (m *GetPlayerStateRsp) Reset()                    { *m = GetPlayerStateRsp{} }
func (m *GetPlayerStateRsp) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerStateRsp) ProtoMessage()               {}
func (*GetPlayerStateRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *GetPlayerStateRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GetPlayerStateRsp) GetState() PlayerState {
	if m != nil {
		return m.State
	}
	return PlayerState_PS_NIL
}

func (m *GetPlayerStateRsp) GetGameId() uint32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GetPlayerStateRsp) GetLevelId() uint32 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

func (m *GetPlayerStateRsp) GetIpAddr() string {
	if m != nil {
		return m.IpAddr
	}
	return ""
}

func (m *GetPlayerStateRsp) GetMatchAddr() string {
	if m != nil {
		return m.MatchAddr
	}
	return ""
}

func (m *GetPlayerStateRsp) GetGateAddr() string {
	if m != nil {
		return m.GateAddr
	}
	return ""
}

func (m *GetPlayerStateRsp) GetRoomAddr() string {
	if m != nil {
		return m.RoomAddr
	}
	return ""
}

// GetPlayerGameInfoReq 获取玩家游戏信息
type GetPlayerGameInfoReq struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	GameId   uint32 `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
}

func (m *GetPlayerGameInfoReq) Reset()                    { *m = GetPlayerGameInfoReq{} }
func (m *GetPlayerGameInfoReq) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerGameInfoReq) ProtoMessage()               {}
func (*GetPlayerGameInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *GetPlayerGameInfoReq) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GetPlayerGameInfoReq) GetGameId() uint32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

// GetPlayerGameInfoRsp 获取玩家游戏信息应答
type GetPlayerGameInfoRsp struct {
	ErrCode          int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	GameId           uint32 `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	WinningRate      uint32 `protobuf:"varint,3,opt,name=winning_rate,json=winningRate" json:"winning_rate,omitempty"`
	WinningBurea     uint32 `protobuf:"varint,4,opt,name=Winning_burea,json=WinningBurea" json:"Winning_burea,omitempty"`
	TotalBurea       uint32 `protobuf:"varint,5,opt,name=total_burea,json=totalBurea" json:"total_burea,omitempty"`
	MaxWinningStream uint32 `protobuf:"varint,6,opt,name=max_winning_stream,json=maxWinningStream" json:"max_winning_stream,omitempty"`
	MaxMultiple      uint32 `protobuf:"varint,7,opt,name=max_multiple,json=maxMultiple" json:"max_multiple,omitempty"`
}

func (m *GetPlayerGameInfoRsp) Reset()                    { *m = GetPlayerGameInfoRsp{} }
func (m *GetPlayerGameInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerGameInfoRsp) ProtoMessage()               {}
func (*GetPlayerGameInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *GetPlayerGameInfoRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GetPlayerGameInfoRsp) GetGameId() uint32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GetPlayerGameInfoRsp) GetWinningRate() uint32 {
	if m != nil {
		return m.WinningRate
	}
	return 0
}

func (m *GetPlayerGameInfoRsp) GetWinningBurea() uint32 {
	if m != nil {
		return m.WinningBurea
	}
	return 0
}

func (m *GetPlayerGameInfoRsp) GetTotalBurea() uint32 {
	if m != nil {
		return m.TotalBurea
	}
	return 0
}

func (m *GetPlayerGameInfoRsp) GetMaxWinningStream() uint32 {
	if m != nil {
		return m.MaxWinningStream
	}
	return 0
}

func (m *GetPlayerGameInfoRsp) GetMaxMultiple() uint32 {
	if m != nil {
		return m.MaxMultiple
	}
	return 0
}

// UpdatePlayerGateInfoReq 更新玩家网关信息
type UpdatePlayerGateInfoReq struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	IpAddr   string `protobuf:"bytes,2,opt,name=ip_addr,json=ipAddr" json:"ip_addr,omitempty"`
	GateAddr string `protobuf:"bytes,3,opt,name=gate_addr,json=gateAddr" json:"gate_addr,omitempty"`
}

func (m *UpdatePlayerGateInfoReq) Reset()                    { *m = UpdatePlayerGateInfoReq{} }
func (m *UpdatePlayerGateInfoReq) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlayerGateInfoReq) ProtoMessage()               {}
func (*UpdatePlayerGateInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *UpdatePlayerGateInfoReq) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *UpdatePlayerGateInfoReq) GetIpAddr() string {
	if m != nil {
		return m.IpAddr
	}
	return ""
}

func (m *UpdatePlayerGateInfoReq) GetGateAddr() string {
	if m != nil {
		return m.GateAddr
	}
	return ""
}

// UpdatePlayerStateReq 更新玩家游戏状态
type UpdatePlayerStateReq struct {
	PlayerId   uint64      `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	OldState   PlayerState `protobuf:"varint,2,opt,name=old_state,json=oldState,enum=user.PlayerState" json:"old_state,omitempty"`
	NewState   PlayerState `protobuf:"varint,3,opt,name=new_state,json=newState,enum=user.PlayerState" json:"new_state,omitempty"`
	GameId     uint32      `protobuf:"varint,4,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId    uint32      `protobuf:"varint,5,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	ServerType ServerType  `protobuf:"varint,6,opt,name=server_type,json=serverType,enum=user.ServerType" json:"server_type,omitempty"`
	ServerAddr string      `protobuf:"bytes,7,opt,name=server_addr,json=serverAddr" json:"server_addr,omitempty"`
}

func (m *UpdatePlayerStateReq) Reset()                    { *m = UpdatePlayerStateReq{} }
func (m *UpdatePlayerStateReq) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlayerStateReq) ProtoMessage()               {}
func (*UpdatePlayerStateReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *UpdatePlayerStateReq) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *UpdatePlayerStateReq) GetOldState() PlayerState {
	if m != nil {
		return m.OldState
	}
	return PlayerState_PS_NIL
}

func (m *UpdatePlayerStateReq) GetNewState() PlayerState {
	if m != nil {
		return m.NewState
	}
	return PlayerState_PS_NIL
}

func (m *UpdatePlayerStateReq) GetGameId() uint32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *UpdatePlayerStateReq) GetLevelId() uint32 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

func (m *UpdatePlayerStateReq) GetServerType() ServerType {
	if m != nil {
		return m.ServerType
	}
	return ServerType_ST_NIL
}

func (m *UpdatePlayerStateReq) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

// UpdatePlayerServerAddrReq 更新玩家服务端地址
type UpdatePlayerServerAddrReq struct {
	PlayerId   uint64     `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	ServerType ServerType `protobuf:"varint,5,opt,name=server_type,json=serverType,enum=user.ServerType" json:"server_type,omitempty"`
	ServerAddr string     `protobuf:"bytes,6,opt,name=server_addr,json=serverAddr" json:"server_addr,omitempty"`
}

func (m *UpdatePlayerServerAddrReq) Reset()                    { *m = UpdatePlayerServerAddrReq{} }
func (m *UpdatePlayerServerAddrReq) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlayerServerAddrReq) ProtoMessage()               {}
func (*UpdatePlayerServerAddrReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *UpdatePlayerServerAddrReq) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *UpdatePlayerServerAddrReq) GetServerType() ServerType {
	if m != nil {
		return m.ServerType
	}
	return ServerType_ST_NIL
}

func (m *UpdatePlayerServerAddrReq) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

// UpdatePlayerRsp  更新玩家应答
type UpdatePlayerRsp struct {
	ErrCode int32 `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	Result  bool  `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
}

func (m *UpdatePlayerRsp) Reset()                    { *m = UpdatePlayerRsp{} }
func (m *UpdatePlayerRsp) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlayerRsp) ProtoMessage()               {}
func (*UpdatePlayerRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *UpdatePlayerRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *UpdatePlayerRsp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// InitRobotPlayerState 初始化机器人玩家状态请求
type InitRobotPlayerStateReq struct {
	RobotIds []uint64 `protobuf:"varint,1,rep,packed,name=robot_ids,json=robotIds" json:"robot_ids,omitempty"`
}

func (m *InitRobotPlayerStateReq) Reset()                    { *m = InitRobotPlayerStateReq{} }
func (m *InitRobotPlayerStateReq) String() string            { return proto.CompactTextString(m) }
func (*InitRobotPlayerStateReq) ProtoMessage()               {}
func (*InitRobotPlayerStateReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *InitRobotPlayerStateReq) GetRobotIds() []uint64 {
	if m != nil {
		return m.RobotIds
	}
	return nil
}

// InitRobotPlayerStateRsp 初始化机器人玩家状态返回
type InitRobotPlayerStateRsp struct {
	ErrCode    int32         `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	RobotState []*RobotState `protobuf:"bytes,2,rep,name=robot_state,json=robotState" json:"robot_state,omitempty"`
}

func (m *InitRobotPlayerStateRsp) Reset()                    { *m = InitRobotPlayerStateRsp{} }
func (m *InitRobotPlayerStateRsp) String() string            { return proto.CompactTextString(m) }
func (*InitRobotPlayerStateRsp) ProtoMessage()               {}
func (*InitRobotPlayerStateRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *InitRobotPlayerStateRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *InitRobotPlayerStateRsp) GetRobotState() []*RobotState {
	if m != nil {
		return m.RobotState
	}
	return nil
}

type RobotState struct {
	RobotId    uint64      `protobuf:"varint,1,opt,name=robot_id,json=robotId" json:"robot_id,omitempty"`
	RobotState PlayerState `protobuf:"varint,2,opt,name=robot_state,json=robotState,enum=user.PlayerState" json:"robot_state,omitempty"`
}

func (m *RobotState) Reset()                    { *m = RobotState{} }
func (m *RobotState) String() string            { return proto.CompactTextString(m) }
func (*RobotState) ProtoMessage()               {}
func (*RobotState) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

func (m *RobotState) GetRobotId() uint64 {
	if m != nil {
		return m.RobotId
	}
	return 0
}

func (m *RobotState) GetRobotState() PlayerState {
	if m != nil {
		return m.RobotState
	}
	return PlayerState_PS_NIL
}

func init() {
	proto.RegisterType((*GameConfig)(nil), "user.GameConfig")
	proto.RegisterType((*GameLevelConfig)(nil), "user.GameLevelConfig")
	proto.RegisterType((*GetPlayerByAccountReq)(nil), "user.GetPlayerByAccountReq")
	proto.RegisterType((*GetPlayerByAccountRsp)(nil), "user.GetPlayerByAccountRsp")
	proto.RegisterType((*GetPlayerInfoReq)(nil), "user.GetPlayerInfoReq")
	proto.RegisterType((*GetPlayerInfoRsp)(nil), "user.GetPlayerInfoRsp")
	proto.RegisterType((*UpdatePlayerInfoReq)(nil), "user.UpdatePlayerInfoReq")
	proto.RegisterType((*UpdatePlayerInfoRsp)(nil), "user.UpdatePlayerInfoRsp")
	proto.RegisterType((*GetPlayerStateReq)(nil), "user.GetPlayerStateReq")
	proto.RegisterType((*GetPlayerStateRsp)(nil), "user.GetPlayerStateRsp")
	proto.RegisterType((*GetPlayerGameInfoReq)(nil), "user.GetPlayerGameInfoReq")
	proto.RegisterType((*GetPlayerGameInfoRsp)(nil), "user.GetPlayerGameInfoRsp")
	proto.RegisterType((*UpdatePlayerGateInfoReq)(nil), "user.UpdatePlayerGateInfoReq")
	proto.RegisterType((*UpdatePlayerStateReq)(nil), "user.UpdatePlayerStateReq")
	proto.RegisterType((*UpdatePlayerServerAddrReq)(nil), "user.UpdatePlayerServerAddrReq")
	proto.RegisterType((*UpdatePlayerRsp)(nil), "user.UpdatePlayerRsp")
	proto.RegisterType((*InitRobotPlayerStateReq)(nil), "user.InitRobotPlayerStateReq")
	proto.RegisterType((*InitRobotPlayerStateRsp)(nil), "user.InitRobotPlayerStateRsp")
	proto.RegisterType((*RobotState)(nil), "user.RobotState")
	proto.RegisterEnum("user.PlayerState", PlayerState_name, PlayerState_value)
	proto.RegisterEnum("user.ServerType", ServerType_name, ServerType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PlayerData service

type PlayerDataClient interface {
	// GetPlayerByAccount 根据账号获取玩家
	GetPlayerByAccount(ctx context.Context, in *GetPlayerByAccountReq, opts ...grpc.CallOption) (*GetPlayerByAccountRsp, error)
	// GetPlayerInfo 获取玩家信息
	GetPlayerInfo(ctx context.Context, in *GetPlayerInfoReq, opts ...grpc.CallOption) (*GetPlayerInfoRsp, error)
	// UpdatePlayerInfo 更新玩家信息
	UpdatePlayerInfo(ctx context.Context, in *UpdatePlayerInfoReq, opts ...grpc.CallOption) (*UpdatePlayerInfoRsp, error)
	// GetPlayerState 获取玩家状态
	GetPlayerState(ctx context.Context, in *GetPlayerStateReq, opts ...grpc.CallOption) (*GetPlayerStateRsp, error)
	//  GetPlayerGameInfo 获取玩家游戏信息
	GetPlayerGameInfo(ctx context.Context, in *GetPlayerGameInfoReq, opts ...grpc.CallOption) (*GetPlayerGameInfoRsp, error)
	// UpdatePlayerState 更新玩家状态
	UpdatePlayerState(ctx context.Context, in *UpdatePlayerStateReq, opts ...grpc.CallOption) (*UpdatePlayerRsp, error)
	// UpdatePlayerGateInfo 更新玩家网关信息
	UpdatePlayerGateInfo(ctx context.Context, in *UpdatePlayerGateInfoReq, opts ...grpc.CallOption) (*UpdatePlayerRsp, error)
	// UpdatePlayerServerAddr 更新玩家服务端信息
	UpdatePlayerServerAddr(ctx context.Context, in *UpdatePlayerServerAddrReq, opts ...grpc.CallOption) (*UpdatePlayerRsp, error)
	// InitRobotPlayerState 初始化机器人状态
	InitRobotPlayerState(ctx context.Context, in *InitRobotPlayerStateReq, opts ...grpc.CallOption) (*InitRobotPlayerStateRsp, error)
}

type playerDataClient struct {
	cc *grpc.ClientConn
}

func NewPlayerDataClient(cc *grpc.ClientConn) PlayerDataClient {
	return &playerDataClient{cc}
}

func (c *playerDataClient) GetPlayerByAccount(ctx context.Context, in *GetPlayerByAccountReq, opts ...grpc.CallOption) (*GetPlayerByAccountRsp, error) {
	out := new(GetPlayerByAccountRsp)
	err := grpc.Invoke(ctx, "/user.PlayerData/GetPlayerByAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerDataClient) GetPlayerInfo(ctx context.Context, in *GetPlayerInfoReq, opts ...grpc.CallOption) (*GetPlayerInfoRsp, error) {
	out := new(GetPlayerInfoRsp)
	err := grpc.Invoke(ctx, "/user.PlayerData/GetPlayerInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerDataClient) UpdatePlayerInfo(ctx context.Context, in *UpdatePlayerInfoReq, opts ...grpc.CallOption) (*UpdatePlayerInfoRsp, error) {
	out := new(UpdatePlayerInfoRsp)
	err := grpc.Invoke(ctx, "/user.PlayerData/UpdatePlayerInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerDataClient) GetPlayerState(ctx context.Context, in *GetPlayerStateReq, opts ...grpc.CallOption) (*GetPlayerStateRsp, error) {
	out := new(GetPlayerStateRsp)
	err := grpc.Invoke(ctx, "/user.PlayerData/GetPlayerState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerDataClient) GetPlayerGameInfo(ctx context.Context, in *GetPlayerGameInfoReq, opts ...grpc.CallOption) (*GetPlayerGameInfoRsp, error) {
	out := new(GetPlayerGameInfoRsp)
	err := grpc.Invoke(ctx, "/user.PlayerData/GetPlayerGameInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerDataClient) UpdatePlayerState(ctx context.Context, in *UpdatePlayerStateReq, opts ...grpc.CallOption) (*UpdatePlayerRsp, error) {
	out := new(UpdatePlayerRsp)
	err := grpc.Invoke(ctx, "/user.PlayerData/UpdatePlayerState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerDataClient) UpdatePlayerGateInfo(ctx context.Context, in *UpdatePlayerGateInfoReq, opts ...grpc.CallOption) (*UpdatePlayerRsp, error) {
	out := new(UpdatePlayerRsp)
	err := grpc.Invoke(ctx, "/user.PlayerData/UpdatePlayerGateInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerDataClient) UpdatePlayerServerAddr(ctx context.Context, in *UpdatePlayerServerAddrReq, opts ...grpc.CallOption) (*UpdatePlayerRsp, error) {
	out := new(UpdatePlayerRsp)
	err := grpc.Invoke(ctx, "/user.PlayerData/UpdatePlayerServerAddr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerDataClient) InitRobotPlayerState(ctx context.Context, in *InitRobotPlayerStateReq, opts ...grpc.CallOption) (*InitRobotPlayerStateRsp, error) {
	out := new(InitRobotPlayerStateRsp)
	err := grpc.Invoke(ctx, "/user.PlayerData/InitRobotPlayerState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PlayerData service

type PlayerDataServer interface {
	// GetPlayerByAccount 根据账号获取玩家
	GetPlayerByAccount(context.Context, *GetPlayerByAccountReq) (*GetPlayerByAccountRsp, error)
	// GetPlayerInfo 获取玩家信息
	GetPlayerInfo(context.Context, *GetPlayerInfoReq) (*GetPlayerInfoRsp, error)
	// UpdatePlayerInfo 更新玩家信息
	UpdatePlayerInfo(context.Context, *UpdatePlayerInfoReq) (*UpdatePlayerInfoRsp, error)
	// GetPlayerState 获取玩家状态
	GetPlayerState(context.Context, *GetPlayerStateReq) (*GetPlayerStateRsp, error)
	//  GetPlayerGameInfo 获取玩家游戏信息
	GetPlayerGameInfo(context.Context, *GetPlayerGameInfoReq) (*GetPlayerGameInfoRsp, error)
	// UpdatePlayerState 更新玩家状态
	UpdatePlayerState(context.Context, *UpdatePlayerStateReq) (*UpdatePlayerRsp, error)
	// UpdatePlayerGateInfo 更新玩家网关信息
	UpdatePlayerGateInfo(context.Context, *UpdatePlayerGateInfoReq) (*UpdatePlayerRsp, error)
	// UpdatePlayerServerAddr 更新玩家服务端信息
	UpdatePlayerServerAddr(context.Context, *UpdatePlayerServerAddrReq) (*UpdatePlayerRsp, error)
	// InitRobotPlayerState 初始化机器人状态
	InitRobotPlayerState(context.Context, *InitRobotPlayerStateReq) (*InitRobotPlayerStateRsp, error)
}

func RegisterPlayerDataServer(s *grpc.Server, srv PlayerDataServer) {
	s.RegisterService(&_PlayerData_serviceDesc, srv)
}

func _PlayerData_GetPlayerByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerByAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerDataServer).GetPlayerByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PlayerData/GetPlayerByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerDataServer).GetPlayerByAccount(ctx, req.(*GetPlayerByAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerData_GetPlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerDataServer).GetPlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PlayerData/GetPlayerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerDataServer).GetPlayerInfo(ctx, req.(*GetPlayerInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerData_UpdatePlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerDataServer).UpdatePlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PlayerData/UpdatePlayerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerDataServer).UpdatePlayerInfo(ctx, req.(*UpdatePlayerInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerData_GetPlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerDataServer).GetPlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PlayerData/GetPlayerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerDataServer).GetPlayerState(ctx, req.(*GetPlayerStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerData_GetPlayerGameInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerGameInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerDataServer).GetPlayerGameInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PlayerData/GetPlayerGameInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerDataServer).GetPlayerGameInfo(ctx, req.(*GetPlayerGameInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerData_UpdatePlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerDataServer).UpdatePlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PlayerData/UpdatePlayerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerDataServer).UpdatePlayerState(ctx, req.(*UpdatePlayerStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerData_UpdatePlayerGateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerGateInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerDataServer).UpdatePlayerGateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PlayerData/UpdatePlayerGateInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerDataServer).UpdatePlayerGateInfo(ctx, req.(*UpdatePlayerGateInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerData_UpdatePlayerServerAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerServerAddrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerDataServer).UpdatePlayerServerAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PlayerData/UpdatePlayerServerAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerDataServer).UpdatePlayerServerAddr(ctx, req.(*UpdatePlayerServerAddrReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerData_InitRobotPlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRobotPlayerStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerDataServer).InitRobotPlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.PlayerData/InitRobotPlayerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerDataServer).InitRobotPlayerState(ctx, req.(*InitRobotPlayerStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayerData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.PlayerData",
	HandlerType: (*PlayerDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerByAccount",
			Handler:    _PlayerData_GetPlayerByAccount_Handler,
		},
		{
			MethodName: "GetPlayerInfo",
			Handler:    _PlayerData_GetPlayerInfo_Handler,
		},
		{
			MethodName: "UpdatePlayerInfo",
			Handler:    _PlayerData_UpdatePlayerInfo_Handler,
		},
		{
			MethodName: "GetPlayerState",
			Handler:    _PlayerData_GetPlayerState_Handler,
		},
		{
			MethodName: "GetPlayerGameInfo",
			Handler:    _PlayerData_GetPlayerGameInfo_Handler,
		},
		{
			MethodName: "UpdatePlayerState",
			Handler:    _PlayerData_UpdatePlayerState_Handler,
		},
		{
			MethodName: "UpdatePlayerGateInfo",
			Handler:    _PlayerData_UpdatePlayerGateInfo_Handler,
		},
		{
			MethodName: "UpdatePlayerServerAddr",
			Handler:    _PlayerData_UpdatePlayerServerAddr_Handler,
		},
		{
			MethodName: "InitRobotPlayerState",
			Handler:    _PlayerData_InitRobotPlayerState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 1155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x26, 0xff, 0xf1, 0xc9, 0x76, 0x9b, 0x0e, 0xdd, 0x36, 0xcd, 0x6a, 0xd5, 0x62, 0x2e, 0xa8,
	0x56, 0xa8, 0xb0, 0x45, 0xda, 0x5b, 0xe8, 0xcf, 0x92, 0x5a, 0xf4, 0x27, 0xb2, 0xb3, 0xe2, 0x82,
	0x0b, 0x6b, 0x1a, 0xcf, 0x26, 0x16, 0xfe, 0x63, 0xec, 0x34, 0xed, 0x3d, 0x77, 0xf0, 0x06, 0x88,
	0x07, 0xe0, 0x05, 0x78, 0x03, 0x1e, 0x0b, 0x09, 0x9d, 0x99, 0x71, 0x6a, 0x27, 0x76, 0x5b, 0xf6,
	0x2e, 0xf3, 0x7d, 0xe7, 0x9c, 0x39, 0x7f, 0x73, 0x8e, 0x03, 0x6b, 0x31, 0xe3, 0x37, 0xee, 0x98,
	0x1d, 0x44, 0x3c, 0x4c, 0x42, 0x52, 0x9f, 0xc5, 0x8c, 0xeb, 0x7f, 0x56, 0x00, 0x06, 0xd4, 0x67,
	0x27, 0x61, 0xf0, 0xc1, 0x9d, 0x90, 0x6d, 0x68, 0x4d, 0xa8, 0xcf, 0x6c, 0xd7, 0xe9, 0x55, 0xf6,
	0x2a, 0xfb, 0x6b, 0x66, 0x13, 0x8f, 0x86, 0x43, 0x5e, 0x82, 0x26, 0x88, 0x80, 0xfa, 0xac, 0x57,
	0xdd, 0xab, 0xec, 0x6b, 0x66, 0x1b, 0x81, 0x4b, 0xea, 0xb3, 0x05, 0x99, 0xdc, 0x45, 0xac, 0x57,
	0x13, 0x7a, 0x82, 0x1c, 0xdd, 0x45, 0x8c, 0xbc, 0x02, 0xf0, 0xdd, 0xc0, 0x8e, 0x58, 0x18, 0x79,
	0xac, 0x57, 0x17, 0xac, 0xe6, 0xbb, 0xc1, 0x50, 0x00, 0x82, 0xa6, 0xb7, 0x29, 0xdd, 0x50, 0x34,
	0xbd, 0x95, 0xb4, 0xfe, 0x4f, 0x05, 0xd6, 0xd1, 0xbf, 0x73, 0x76, 0xc3, 0xbc, 0xc7, 0x9c, 0xdc,
	0x81, 0xb6, 0x87, 0x72, 0xc8, 0x54, 0x05, 0xd3, 0x12, 0x67, 0xc3, 0xc1, 0x6b, 0x24, 0x25, 0x02,
	0xa8, 0x89, 0x00, 0x34, 0x81, 0x88, 0x08, 0x76, 0xa1, 0x73, 0x4d, 0x63, 0x66, 0xc7, 0xe3, 0x90,
	0xb3, 0x58, 0x79, 0x09, 0x08, 0x59, 0x02, 0x11, 0xfa, 0xe1, 0x3c, 0xe5, 0x95, 0x9b, 0x5e, 0x38,
	0x57, 0xf4, 0x2e, 0x74, 0xa6, 0xee, 0x64, 0x9a, 0xf2, 0x4d, 0xa9, 0x8f, 0x90, 0x14, 0xd0, 0xdf,
	0xc2, 0x8b, 0x01, 0x4b, 0x86, 0x1e, 0xbd, 0x63, 0xfc, 0xf8, 0xee, 0x68, 0x3c, 0x0e, 0x67, 0x41,
	0x62, 0xb2, 0x5f, 0xd0, 0x30, 0x95, 0xa7, 0x34, 0x9e, 0xba, 0xa9, 0x29, 0xc4, 0x70, 0xf4, 0xab,
	0x42, 0xbd, 0x38, 0xc2, 0x58, 0x19, 0xe7, 0xf6, 0x38, 0x74, 0x98, 0xd0, 0x6a, 0x98, 0x2d, 0xc6,
	0xf9, 0x49, 0xe8, 0x88, 0x72, 0x44, 0x42, 0x21, 0xcd, 0x43, 0xdd, 0x6c, 0x4b, 0xc0, 0x70, 0xf4,
	0xaf, 0xa0, 0xbb, 0x30, 0x68, 0x04, 0x1f, 0x42, 0xf4, 0x21, 0xa7, 0x50, 0x59, 0x52, 0xf8, 0xad,
	0xba, 0xac, 0xf1, 0xf1, 0xb7, 0x23, 0x19, 0xb8, 0xe3, 0x9f, 0xb3, 0x55, 0x68, 0x23, 0x20, 0x8a,
	0xb0, 0x05, 0x4d, 0x7a, 0x43, 0x13, 0xca, 0x45, 0xfe, 0x35, 0x53, 0x9d, 0x10, 0x9f, 0xb0, 0xc0,
	0x61, 0x5c, 0xe5, 0x5d, 0x9d, 0x30, 0x75, 0xe3, 0x29, 0x0d, 0x02, 0x59, 0x70, 0x99, 0x73, 0x4d,
	0x21, 0x86, 0x83, 0x35, 0x89, 0x78, 0x78, 0xe3, 0x06, 0x63, 0xd1, 0x2a, 0x2d, 0x59, 0x93, 0x14,
	0x32, 0x1c, 0xec, 0xa3, 0xb1, 0x9b, 0xdc, 0x21, 0xd9, 0x96, 0x86, 0xf1, 0x28, 0xfb, 0x28, 0x9e,
	0x86, 0x73, 0x7b, 0xe6, 0x3a, 0x3d, 0x4d, 0x44, 0xd0, 0xc2, 0xf3, 0x7b, 0xd7, 0xd1, 0xff, 0xaa,
	0xc0, 0xa7, 0xef, 0x23, 0x87, 0x26, 0xec, 0xe9, 0x29, 0xcc, 0x47, 0x5d, 0x2d, 0x8d, 0xba, 0x56,
	0x12, 0x75, 0x3d, 0x17, 0x35, 0x81, 0xba, 0xb0, 0xd3, 0x10, 0xd2, 0xe2, 0x37, 0xd9, 0x84, 0x46,
	0x34, 0x0d, 0x03, 0x26, 0x92, 0xa0, 0x99, 0xf2, 0xa0, 0x9f, 0x15, 0xb8, 0xfa, 0x70, 0xed, 0xb6,
	0xa0, 0xc9, 0x59, 0x3c, 0xf3, 0x12, 0xe1, 0x65, 0xdb, 0x54, 0x27, 0xfd, 0x6b, 0xd8, 0x58, 0xb4,
	0x80, 0x95, 0xd0, 0x84, 0x3d, 0xda, 0x35, 0xff, 0x56, 0x56, 0x54, 0x1e, 0xbe, 0xfa, 0x0b, 0x68,
	0xc4, 0x28, 0x26, 0x6e, 0x7e, 0x7e, 0xb8, 0x71, 0x80, 0xe3, 0xe9, 0x20, 0xab, 0x2f, 0xf9, 0xec,
	0xeb, 0xaf, 0x95, 0xbe, 0xfe, 0x7a, 0xfe, 0xf5, 0x6f, 0x43, 0xcb, 0x8d, 0x6c, 0xea, 0x38, 0x5c,
	0xa5, 0xad, 0xe9, 0x46, 0x47, 0x8e, 0xc3, 0xe5, 0xf4, 0x49, 0xc6, 0x53, 0xc9, 0xc9, 0xec, 0x69,
	0x02, 0x11, 0xb4, 0x18, 0x6c, 0x09, 0x93, 0x6c, 0x2b, 0x9d, 0x7a, 0x09, 0x4b, 0x49, 0x1e, 0x86,
	0xbe, 0x24, 0xdb, 0x92, 0x44, 0x00, 0x49, 0xfd, 0x1c, 0x36, 0x17, 0xe1, 0xe3, 0xfc, 0x7a, 0x52,
	0x9f, 0x64, 0x42, 0xab, 0x66, 0x43, 0xd3, 0x7f, 0xad, 0x16, 0x99, 0x7b, 0x38, 0xa1, 0x65, 0xc6,
	0xc8, 0x67, 0xf0, 0x6c, 0xee, 0x06, 0x81, 0x1b, 0x4c, 0x6c, 0x8e, 0x09, 0x97, 0x59, 0xec, 0x28,
	0xcc, 0xc4, 0x1c, 0x7f, 0x0e, 0x6b, 0x3f, 0x2a, 0x91, 0xeb, 0x19, 0x67, 0x54, 0xe5, 0xf3, 0x99,
	0x02, 0x8f, 0x11, 0xc3, 0xf7, 0x95, 0x84, 0x09, 0xf5, 0x94, 0x88, 0x7c, 0x9b, 0x20, 0x20, 0x29,
	0xf0, 0x25, 0x10, 0x1c, 0xed, 0xe9, 0x65, 0x71, 0xc2, 0x19, 0xf5, 0xd5, 0x3b, 0xed, 0xfa, 0xf4,
	0x56, 0x59, 0xb3, 0x04, 0x8e, 0x6e, 0xa1, 0xb4, 0x3f, 0xf3, 0x12, 0x17, 0x57, 0x81, 0x7c, 0xaf,
	0x1d, 0x9f, 0xde, 0x5e, 0x28, 0x48, 0xf7, 0x60, 0x3b, 0xdb, 0xd0, 0x03, 0x9a, 0x3c, 0x39, 0xaf,
	0x69, 0xf9, 0xab, 0xb9, 0xf2, 0xe7, 0xea, 0x5b, 0xcb, 0xd7, 0x57, 0xff, 0xa3, 0x0a, 0x9b, 0xd9,
	0xeb, 0x9e, 0xd4, 0xf8, 0xe4, 0x00, 0xb4, 0xd0, 0x73, 0xec, 0x47, 0x7a, 0xb9, 0x1d, 0x7a, 0x8e,
	0xf8, 0x85, 0xf2, 0x01, 0x9b, 0x2b, 0xf9, 0x5a, 0xa9, 0x7c, 0xc0, 0xe6, 0xd6, 0x72, 0xfb, 0xd7,
	0x4b, 0xdb, 0xbf, 0x91, 0x6f, 0xff, 0x37, 0xd0, 0xc1, 0xdd, 0xcf, 0xb8, 0xdc, 0xd0, 0x4d, 0x71,
	0x4b, 0x57, 0xde, 0x62, 0x09, 0x02, 0x37, 0xb5, 0x09, 0xf1, 0xe2, 0x37, 0x16, 0x57, 0xa9, 0x64,
	0x7a, 0x5f, 0x09, 0x88, 0xec, 0xfc, 0x5e, 0x81, 0x9d, 0x5c, 0x76, 0x16, 0xd4, 0xa3, 0x29, 0x5a,
	0x72, 0xa7, 0xf1, 0xff, 0xdd, 0x69, 0xae, 0xb8, 0x73, 0x0a, 0xeb, 0x59, 0x6f, 0x3e, 0x72, 0xce,
	0xbd, 0x85, 0x6d, 0x23, 0x70, 0x13, 0x33, 0xbc, 0x0e, 0x0b, 0xa6, 0x1d, 0x47, 0xd8, 0x76, 0x9d,
	0xb8, 0x57, 0xd9, 0xab, 0x61, 0x44, 0x02, 0x30, 0x9c, 0x58, 0x9f, 0x94, 0xe8, 0x3d, 0xec, 0xc5,
	0x1b, 0xe8, 0x48, 0x93, 0x69, 0xb3, 0xd4, 0xf6, 0x3b, 0x69, 0x1e, 0x84, 0x29, 0x69, 0x04, 0xf8,
	0xe2, 0xb7, 0xfe, 0x13, 0xc0, 0x3d, 0x83, 0xb6, 0x53, 0x9f, 0x54, 0x92, 0x5b, 0xca, 0x25, 0x72,
	0xb8, 0x6c, 0xbb, 0xa4, 0xb1, 0x32, 0xc6, 0x5f, 0x0f, 0xa0, 0x93, 0xa1, 0x08, 0x40, 0x73, 0x68,
	0xd9, 0x97, 0xc6, 0x79, 0xf7, 0x13, 0xd2, 0x81, 0xd6, 0xd0, 0xb2, 0x8d, 0x53, 0xe3, 0x5d, 0xb7,
	0x42, 0x9e, 0x03, 0x0c, 0x2d, 0x7b, 0x70, 0x74, 0xf1, 0xce, 0xb8, 0x1c, 0x74, 0xab, 0x64, 0x1d,
	0x3a, 0x43, 0xcb, 0xbe, 0x38, 0x1a, 0x9d, 0x9c, 0x21, 0x50, 0x7b, 0xfd, 0x1d, 0xc0, 0x7d, 0x1d,
	0xd1, 0x8e, 0x35, 0xba, 0xb7, 0x63, 0x8d, 0xec, 0xc1, 0xd1, 0x08, 0xed, 0x3c, 0x83, 0xb6, 0x35,
	0x92, 0x7a, 0xdd, 0xaa, 0xa2, 0xcc, 0xab, 0xab, 0x8b, 0x6e, 0xed, 0xf0, 0xef, 0x06, 0x80, 0xf4,
	0xe5, 0x94, 0x26, 0x94, 0x5c, 0x02, 0x59, 0xfd, 0x0a, 0x22, 0x2f, 0x65, 0x38, 0x85, 0xdf, 0x55,
	0xfd, 0x72, 0x32, 0x8e, 0xc8, 0xb7, 0xb0, 0x96, 0xfb, 0xa4, 0x21, 0x5b, 0x4b, 0xd2, 0x6a, 0xac,
	0xf4, 0x0b, 0xf1, 0x38, 0x22, 0x67, 0xd0, 0x5d, 0x5e, 0xad, 0x64, 0x47, 0xca, 0x16, 0x7c, 0x1d,
	0xf4, 0xcb, 0xa8, 0x38, 0x22, 0xc7, 0xf0, 0x3c, 0xbf, 0x27, 0xc9, 0xf6, 0xd2, 0x9d, 0x69, 0x0b,
	0xf6, 0x8b, 0x89, 0x38, 0x22, 0x3f, 0x64, 0x76, 0x6d, 0xba, 0x1d, 0x48, 0x7f, 0x49, 0x3a, 0xb3,
	0x85, 0xfa, 0xa5, 0x5c, 0x1c, 0x91, 0xef, 0x61, 0x63, 0x65, 0xea, 0xa5, 0xc6, 0x8a, 0xc6, 0x61,
	0xff, 0xc5, 0x2a, 0x87, 0x76, 0xce, 0xf3, 0xd3, 0x33, 0x1d, 0xd6, 0xe4, 0xd5, 0xaa, 0x78, 0x66,
	0x90, 0x97, 0x59, 0x1b, 0xc2, 0x56, 0xf1, 0xb4, 0x21, 0xbb, 0x05, 0xae, 0x65, 0x67, 0x51, 0x99,
	0xc5, 0x11, 0x6c, 0x16, 0xbd, 0xd9, 0xd4, 0xbf, 0x92, 0x39, 0xd0, 0x7f, 0x88, 0x8e, 0xa3, 0xeb,
	0xa6, 0xf8, 0x73, 0xf5, 0xcd, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0x47, 0x7f, 0xb1, 0x6d,
	0x0d, 0x00, 0x00,
}
