// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alms.proto

/*
Package alms is a generated protocol buffer package.

It is generated from these files:
	alms.proto

It has these top-level messages:
	AlmsGetGoldReq
	GameLevelIsOpen
	AlmsConfig
	AlmsGetGoldRsp
	AlmsLoginGoldConfigNtf
	PacksackInfoRep
	PacksackPropInfo
	PacksackInfoRsp
	PacksackGoldReq
	PacksackGoldRsp
*/
package alms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AlmsReqType 救济金请求类型
type AlmsReqType int32

const (
	AlmsReqType_ART_INVALID_PROP AlmsReqType = 0
	AlmsReqType_LOGIN            AlmsReqType = 1
	AlmsReqType_SELECTED         AlmsReqType = 2
	AlmsReqType_INGAME           AlmsReqType = 3
)

var AlmsReqType_name = map[int32]string{
	0: "ART_INVALID_PROP",
	1: "LOGIN",
	2: "SELECTED",
	3: "INGAME",
}
var AlmsReqType_value = map[string]int32{
	"ART_INVALID_PROP": 0,
	"LOGIN":            1,
	"SELECTED":         2,
	"INGAME":           3,
}

func (x AlmsReqType) Enum() *AlmsReqType {
	p := new(AlmsReqType)
	*p = x
	return p
}
func (x AlmsReqType) String() string {
	return proto.EnumName(AlmsReqType_name, int32(x))
}
func (x *AlmsReqType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AlmsReqType_value, data, "AlmsReqType")
	if err != nil {
		return err
	}
	*x = AlmsReqType(value)
	return nil
}
func (AlmsReqType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// PropType 具类型
type PropType int32

const (
	PropType_INVALID_PROP PropType = 0
	PropType_INTERACTIVE  PropType = 1
	PropType_SPEEDY       PropType = 2
)

var PropType_name = map[int32]string{
	0: "INVALID_PROP",
	1: "INTERACTIVE",
	2: "SPEEDY",
}
var PropType_value = map[string]int32{
	"INVALID_PROP": 0,
	"INTERACTIVE":  1,
	"SPEEDY":       2,
}

func (x PropType) Enum() *PropType {
	p := new(PropType)
	*p = x
	return p
}
func (x PropType) String() string {
	return proto.EnumName(PropType_name, int32(x))
}
func (x *PropType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PropType_value, data, "PropType")
	if err != nil {
		return err
	}
	*x = PropType(value)
	return nil
}
func (PropType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// msgid:ALMS_GET_GOLD_REQ = 0x6001;  	             // 获取救济金请求
// 获取救济金请求(玩家申请救济金请求)
type AlmsGetGoldReq struct {
	Version          *int32       `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	ReqType          *AlmsReqType `protobuf:"varint,2,opt,name=req_type,json=reqType,enum=alms.AlmsReqType" json:"req_type,omitempty"`
	GameId           *int32       `protobuf:"varint,3,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId          *int32       `protobuf:"varint,4,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *AlmsGetGoldReq) Reset()                    { *m = AlmsGetGoldReq{} }
func (m *AlmsGetGoldReq) String() string            { return proto.CompactTextString(m) }
func (*AlmsGetGoldReq) ProtoMessage()               {}
func (*AlmsGetGoldReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AlmsGetGoldReq) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AlmsGetGoldReq) GetReqType() AlmsReqType {
	if m != nil && m.ReqType != nil {
		return *m.ReqType
	}
	return AlmsReqType_ART_INVALID_PROP
}

func (m *AlmsGetGoldReq) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *AlmsGetGoldReq) GetLevelId() int32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

// 场次是否开启救济金
type GameLevelIsOpen struct {
	GameId           *int32 `protobuf:"varint,1,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId          *int32 `protobuf:"varint,2,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	IsOpen           *int32 `protobuf:"varint,3,opt,name=is_open,json=isOpen" json:"is_open,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GameLevelIsOpen) Reset()                    { *m = GameLevelIsOpen{} }
func (m *GameLevelIsOpen) String() string            { return proto.CompactTextString(m) }
func (*GameLevelIsOpen) ProtoMessage()               {}
func (*GameLevelIsOpen) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GameLevelIsOpen) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *GameLevelIsOpen) GetLevelId() int32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

func (m *GameLevelIsOpen) GetIsOpen() int32 {
	if m != nil && m.IsOpen != nil {
		return *m.IsOpen
	}
	return 0
}

// 救济金配置
type AlmsConfig struct {
	AlmsGetNorm      *int64             `protobuf:"varint,1,opt,name=alms_get_norm,json=almsGetNorm" json:"alms_get_norm,omitempty"`
	AlmsGetTimes     *int32             `protobuf:"varint,2,opt,name=alms_get_times,json=almsGetTimes" json:"alms_get_times,omitempty"`
	AlmsGetNumber    *int64             `protobuf:"varint,3,opt,name=alms_get_number,json=almsGetNumber" json:"alms_get_number,omitempty"`
	AlmsCountDonw    *int32             `protobuf:"varint,4,opt,name=alms_count_donw,json=almsCountDonw" json:"alms_count_donw,omitempty"`
	DepositCountDonw *int32             `protobuf:"varint,5,opt,name=deposit_count_donw,json=depositCountDonw" json:"deposit_count_donw,omitempty"`
	Version          *int32             `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`
	GameLevelIsOpen  []*GameLevelIsOpen `protobuf:"bytes,7,rep,name=game_level_isOpen,json=gameLevelIsOpen" json:"game_level_isOpen,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *AlmsConfig) Reset()                    { *m = AlmsConfig{} }
func (m *AlmsConfig) String() string            { return proto.CompactTextString(m) }
func (*AlmsConfig) ProtoMessage()               {}
func (*AlmsConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AlmsConfig) GetAlmsGetNorm() int64 {
	if m != nil && m.AlmsGetNorm != nil {
		return *m.AlmsGetNorm
	}
	return 0
}

func (m *AlmsConfig) GetAlmsGetTimes() int32 {
	if m != nil && m.AlmsGetTimes != nil {
		return *m.AlmsGetTimes
	}
	return 0
}

func (m *AlmsConfig) GetAlmsGetNumber() int64 {
	if m != nil && m.AlmsGetNumber != nil {
		return *m.AlmsGetNumber
	}
	return 0
}

func (m *AlmsConfig) GetAlmsCountDonw() int32 {
	if m != nil && m.AlmsCountDonw != nil {
		return *m.AlmsCountDonw
	}
	return 0
}

func (m *AlmsConfig) GetDepositCountDonw() int32 {
	if m != nil && m.DepositCountDonw != nil {
		return *m.DepositCountDonw
	}
	return 0
}

func (m *AlmsConfig) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AlmsConfig) GetGameLevelIsOpen() []*GameLevelIsOpen {
	if m != nil {
		return m.GameLevelIsOpen
	}
	return nil
}

// msgid:ALMS_GET_GOLD_RSP = 0x6002;
// 获取救济金应答(玩家申请救济金响应)
type AlmsGetGoldRsp struct {
	PlayerAlmsTimes  *int32      `protobuf:"varint,1,opt,name=player_alms_times,json=playerAlmsTimes" json:"player_alms_times,omitempty"`
	ChangeGold       *int64      `protobuf:"varint,2,opt,name=change_gold,json=changeGold" json:"change_gold,omitempty"`
	NewVersion       *int32      `protobuf:"varint,3,opt,name=new_version,json=newVersion" json:"new_version,omitempty"`
	NewAlmsConfig    *AlmsConfig `protobuf:"bytes,4,opt,name=new_alms_config,json=newAlmsConfig" json:"new_alms_config,omitempty"`
	Result           *bool       `protobuf:"varint,5,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *AlmsGetGoldRsp) Reset()                    { *m = AlmsGetGoldRsp{} }
func (m *AlmsGetGoldRsp) String() string            { return proto.CompactTextString(m) }
func (*AlmsGetGoldRsp) ProtoMessage()               {}
func (*AlmsGetGoldRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AlmsGetGoldRsp) GetPlayerAlmsTimes() int32 {
	if m != nil && m.PlayerAlmsTimes != nil {
		return *m.PlayerAlmsTimes
	}
	return 0
}

func (m *AlmsGetGoldRsp) GetChangeGold() int64 {
	if m != nil && m.ChangeGold != nil {
		return *m.ChangeGold
	}
	return 0
}

func (m *AlmsGetGoldRsp) GetNewVersion() int32 {
	if m != nil && m.NewVersion != nil {
		return *m.NewVersion
	}
	return 0
}

func (m *AlmsGetGoldRsp) GetNewAlmsConfig() *AlmsConfig {
	if m != nil {
		return m.NewAlmsConfig
	}
	return nil
}

func (m *AlmsGetGoldRsp) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

// ALMS_LOGIN_GOLD_CONFIG_NTF = 0x6003;         // 玩家登陆救济金配置通知
// 救济金配置通知
type AlmsLoginGoldConfigNtf struct {
	AlmsConfig       *AlmsConfig `protobuf:"bytes,1,opt,name=alms_config,json=almsConfig" json:"alms_config,omitempty"`
	PlayerGotTimes   *int32      `protobuf:"varint,2,opt,name=player_got_times,json=playerGotTimes" json:"player_got_times,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *AlmsLoginGoldConfigNtf) Reset()                    { *m = AlmsLoginGoldConfigNtf{} }
func (m *AlmsLoginGoldConfigNtf) String() string            { return proto.CompactTextString(m) }
func (*AlmsLoginGoldConfigNtf) ProtoMessage()               {}
func (*AlmsLoginGoldConfigNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AlmsLoginGoldConfigNtf) GetAlmsConfig() *AlmsConfig {
	if m != nil {
		return m.AlmsConfig
	}
	return nil
}

func (m *AlmsLoginGoldConfigNtf) GetPlayerGotTimes() int32 {
	if m != nil && m.PlayerGotTimes != nil {
		return *m.PlayerGotTimes
	}
	return 0
}

// PACKSACK_INFO_REQ = 0x6004;            // 玩家登录背包信息请求
type PacksackInfoRep struct {
	Reserved         *int32 `protobuf:"varint,1,opt,name=reserved" json:"reserved,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PacksackInfoRep) Reset()                    { *m = PacksackInfoRep{} }
func (m *PacksackInfoRep) String() string            { return proto.CompactTextString(m) }
func (*PacksackInfoRep) ProtoMessage()               {}
func (*PacksackInfoRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PacksackInfoRep) GetReserved() int32 {
	if m != nil && m.Reserved != nil {
		return *m.Reserved
	}
	return 0
}

// PacksackPropInfo 背包道具信息
type PacksackPropInfo struct {
	PropId           *int32    `protobuf:"varint,1,opt,name=prop_id,json=propId" json:"prop_id,omitempty"`
	PropName         *string   `protobuf:"bytes,2,opt,name=prop_name,json=propName" json:"prop_name,omitempty"`
	PropType         *PropType `protobuf:"varint,3,opt,name=prop_type,json=propType,enum=alms.PropType" json:"prop_type,omitempty"`
	PropCount        *int64    `protobuf:"varint,5,opt,name=prop_count,json=propCount" json:"prop_count,omitempty"`
	PropDescribe     *string   `protobuf:"bytes,6,opt,name=prop_describe,json=propDescribe" json:"prop_describe,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *PacksackPropInfo) Reset()                    { *m = PacksackPropInfo{} }
func (m *PacksackPropInfo) String() string            { return proto.CompactTextString(m) }
func (*PacksackPropInfo) ProtoMessage()               {}
func (*PacksackPropInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PacksackPropInfo) GetPropId() int32 {
	if m != nil && m.PropId != nil {
		return *m.PropId
	}
	return 0
}

func (m *PacksackPropInfo) GetPropName() string {
	if m != nil && m.PropName != nil {
		return *m.PropName
	}
	return ""
}

func (m *PacksackPropInfo) GetPropType() PropType {
	if m != nil && m.PropType != nil {
		return *m.PropType
	}
	return PropType_INVALID_PROP
}

func (m *PacksackPropInfo) GetPropCount() int64 {
	if m != nil && m.PropCount != nil {
		return *m.PropCount
	}
	return 0
}

func (m *PacksackPropInfo) GetPropDescribe() string {
	if m != nil && m.PropDescribe != nil {
		return *m.PropDescribe
	}
	return ""
}

// PACKSACK_INFO_RSP = 0x6005;            // 玩家登录背包信息通知
// PacksackInfoRsp   玩家背包信息
type PacksackInfoRsp struct {
	PropInfo         []*PacksackPropInfo `protobuf:"bytes,1,rep,name=prop_info,json=propInfo" json:"prop_info,omitempty"`
	PacksackGold     *int64              `protobuf:"varint,2,opt,name=packsack_gold,json=packsackGold" json:"packsack_gold,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PacksackInfoRsp) Reset()                    { *m = PacksackInfoRsp{} }
func (m *PacksackInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*PacksackInfoRsp) ProtoMessage()               {}
func (*PacksackInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PacksackInfoRsp) GetPropInfo() []*PacksackPropInfo {
	if m != nil {
		return m.PropInfo
	}
	return nil
}

func (m *PacksackInfoRsp) GetPacksackGold() int64 {
	if m != nil && m.PacksackGold != nil {
		return *m.PacksackGold
	}
	return 0
}

// PACKSACK_GOLD_REQ = 0x6006;                  // 背包金币请求
// PacksackGoldReq 背包金币存入存出请求
type PacksackGoldReq struct {
	ChangeGold       *int64 `protobuf:"varint,1,opt,name=change_gold,json=changeGold" json:"change_gold,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PacksackGoldReq) Reset()                    { *m = PacksackGoldReq{} }
func (m *PacksackGoldReq) String() string            { return proto.CompactTextString(m) }
func (*PacksackGoldReq) ProtoMessage()               {}
func (*PacksackGoldReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PacksackGoldReq) GetChangeGold() int64 {
	if m != nil && m.ChangeGold != nil {
		return *m.ChangeGold
	}
	return 0
}

// PACKSACK_GOLD_RSP = 0x6007;                  // 背包金币响应
// PacksackGoldRsp 背包金币存入存出响应
type PacksackGoldRsp struct {
	Result           *bool  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	ChangeGold       *int64 `protobuf:"varint,2,opt,name=change_gold,json=changeGold" json:"change_gold,omitempty"`
	PacksackGold     *int64 `protobuf:"varint,3,opt,name=packsack_gold,json=packsackGold" json:"packsack_gold,omitempty"`
	Gold             *int64 `protobuf:"varint,4,opt,name=gold" json:"gold,omitempty"`
	ProcedureFee     *int64 `protobuf:"varint,5,opt,name=procedure_fee,json=procedureFee" json:"procedure_fee,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PacksackGoldRsp) Reset()                    { *m = PacksackGoldRsp{} }
func (m *PacksackGoldRsp) String() string            { return proto.CompactTextString(m) }
func (*PacksackGoldRsp) ProtoMessage()               {}
func (*PacksackGoldRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PacksackGoldRsp) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

func (m *PacksackGoldRsp) GetChangeGold() int64 {
	if m != nil && m.ChangeGold != nil {
		return *m.ChangeGold
	}
	return 0
}

func (m *PacksackGoldRsp) GetPacksackGold() int64 {
	if m != nil && m.PacksackGold != nil {
		return *m.PacksackGold
	}
	return 0
}

func (m *PacksackGoldRsp) GetGold() int64 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *PacksackGoldRsp) GetProcedureFee() int64 {
	if m != nil && m.ProcedureFee != nil {
		return *m.ProcedureFee
	}
	return 0
}

func init() {
	proto.RegisterType((*AlmsGetGoldReq)(nil), "alms.AlmsGetGoldReq")
	proto.RegisterType((*GameLevelIsOpen)(nil), "alms.GameLevelIsOpen")
	proto.RegisterType((*AlmsConfig)(nil), "alms.AlmsConfig")
	proto.RegisterType((*AlmsGetGoldRsp)(nil), "alms.AlmsGetGoldRsp")
	proto.RegisterType((*AlmsLoginGoldConfigNtf)(nil), "alms.AlmsLoginGoldConfigNtf")
	proto.RegisterType((*PacksackInfoRep)(nil), "alms.PacksackInfoRep")
	proto.RegisterType((*PacksackPropInfo)(nil), "alms.PacksackPropInfo")
	proto.RegisterType((*PacksackInfoRsp)(nil), "alms.PacksackInfoRsp")
	proto.RegisterType((*PacksackGoldReq)(nil), "alms.PacksackGoldReq")
	proto.RegisterType((*PacksackGoldRsp)(nil), "alms.PacksackGoldRsp")
	proto.RegisterEnum("alms.AlmsReqType", AlmsReqType_name, AlmsReqType_value)
	proto.RegisterEnum("alms.PropType", PropType_name, PropType_value)
}

func init() { proto.RegisterFile("alms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 794 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6e, 0xeb, 0x44,
	0x10, 0xc6, 0x71, 0x7f, 0xd2, 0x49, 0x9a, 0xb8, 0xab, 0x43, 0x09, 0x20, 0x44, 0x65, 0x10, 0xaa,
	0xca, 0xe1, 0x1c, 0x51, 0x6e, 0xe0, 0x32, 0x34, 0x26, 0x58, 0x0a, 0x69, 0xb4, 0x27, 0xaa, 0x04,
	0x17, 0x58, 0x6e, 0x3c, 0x31, 0x56, 0xed, 0x5d, 0xd7, 0x76, 0x1a, 0xf5, 0x1d, 0x78, 0x10, 0x6e,
	0xb9, 0xe4, 0x2d, 0x78, 0x24, 0xb4, 0xb3, 0xeb, 0xc6, 0xf5, 0x51, 0xc5, 0x9d, 0x67, 0xe6, 0xdb,
	0xf9, 0xf9, 0xe6, 0x1b, 0x03, 0x84, 0x69, 0x56, 0xbe, 0xc9, 0x0b, 0x59, 0x49, 0xb6, 0xa7, 0xbe,
	0xdd, 0x3f, 0x2d, 0x18, 0x8c, 0xd3, 0xac, 0x9c, 0x62, 0x35, 0x95, 0x69, 0xc4, 0xf1, 0x9e, 0x8d,
	0xe0, 0xf0, 0x01, 0x8b, 0x32, 0x91, 0x62, 0x64, 0x9d, 0x59, 0xe7, 0xfb, 0xbc, 0x36, 0xd9, 0x6b,
	0xe8, 0x16, 0x78, 0x1f, 0x54, 0x8f, 0x39, 0x8e, 0x3a, 0x67, 0xd6, 0xf9, 0xe0, 0xf2, 0xe4, 0x0d,
	0x65, 0x54, 0x19, 0x38, 0xde, 0x2f, 0x1f, 0x73, 0xe4, 0x87, 0x85, 0xfe, 0x60, 0x1f, 0xc1, 0x61,
	0x1c, 0x66, 0x18, 0x24, 0xd1, 0xc8, 0xa6, 0x3c, 0x07, 0xca, 0xf4, 0x23, 0xf6, 0x31, 0x74, 0x53,
	0x7c, 0xc0, 0x54, 0x45, 0xf6, 0x74, 0x05, 0xb2, 0xfd, 0xc8, 0xfd, 0x1d, 0x86, 0xd3, 0x30, 0xc3,
	0x19, 0x99, 0xe5, 0x75, 0x8e, 0xa2, 0x99, 0xc6, 0x7a, 0x31, 0x4d, 0xe7, 0x59, 0x1a, 0xf5, 0x26,
	0x29, 0x03, 0x99, 0xa3, 0xa8, 0x4b, 0x27, 0x94, 0xcc, 0xfd, 0xbb, 0x03, 0xa0, 0x9a, 0xbd, 0x92,
	0x62, 0x9d, 0xc4, 0xcc, 0x85, 0x63, 0xd5, 0x7f, 0x10, 0x63, 0x15, 0x08, 0x59, 0x64, 0x54, 0xc1,
	0xe6, 0xbd, 0x50, 0x33, 0x32, 0x97, 0x45, 0xc6, 0xbe, 0x84, 0xc1, 0x13, 0xa6, 0x4a, 0x32, 0x2c,
	0x4d, 0xb1, 0xbe, 0x01, 0x2d, 0x95, 0x8f, 0x7d, 0x05, 0xc3, 0x5d, 0xa6, 0x4d, 0x76, 0x8b, 0x05,
	0x55, 0xb6, 0xf9, 0x71, 0x9d, 0x8b, 0x9c, 0x4f, 0xb8, 0x95, 0xdc, 0x88, 0x2a, 0x88, 0xa4, 0xd8,
	0x1a, 0x0a, 0x08, 0x77, 0xa5, 0xbc, 0x13, 0x29, 0xb6, 0xec, 0x35, 0xb0, 0x08, 0x73, 0x59, 0x26,
	0x55, 0x13, 0xba, 0x4f, 0x50, 0xc7, 0x44, 0x76, 0xe8, 0xc6, 0xca, 0x0e, 0x9e, 0xaf, 0x6c, 0x0c,
	0x27, 0xc4, 0x9e, 0x61, 0x8a, 0x58, 0x18, 0x1d, 0x9e, 0xd9, 0xe7, 0xbd, 0xcb, 0x0f, 0xf5, 0xee,
	0x5a, 0x7c, 0xf3, 0x61, 0xfc, 0xdc, 0xe1, 0xfe, 0xdb, 0x92, 0x48, 0x99, 0xb3, 0x0b, 0x38, 0xc9,
	0xd3, 0xf0, 0x11, 0x8b, 0x80, 0x86, 0xd1, 0xb4, 0xe8, 0xed, 0x0c, 0x75, 0x40, 0x3d, 0xd0, 0xcc,
	0x7c, 0x0e, 0xbd, 0xd5, 0x1f, 0xa1, 0x88, 0x31, 0x88, 0x65, 0xaa, 0x37, 0x65, 0x73, 0xd0, 0x2e,
	0x95, 0x4f, 0x01, 0x04, 0x6e, 0x83, 0x7a, 0x00, 0xbd, 0x30, 0x10, 0xb8, 0xbd, 0x31, 0x33, 0x7c,
	0x0f, 0x43, 0x05, 0x30, 0xbc, 0xa9, 0xc5, 0x11, 0x67, 0xbd, 0x4b, 0x67, 0xa7, 0x3e, 0xbd, 0x50,
	0x7e, 0x2c, 0x70, 0xdb, 0xd8, 0xef, 0x29, 0x1c, 0x14, 0x58, 0x6e, 0xd2, 0x8a, 0x98, 0xeb, 0x72,
	0x63, 0xb9, 0x1b, 0x38, 0x55, 0xa8, 0x99, 0x8c, 0x13, 0xa1, 0x7a, 0xd0, 0xf0, 0x79, 0xb5, 0x66,
	0xdf, 0x42, 0xaf, 0x59, 0xc7, 0x7a, 0xa1, 0x0e, 0x84, 0xbb, 0x22, 0xe7, 0xe0, 0x18, 0x32, 0x62,
	0xf9, 0x5c, 0x22, 0x03, 0xed, 0x9f, 0x4a, 0x2d, 0x12, 0xf7, 0x1b, 0x18, 0x2e, 0xc2, 0xd5, 0x5d,
	0x19, 0xae, 0xee, 0x7c, 0xb1, 0x96, 0x1c, 0x73, 0xf6, 0x89, 0x3a, 0xa9, 0x12, 0x8b, 0x07, 0xac,
	0xe5, 0xfd, 0x64, 0xbb, 0xff, 0x58, 0xe0, 0xd4, 0xf8, 0x45, 0x21, 0x73, 0xf5, 0x46, 0x49, 0x3b,
	0x2f, 0x64, 0xde, 0x38, 0x07, 0x65, 0xfa, 0x11, 0xfb, 0x14, 0x8e, 0x28, 0x20, 0xc2, 0x4c, 0x5f,
	0xe7, 0x11, 0xef, 0x2a, 0xc7, 0x3c, 0xcc, 0x90, 0x7d, 0x6d, 0x82, 0x74, 0xba, 0x36, 0x9d, 0xee,
	0x40, 0x0f, 0xa5, 0x12, 0xd3, 0xdd, 0x12, 0x98, 0x0e, 0xf7, 0x33, 0x00, 0x02, 0x93, 0xf0, 0x88,
	0x39, 0x9b, 0xd3, 0x73, 0x12, 0x1c, 0xfb, 0x02, 0x8e, 0x29, 0x1c, 0x61, 0xb9, 0x2a, 0x92, 0x5b,
	0x24, 0xc9, 0x1d, 0xf1, 0xbe, 0x72, 0x4e, 0x8c, 0xcf, 0xbd, 0x6b, 0x8d, 0x5a, 0xe6, 0xec, 0x3b,
	0xd3, 0x43, 0x22, 0xd6, 0x72, 0x64, 0x91, 0x04, 0x4f, 0x4d, 0x0f, 0xad, 0x21, 0x75, 0x2f, 0x34,
	0xae, 0x2a, 0x66, 0xa2, 0x4d, 0xfd, 0xf4, 0x6b, 0xa7, 0xda, 0x9e, 0x7b, 0xb9, 0x2b, 0x56, 0xff,
	0xc4, 0x5a, 0xaa, 0xb3, 0xda, 0xaa, 0x73, 0xff, 0xb2, 0x5a, 0x8f, 0xca, 0xbc, 0x21, 0x17, 0xab,
	0x29, 0x97, 0xff, 0x97, 0xf0, 0x7b, 0x5d, 0xda, 0xef, 0x77, 0xc9, 0x18, 0xec, 0x51, 0x6c, 0x8f,
	0x62, 0xf4, 0x6d, 0xb8, 0x5c, 0x61, 0xb4, 0x29, 0x30, 0x58, 0x23, 0x1a, 0xb6, 0xfb, 0x4f, 0xce,
	0x9f, 0x10, 0x2f, 0x7e, 0x86, 0x5e, 0xe3, 0x07, 0xcb, 0x5e, 0x81, 0x33, 0xe6, 0xcb, 0xc0, 0x9f,
	0xdf, 0x8c, 0x67, 0xfe, 0x24, 0x58, 0xf0, 0xeb, 0x85, 0xf3, 0x01, 0x3b, 0x82, 0xfd, 0xd9, 0xf5,
	0xd4, 0x9f, 0x3b, 0x16, 0xeb, 0x43, 0xf7, 0x9d, 0x37, 0xf3, 0xae, 0x96, 0xde, 0xc4, 0xe9, 0x30,
	0x80, 0x03, 0x7f, 0x3e, 0x1d, 0xff, 0xe2, 0x39, 0xf6, 0xc5, 0x0f, 0xd0, 0xad, 0xf7, 0xcd, 0x1c,
	0xe8, 0xb7, 0x52, 0x0c, 0xa1, 0xe7, 0xcf, 0x97, 0x1e, 0x1f, 0x5f, 0x2d, 0xfd, 0x1b, 0xcf, 0xb1,
	0xd4, 0xd3, 0x77, 0x0b, 0xcf, 0x9b, 0xfc, 0xea, 0x74, 0x7e, 0x3c, 0xfd, 0xed, 0x55, 0x59, 0xe1,
	0x03, 0xbe, 0x5d, 0xa5, 0x09, 0x8a, 0x2a, 0xc8, 0x6f, 0xdf, 0xaa, 0xdd, 0xfd, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x15, 0xf9, 0x43, 0x02, 0x53, 0x06, 0x00, 0x00,
}
