// Code generated by protoc-gen-go. DO NOT EDIT.
// source: match.proto

package match

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "steve/client_pb/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MatchReq 匹配请求
type MatchReq struct {
	Reserve          *uint32                        `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	GameId           *uint32                        `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId          *uint32                        `protobuf:"varint,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	Location         []*common.GeographicalLocation `protobuf:"bytes,4,rep,name=location" json:"location,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *MatchReq) Reset()                    { *m = MatchReq{} }
func (m *MatchReq) String() string            { return proto.CompactTextString(m) }
func (*MatchReq) ProtoMessage()               {}
func (*MatchReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MatchReq) GetReserve() uint32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

func (m *MatchReq) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *MatchReq) GetLevelId() uint32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

func (m *MatchReq) GetLocation() []*common.GeographicalLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

// MatchRsp 匹配应答
type MatchRsp struct {
	ErrCode          *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc          *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	GameId           *uint32 `protobuf:"varint,3,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId          *uint32 `protobuf:"varint,4,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MatchRsp) Reset()                    { *m = MatchRsp{} }
func (m *MatchRsp) String() string            { return proto.CompactTextString(m) }
func (*MatchRsp) ProtoMessage()               {}
func (*MatchRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *MatchRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MatchRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *MatchRsp) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *MatchRsp) GetLevelId() uint32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

// DeskPlayerInfo 桌子玩家数据
type DeskPlayerInfo struct {
	PlayerId         *uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Coin             *int64  `protobuf:"varint,3,opt,name=coin" json:"coin,omitempty"`
	Seat             *int32  `protobuf:"varint,4,opt,name=seat" json:"seat,omitempty"`
	Gender           *uint32 `protobuf:"varint,5,opt,name=gender" json:"gender,omitempty"`
	Avatar           *string `protobuf:"bytes,6,opt,name=avatar" json:"avatar,omitempty"`
	ShowUid          *int64  `protobuf:"varint,7,opt,name=show_uid,json=showUid" json:"show_uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeskPlayerInfo) Reset()                    { *m = DeskPlayerInfo{} }
func (m *DeskPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*DeskPlayerInfo) ProtoMessage()               {}
func (*DeskPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *DeskPlayerInfo) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *DeskPlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DeskPlayerInfo) GetCoin() int64 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *DeskPlayerInfo) GetSeat() int32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *DeskPlayerInfo) GetGender() uint32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *DeskPlayerInfo) GetAvatar() string {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return ""
}

func (m *DeskPlayerInfo) GetShowUid() int64 {
	if m != nil && m.ShowUid != nil {
		return *m.ShowUid
	}
	return 0
}

// 匹配成功时的创建桌子消息
type MatchSucCreateDeskNtf struct {
	Players          []*DeskPlayerInfo `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	GameId           *uint32           `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId          *uint32           `protobuf:"varint,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MatchSucCreateDeskNtf) Reset()                    { *m = MatchSucCreateDeskNtf{} }
func (m *MatchSucCreateDeskNtf) String() string            { return proto.CompactTextString(m) }
func (*MatchSucCreateDeskNtf) ProtoMessage()               {}
func (*MatchSucCreateDeskNtf) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *MatchSucCreateDeskNtf) GetPlayers() []*DeskPlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *MatchSucCreateDeskNtf) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *MatchSucCreateDeskNtf) GetLevelId() uint32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

// MatchDeskContinueReq 续局请求
type MatchDeskContinueReq struct {
	GameId           *uint32                        `protobuf:"varint,1,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	Location         []*common.GeographicalLocation `protobuf:"bytes,2,rep,name=location" json:"location,omitempty"`
	Cancel           *bool                          `protobuf:"varint,3,opt,name=cancel" json:"cancel,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *MatchDeskContinueReq) Reset()                    { *m = MatchDeskContinueReq{} }
func (m *MatchDeskContinueReq) String() string            { return proto.CompactTextString(m) }
func (*MatchDeskContinueReq) ProtoMessage()               {}
func (*MatchDeskContinueReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *MatchDeskContinueReq) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *MatchDeskContinueReq) GetLocation() []*common.GeographicalLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *MatchDeskContinueReq) GetCancel() bool {
	if m != nil && m.Cancel != nil {
		return *m.Cancel
	}
	return false
}

// MatchDeskContinueRsp 续局应答
type MatchDeskContinueRsp struct {
	ErrCode          *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc          *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MatchDeskContinueRsp) Reset()                    { *m = MatchDeskContinueRsp{} }
func (m *MatchDeskContinueRsp) String() string            { return proto.CompactTextString(m) }
func (*MatchDeskContinueRsp) ProtoMessage()               {}
func (*MatchDeskContinueRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *MatchDeskContinueRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MatchDeskContinueRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

// MatchContinueDeskDimissNtf 续局牌桌解散通知
type MatchContinueDeskDimissNtf struct {
	Reserve          *int32 `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MatchContinueDeskDimissNtf) Reset()                    { *m = MatchContinueDeskDimissNtf{} }
func (m *MatchContinueDeskDimissNtf) String() string            { return proto.CompactTextString(m) }
func (*MatchContinueDeskDimissNtf) ProtoMessage()               {}
func (*MatchContinueDeskDimissNtf) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *MatchContinueDeskDimissNtf) GetReserve() int32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

// CancelMatchReq 取消匹配请求
type CancelMatchReq struct {
	Reserve          *uint32 `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CancelMatchReq) Reset()                    { *m = CancelMatchReq{} }
func (m *CancelMatchReq) String() string            { return proto.CompactTextString(m) }
func (*CancelMatchReq) ProtoMessage()               {}
func (*CancelMatchReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *CancelMatchReq) GetReserve() uint32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

// CancelMatchRsp 取消匹配应答
type CancelMatchRsp struct {
	ErrCode          *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc          *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CancelMatchRsp) Reset()                    { *m = CancelMatchRsp{} }
func (m *CancelMatchRsp) String() string            { return proto.CompactTextString(m) }
func (*CancelMatchRsp) ProtoMessage()               {}
func (*CancelMatchRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *CancelMatchRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *CancelMatchRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func init() {
	proto.RegisterType((*MatchReq)(nil), "match.MatchReq")
	proto.RegisterType((*MatchRsp)(nil), "match.MatchRsp")
	proto.RegisterType((*DeskPlayerInfo)(nil), "match.DeskPlayerInfo")
	proto.RegisterType((*MatchSucCreateDeskNtf)(nil), "match.MatchSucCreateDeskNtf")
	proto.RegisterType((*MatchDeskContinueReq)(nil), "match.MatchDeskContinueReq")
	proto.RegisterType((*MatchDeskContinueRsp)(nil), "match.MatchDeskContinueRsp")
	proto.RegisterType((*MatchContinueDeskDimissNtf)(nil), "match.MatchContinueDeskDimissNtf")
	proto.RegisterType((*CancelMatchReq)(nil), "match.CancelMatchReq")
	proto.RegisterType((*CancelMatchRsp)(nil), "match.CancelMatchRsp")
}

func init() { proto.RegisterFile("match.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x95, 0x6d, 0xd3, 0x64, 0xbd, 0xb0, 0x07, 0x8b, 0xb2, 0x61, 0xe1, 0xb0, 0xca, 0x69,
	0xc5, 0xa1, 0x95, 0x38, 0x20, 0xce, 0xb4, 0x02, 0x55, 0x5a, 0x10, 0x32, 0xe2, 0xc2, 0xa5, 0x32,
	0xf6, 0x6c, 0x6b, 0x91, 0xd8, 0xc1, 0x76, 0x8b, 0x90, 0xb8, 0xf0, 0x0a, 0x3c, 0x0b, 0x0f, 0x88,
	0x66, 0x92, 0x54, 0x2d, 0x02, 0xa1, 0xed, 0xcd, 0xff, 0xcc, 0xe4, 0x9f, 0x2f, 0xe3, 0x31, 0x3b,
	0xab, 0x65, 0x54, 0xeb, 0x49, 0xe3, 0x5d, 0x74, 0x3c, 0x25, 0x71, 0x79, 0x4f, 0xb9, 0xba, 0x76,
	0xb6, 0x0d, 0x96, 0x3f, 0x13, 0x96, 0xbf, 0xc1, 0xb8, 0x80, 0x2f, 0xbc, 0x60, 0x99, 0x87, 0x00,
	0x7e, 0x0b, 0x45, 0x72, 0x95, 0x5c, 0xdf, 0x17, 0xbd, 0xe4, 0x17, 0x2c, 0x5b, 0xc9, 0x1a, 0x96,
	0x46, 0x17, 0x27, 0x94, 0x19, 0xa1, 0x5c, 0x68, 0xfe, 0x88, 0xe5, 0x15, 0x6c, 0xa1, 0xc2, 0xcc,
	0xa0, 0xfd, 0x86, 0xf4, 0x42, 0xf3, 0x17, 0x2c, 0xaf, 0x9c, 0x92, 0xd1, 0x38, 0x5b, 0x0c, 0xaf,
	0x06, 0xd7, 0x67, 0xcf, 0x9e, 0x4c, 0xba, 0xde, 0xaf, 0xc1, 0xad, 0xbc, 0x6c, 0xd6, 0x46, 0xc9,
	0xea, 0xa6, 0xab, 0x11, 0xbb, 0xea, 0x32, 0xf6, 0x4c, 0xa1, 0xc1, 0x06, 0xe0, 0xfd, 0x52, 0x39,
	0xdd, 0x42, 0xa5, 0x22, 0x03, 0xef, 0x67, 0x4e, 0x43, 0x9f, 0xd2, 0x10, 0x14, 0x51, 0x9d, 0x52,
	0x6a, 0x0e, 0x41, 0xed, 0xf3, 0x0e, 0xfe, 0xc9, 0x3b, 0x3c, 0xe0, 0x2d, 0x7f, 0x25, 0xec, 0x7c,
	0x0e, 0xe1, 0xf3, 0xbb, 0x4a, 0x7e, 0x03, 0xbf, 0xb0, 0xb7, 0x8e, 0x3f, 0x66, 0xa7, 0x0d, 0x29,
	0x2c, 0xc7, 0xee, 0x43, 0x91, 0xb7, 0x81, 0x85, 0xe6, 0x9c, 0x0d, 0xad, 0xac, 0xa1, 0x6b, 0x4d,
	0x67, 0x8c, 0x29, 0x67, 0x2c, 0x35, 0x1d, 0x08, 0x3a, 0x63, 0x2c, 0x80, 0x8c, 0xd4, 0x2e, 0x15,
	0x74, 0xe6, 0x0f, 0xd9, 0x68, 0x05, 0x56, 0x83, 0x2f, 0xd2, 0x0e, 0x8f, 0x14, 0xc6, 0xe5, 0x56,
	0x46, 0xe9, 0x8b, 0x11, 0xb9, 0x76, 0x0a, 0xb1, 0xc3, 0xda, 0x7d, 0x5d, 0x6e, 0x8c, 0x2e, 0x32,
	0xf2, 0xce, 0x50, 0x7f, 0x30, 0xba, 0xfc, 0xce, 0xc6, 0x34, 0xac, 0xf7, 0x1b, 0x35, 0xf3, 0x20,
	0x23, 0xe0, 0x3f, 0xbc, 0x8d, 0xb7, 0x7c, 0xca, 0xb2, 0x96, 0x35, 0x14, 0x09, 0x8d, 0x7f, 0x3c,
	0x69, 0xd7, 0xe1, 0xf0, 0x27, 0x45, 0x5f, 0x75, 0xcc, 0x25, 0x97, 0x3f, 0x12, 0xf6, 0x80, 0xda,
	0xa3, 0xe9, 0xcc, 0xd9, 0x68, 0xec, 0x06, 0x70, 0x97, 0xf6, 0xcc, 0x92, 0x03, 0xb3, 0xfd, 0xb5,
	0x38, 0xb9, 0xcb, 0x5a, 0xe0, 0x70, 0x94, 0xb4, 0x0a, 0x2a, 0x82, 0xc8, 0x45, 0xa7, 0xca, 0x9b,
	0xbf, 0x21, 0x1c, 0xbb, 0x3a, 0xe5, 0x73, 0x76, 0x49, 0x6e, 0xbd, 0x13, 0xba, 0xce, 0x4d, 0x6d,
	0x42, 0xc0, 0xa1, 0xfe, 0xf1, 0x44, 0xd2, 0xdd, 0x13, 0x29, 0x9f, 0xb2, 0xf3, 0x19, 0xf1, 0xfc,
	0xff, 0x39, 0x95, 0xaf, 0x0e, 0x6b, 0x8f, 0x65, 0x7d, 0x79, 0xf1, 0x71, 0x1c, 0x22, 0x6c, 0x61,
	0xaa, 0x2a, 0x03, 0x36, 0x2e, 0x9b, 0x4f, 0x53, 0xba, 0xe2, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd7, 0x22, 0x2c, 0xee, 0xf9, 0x03, 0x00, 0x00,
}
