// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package login is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	BindInfo
	LoginData
	LoginAuthReq
	LoginAuthRsp
	AccountSysLoginRequestData
*/
package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_SUCCESS           ErrorCode = 0
	ErrorCode_ABNORMAL          ErrorCode = 1
	ErrorCode_ERR_EXPIRE_TOKEN  ErrorCode = 101
	ErrorCode_ERR_INVALID_TOKEN ErrorCode = 102
)

var ErrorCode_name = map[int32]string{
	0:   "SUCCESS",
	1:   "ABNORMAL",
	101: "ERR_EXPIRE_TOKEN",
	102: "ERR_INVALID_TOKEN",
}
var ErrorCode_value = map[string]int32{
	"SUCCESS":           0,
	"ABNORMAL":          1,
	"ERR_EXPIRE_TOKEN":  101,
	"ERR_INVALID_TOKEN": 102,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 登录方式
type LoginType int32

const (
	LoginType_VISITOR_LOGIN LoginType = 1
	LoginType_PHONE_LOGIN   LoginType = 2
	LoginType_WECHAT_LOGIN  LoginType = 3
)

var LoginType_name = map[int32]string{
	1: "VISITOR_LOGIN",
	2: "PHONE_LOGIN",
	3: "WECHAT_LOGIN",
}
var LoginType_value = map[string]int32{
	"VISITOR_LOGIN": 1,
	"PHONE_LOGIN":   2,
	"WECHAT_LOGIN":  3,
}

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}
func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}
func (x *LoginType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LoginType_value, data, "LoginType")
	if err != nil {
		return err
	}
	*x = LoginType(value)
	return nil
}
func (LoginType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 绑定类型
type BindType int32

const (
	BindType_WECHAT BindType = 3
)

var BindType_name = map[int32]string{
	3: "WECHAT",
}
var BindType_value = map[string]int32{
	"WECHAT": 3,
}

func (x BindType) Enum() *BindType {
	p := new(BindType)
	*p = x
	return p
}
func (x BindType) String() string {
	return proto.EnumName(BindType_name, int32(x))
}
func (x *BindType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BindType_value, data, "BindType")
	if err != nil {
		return err
	}
	*x = BindType(value)
	return nil
}
func (BindType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 绑定信息根据绑定类型为不同数据结构，无绑定类型时为空数组
type BindInfo struct {
	WcAppid          *string `protobuf:"bytes,1,opt,name=wc_appid,json=wcAppid" json:"wc_appid,omitempty"`
	WcOpenid         *string `protobuf:"bytes,2,opt,name=wc_openid,json=wcOpenid" json:"wc_openid,omitempty"`
	WcUnionid        *string `protobuf:"bytes,3,opt,name=wc_unionid,json=wcUnionid" json:"wc_unionid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BindInfo) Reset()                    { *m = BindInfo{} }
func (m *BindInfo) String() string            { return proto.CompactTextString(m) }
func (*BindInfo) ProtoMessage()               {}
func (*BindInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BindInfo) GetWcAppid() string {
	if m != nil && m.WcAppid != nil {
		return *m.WcAppid
	}
	return ""
}

func (m *BindInfo) GetWcOpenid() string {
	if m != nil && m.WcOpenid != nil {
		return *m.WcOpenid
	}
	return ""
}

func (m *BindInfo) GetWcUnionid() string {
	if m != nil && m.WcUnionid != nil {
		return *m.WcUnionid
	}
	return ""
}

// 登录数据
type LoginData struct {
	Type             *LoginType `protobuf:"varint,1,opt,name=type,enum=login.LoginType" json:"type,omitempty"`
	Channel          *int32     `protobuf:"varint,2,opt,name=channel" json:"channel,omitempty"`
	Username         *string    `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	DymcCode         *string    `protobuf:"bytes,4,opt,name=dymc_code,json=dymcCode" json:"dymc_code,omitempty"`
	Password         *string    `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	ProId            *uint64    `protobuf:"varint,6,opt,name=pro_id,json=proId" json:"pro_id,omitempty"`
	CityId           *uint64    `protobuf:"varint,7,opt,name=city_id,json=cityId" json:"city_id,omitempty"`
	BindInfo         *BindInfo  `protobuf:"bytes,8,opt,name=bind_info,json=bindInfo" json:"bind_info,omitempty"`
	BindType         *BindType  `protobuf:"varint,9,opt,name=bind_type,json=bindType,enum=login.BindType" json:"bind_type,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *LoginData) Reset()                    { *m = LoginData{} }
func (m *LoginData) String() string            { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()               {}
func (*LoginData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginData) GetType() LoginType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return LoginType_VISITOR_LOGIN
}

func (m *LoginData) GetChannel() int32 {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return 0
}

func (m *LoginData) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *LoginData) GetDymcCode() string {
	if m != nil && m.DymcCode != nil {
		return *m.DymcCode
	}
	return ""
}

func (m *LoginData) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LoginData) GetProId() uint64 {
	if m != nil && m.ProId != nil {
		return *m.ProId
	}
	return 0
}

func (m *LoginData) GetCityId() uint64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

func (m *LoginData) GetBindInfo() *BindInfo {
	if m != nil {
		return m.BindInfo
	}
	return nil
}

func (m *LoginData) GetBindType() BindType {
	if m != nil && m.BindType != nil {
		return *m.BindType
	}
	return BindType_WECHAT
}

// LoginAuthReq 认证请求
type LoginAuthReq struct {
	AccountId   *uint64    `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	RequestData *LoginData `protobuf:"bytes,2,opt,name=request_data,json=requestData" json:"request_data,omitempty"`
	// ...
	PlayerId         *uint64 `protobuf:"varint,14,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Token            *string `protobuf:"bytes,15,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginAuthReq) Reset()                    { *m = LoginAuthReq{} }
func (m *LoginAuthReq) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthReq) ProtoMessage()               {}
func (*LoginAuthReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginAuthReq) GetAccountId() uint64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *LoginAuthReq) GetRequestData() *LoginData {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (m *LoginAuthReq) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *LoginAuthReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// LoginAuthRsp 认证应答
type LoginAuthRsp struct {
	ErrCode          *ErrorCode `protobuf:"varint,1,opt,name=err_code,json=errCode,enum=login.ErrorCode" json:"err_code,omitempty"`
	PlayerId         *uint64    `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Token            *string    `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *LoginAuthRsp) Reset()                    { *m = LoginAuthRsp{} }
func (m *LoginAuthRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthRsp) ProtoMessage()               {}
func (*LoginAuthRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginAuthRsp) GetErrCode() ErrorCode {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return ErrorCode_SUCCESS
}

func (m *LoginAuthRsp) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *LoginAuthRsp) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// AccountSysLoginRequestData 账号系统登录消息
type AccountSysLoginRequestData struct {
	ProductId        *uint64 `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	Data             []byte  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountSysLoginRequestData) Reset()                    { *m = AccountSysLoginRequestData{} }
func (m *AccountSysLoginRequestData) String() string            { return proto.CompactTextString(m) }
func (*AccountSysLoginRequestData) ProtoMessage()               {}
func (*AccountSysLoginRequestData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AccountSysLoginRequestData) GetProductId() uint64 {
	if m != nil && m.ProductId != nil {
		return *m.ProductId
	}
	return 0
}

func (m *AccountSysLoginRequestData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*BindInfo)(nil), "login.BindInfo")
	proto.RegisterType((*LoginData)(nil), "login.LoginData")
	proto.RegisterType((*LoginAuthReq)(nil), "login.LoginAuthReq")
	proto.RegisterType((*LoginAuthRsp)(nil), "login.LoginAuthRsp")
	proto.RegisterType((*AccountSysLoginRequestData)(nil), "login.AccountSysLoginRequestData")
	proto.RegisterEnum("login.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("login.LoginType", LoginType_name, LoginType_value)
	proto.RegisterEnum("login.BindType", BindType_name, BindType_value)
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xef, 0x4e, 0xdb, 0x3e,
	0x14, 0xfd, 0xa5, 0x7f, 0x93, 0xdb, 0xfe, 0x20, 0x58, 0x30, 0x32, 0x10, 0x12, 0xaa, 0xf6, 0x01,
	0xb1, 0x09, 0x24, 0xf6, 0x04, 0xa1, 0x44, 0xc3, 0x5a, 0xd7, 0x20, 0xb7, 0xb0, 0x69, 0x5f, 0xac,
	0x60, 0x9b, 0x11, 0xad, 0xd8, 0xc6, 0x49, 0x17, 0xf5, 0x41, 0xf6, 0x16, 0x7b, 0xc8, 0xc9, 0x4e,
	0x8a, 0xca, 0x87, 0x7d, 0xf3, 0x39, 0xe7, 0xf6, 0x9e, 0x7b, 0xcf, 0x6d, 0x60, 0xb0, 0x50, 0x3f,
	0x72, 0x79, 0xa6, 0x8d, 0x2a, 0x15, 0xea, 0x3a, 0x30, 0xca, 0xc0, 0xbf, 0xcc, 0x25, 0xc7, 0xf2,
	0x41, 0xa1, 0xb7, 0xe0, 0x57, 0x8c, 0x66, 0x5a, 0xe7, 0x3c, 0xf2, 0x8e, 0xbd, 0x93, 0x80, 0xf4,
	0x2b, 0x16, 0x5b, 0x88, 0x0e, 0x21, 0xa8, 0x18, 0x55, 0x5a, 0xc8, 0x9c, 0x47, 0x2d, 0xa7, 0xf9,
	0x15, 0x4b, 0x1d, 0x46, 0x47, 0x00, 0x15, 0xa3, 0x4b, 0x99, 0x2b, 0xab, 0xb6, 0x9d, 0x1a, 0x54,
	0xec, 0xb6, 0x26, 0x46, 0x7f, 0x5a, 0x10, 0x4c, 0xac, 0xd9, 0x55, 0x56, 0x66, 0xe8, 0x1d, 0x74,
	0xca, 0x95, 0x16, 0xce, 0x60, 0xeb, 0x22, 0x3c, 0xab, 0x67, 0x72, 0xfa, 0x7c, 0xa5, 0x05, 0x71,
	0x2a, 0x8a, 0xa0, 0xcf, 0x1e, 0x33, 0x29, 0xc5, 0xc2, 0xb9, 0x75, 0xc9, 0x1a, 0xa2, 0x03, 0xf0,
	0x97, 0x85, 0x30, 0x32, 0x7b, 0x12, 0x8d, 0xd5, 0x0b, 0xb6, 0x53, 0xf2, 0xd5, 0x13, 0xa3, 0x4c,
	0x71, 0x11, 0x75, 0x6a, 0xd1, 0x12, 0x63, 0xc5, 0x85, 0xfd, 0xa1, 0xce, 0x8a, 0xa2, 0x52, 0x86,
	0x47, 0xdd, 0x5a, 0x5b, 0x63, 0xb4, 0x07, 0x3d, 0x6d, 0x14, 0xcd, 0x79, 0xd4, 0x3b, 0xf6, 0x4e,
	0x3a, 0xa4, 0xab, 0x8d, 0xc2, 0x1c, 0xed, 0x43, 0x9f, 0xe5, 0xe5, 0xca, 0xf2, 0x7d, 0xc7, 0xf7,
	0x2c, 0xc4, 0x1c, 0x7d, 0x80, 0xe0, 0x3e, 0x97, 0x9c, 0xe6, 0xf2, 0x41, 0x45, 0xfe, 0xb1, 0x77,
	0x32, 0xb8, 0xd8, 0x6e, 0x36, 0x59, 0xa7, 0x49, 0xfc, 0xfb, 0x75, 0xae, 0xeb, 0x6a, 0xb7, 0x77,
	0xe0, 0xf6, 0xde, 0xac, 0x76, 0x6b, 0xbb, 0x6a, 0xfb, 0x1a, 0xfd, 0xf6, 0x60, 0xe8, 0xe2, 0x88,
	0x97, 0xe5, 0x23, 0x11, 0xcf, 0x36, 0xde, 0x8c, 0x31, 0xb5, 0x94, 0x25, 0x6d, 0x0e, 0xd3, 0x21,
	0x41, 0xc3, 0x60, 0x8e, 0x3e, 0xc2, 0xd0, 0x88, 0xe7, 0xa5, 0x28, 0x4a, 0xca, 0xb3, 0x32, 0x73,
	0x79, 0x0d, 0x5e, 0x07, 0x6b, 0x83, 0x27, 0x83, 0xa6, 0xca, 0x5d, 0xe1, 0x10, 0x02, 0xbd, 0xc8,
	0x56, 0xc2, 0xd8, 0x96, 0x5b, 0xae, 0xa5, 0x5f, 0x13, 0x98, 0xa3, 0x5d, 0xe8, 0x96, 0xea, 0xa7,
	0x90, 0xd1, 0xb6, 0x8b, 0xa9, 0x06, 0x23, 0xb9, 0x39, 0x56, 0xa1, 0xd1, 0x7b, 0xf0, 0x85, 0x31,
	0x75, 0xd6, 0xaf, 0x8f, 0x99, 0x18, 0xa3, 0x8c, 0xcd, 0x9c, 0xf4, 0x85, 0x71, 0x8f, 0xd7, 0x7e,
	0xad, 0x7f, 0xf9, 0xb5, 0x37, 0xfd, 0x52, 0x38, 0x88, 0xeb, 0x25, 0x67, 0xab, 0xc2, 0x39, 0x93,
	0x8d, 0x05, 0x8e, 0x00, 0xb4, 0x51, 0x7c, 0xc9, 0x36, 0x43, 0x69, 0x18, 0xcc, 0x11, 0x82, 0xce,
	0x4b, 0x18, 0x43, 0xe2, 0xde, 0xa7, 0x33, 0x08, 0x5e, 0x26, 0x43, 0x03, 0xe8, 0xcf, 0x6e, 0xc7,
	0xe3, 0x64, 0x36, 0x0b, 0xff, 0x43, 0x43, 0xf0, 0xe3, 0xcb, 0x69, 0x4a, 0xbe, 0xc4, 0x93, 0xd0,
	0x43, 0xbb, 0x10, 0x26, 0x84, 0xd0, 0xe4, 0xdb, 0x0d, 0x26, 0x09, 0x9d, 0xa7, 0x9f, 0x93, 0x69,
	0x28, 0xd0, 0x1e, 0xec, 0x58, 0x16, 0x4f, 0xef, 0xe2, 0x09, 0xbe, 0x6a, 0xe8, 0x87, 0xd3, 0xb8,
	0xf9, 0x6f, 0xdb, 0xd3, 0xa1, 0x1d, 0xf8, 0xff, 0x0e, 0xcf, 0xf0, 0x3c, 0x25, 0x74, 0x92, 0x7e,
	0xc2, 0xd3, 0xd0, 0x43, 0xdb, 0x30, 0xb8, 0xb9, 0x4e, 0xa7, 0x49, 0x43, 0xb4, 0x50, 0x08, 0xc3,
	0xaf, 0xc9, 0xf8, 0x3a, 0x9e, 0x37, 0x4c, 0xfb, 0xf4, 0x4d, 0xfd, 0x09, 0xba, 0x0e, 0x00, 0xbd,
	0x5a, 0x0d, 0xdb, 0x97, 0xfb, 0xdf, 0xf7, 0x8a, 0x52, 0xfc, 0x12, 0xe7, 0x6c, 0x91, 0x0b, 0x59,
	0x52, 0x7d, 0x7f, 0xee, 0xf2, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x91, 0xdf, 0xa1, 0xf1, 0xc8,
	0x03, 0x00, 0x00,
}
