// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mailserver.proto

package mailserver // import "steve/client_pb/mailserver"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 物品类型
type GoodsType int32

const (
	GoodsType_GOODSTYPE_PROPS GoodsType = 0
)

var GoodsType_name = map[int32]string{
	0: "GOODSTYPE_PROPS",
}
var GoodsType_value = map[string]int32{
	"GOODSTYPE_PROPS": 0,
}

func (x GoodsType) Enum() *GoodsType {
	p := new(GoodsType)
	*p = x
	return p
}
func (x GoodsType) String() string {
	return proto.EnumName(GoodsType_name, int32(x))
}
func (x *GoodsType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GoodsType_value, data, "GoodsType")
	if err != nil {
		return err
	}
	*x = GoodsType(value)
	return nil
}
func (GoodsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{0}
}

// 跳转类型
type GoType int32

const (
	GoType_GO_URL  GoType = 0
	GoType_GO_GAME GoType = 1
	GoType_GO_WND  GoType = 2
)

var GoType_name = map[int32]string{
	0: "GO_URL",
	1: "GO_GAME",
	2: "GO_WND",
}
var GoType_value = map[string]int32{
	"GO_URL":  0,
	"GO_GAME": 1,
	"GO_WND":  2,
}

func (x GoType) Enum() *GoType {
	p := new(GoType)
	*p = x
	return p
}
func (x GoType) String() string {
	return proto.EnumName(GoType_name, int32(x))
}
func (x *GoType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GoType_value, data, "GoType")
	if err != nil {
		return err
	}
	*x = GoType(value)
	return nil
}
func (GoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{1}
}

// 物品定义
type Goods struct {
	GoodsType            *GoodsType `protobuf:"varint,1,opt,name=goods_type,json=goodsType,enum=msgserver.GoodsType" json:"goods_type,omitempty"`
	GoodsId              *int32     `protobuf:"varint,2,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
	GoodsNum             *int32     `protobuf:"varint,3,opt,name=goods_num,json=goodsNum" json:"goods_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Goods) Reset()         { *m = Goods{} }
func (m *Goods) String() string { return proto.CompactTextString(m) }
func (*Goods) ProtoMessage()    {}
func (*Goods) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{0}
}
func (m *Goods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Goods.Unmarshal(m, b)
}
func (m *Goods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Goods.Marshal(b, m, deterministic)
}
func (dst *Goods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Goods.Merge(dst, src)
}
func (m *Goods) XXX_Size() int {
	return xxx_messageInfo_Goods.Size(m)
}
func (m *Goods) XXX_DiscardUnknown() {
	xxx_messageInfo_Goods.DiscardUnknown(m)
}

var xxx_messageInfo_Goods proto.InternalMessageInfo

func (m *Goods) GetGoodsType() GoodsType {
	if m != nil && m.GoodsType != nil {
		return *m.GoodsType
	}
	return GoodsType_GOODSTYPE_PROPS
}

func (m *Goods) GetGoodsId() int32 {
	if m != nil && m.GoodsId != nil {
		return *m.GoodsId
	}
	return 0
}

func (m *Goods) GetGoodsNum() int32 {
	if m != nil && m.GoodsNum != nil {
		return *m.GoodsNum
	}
	return 0
}

// msgid:MAILSVR_GET_UNREAD_SUM_REQ = 0x5001; 	// 获取未读消息总数请求
// 获取未读消息总数请求
type MailSvrGetUnReadSumReq struct {
	PlayerId             *uint64  `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrGetUnReadSumReq) Reset()         { *m = MailSvrGetUnReadSumReq{} }
func (m *MailSvrGetUnReadSumReq) String() string { return proto.CompactTextString(m) }
func (*MailSvrGetUnReadSumReq) ProtoMessage()    {}
func (*MailSvrGetUnReadSumReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{1}
}
func (m *MailSvrGetUnReadSumReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrGetUnReadSumReq.Unmarshal(m, b)
}
func (m *MailSvrGetUnReadSumReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrGetUnReadSumReq.Marshal(b, m, deterministic)
}
func (dst *MailSvrGetUnReadSumReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrGetUnReadSumReq.Merge(dst, src)
}
func (m *MailSvrGetUnReadSumReq) XXX_Size() int {
	return xxx_messageInfo_MailSvrGetUnReadSumReq.Size(m)
}
func (m *MailSvrGetUnReadSumReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrGetUnReadSumReq.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrGetUnReadSumReq proto.InternalMessageInfo

func (m *MailSvrGetUnReadSumReq) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// msgid:MAILSVR_GET_UNREAD_SUM_RSP = 0x5002; 	// 获取未读消息总数应答
// 获取未读消息总数回复
type MailSvrGetUnReadSumRsp struct {
	ErrCode              *int32   `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc              *string  `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	Sum                  *int32   `protobuf:"varint,3,opt,name=sum" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrGetUnReadSumRsp) Reset()         { *m = MailSvrGetUnReadSumRsp{} }
func (m *MailSvrGetUnReadSumRsp) String() string { return proto.CompactTextString(m) }
func (*MailSvrGetUnReadSumRsp) ProtoMessage()    {}
func (*MailSvrGetUnReadSumRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{2}
}
func (m *MailSvrGetUnReadSumRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrGetUnReadSumRsp.Unmarshal(m, b)
}
func (m *MailSvrGetUnReadSumRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrGetUnReadSumRsp.Marshal(b, m, deterministic)
}
func (dst *MailSvrGetUnReadSumRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrGetUnReadSumRsp.Merge(dst, src)
}
func (m *MailSvrGetUnReadSumRsp) XXX_Size() int {
	return xxx_messageInfo_MailSvrGetUnReadSumRsp.Size(m)
}
func (m *MailSvrGetUnReadSumRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrGetUnReadSumRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrGetUnReadSumRsp proto.InternalMessageInfo

func (m *MailSvrGetUnReadSumRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MailSvrGetUnReadSumRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *MailSvrGetUnReadSumRsp) GetSum() int32 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

// 邮件概要信息
type MailTitle struct {
	MailId               *uint64  `protobuf:"varint,1,opt,name=mail_id,json=mailId" json:"mail_id,omitempty"`
	MailTitle            *string  `protobuf:"bytes,2,opt,name=mail_title,json=mailTitle" json:"mail_title,omitempty"`
	IsHaveAttach         *int32   `protobuf:"varint,3,opt,name=is_have_attach,json=isHaveAttach" json:"is_have_attach,omitempty"`
	IsRead               *int32   `protobuf:"varint,4,opt,name=is_read,json=isRead" json:"is_read,omitempty"`
	CreateTime           *string  `protobuf:"bytes,5,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailTitle) Reset()         { *m = MailTitle{} }
func (m *MailTitle) String() string { return proto.CompactTextString(m) }
func (*MailTitle) ProtoMessage()    {}
func (*MailTitle) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{3}
}
func (m *MailTitle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailTitle.Unmarshal(m, b)
}
func (m *MailTitle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailTitle.Marshal(b, m, deterministic)
}
func (dst *MailTitle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailTitle.Merge(dst, src)
}
func (m *MailTitle) XXX_Size() int {
	return xxx_messageInfo_MailTitle.Size(m)
}
func (m *MailTitle) XXX_DiscardUnknown() {
	xxx_messageInfo_MailTitle.DiscardUnknown(m)
}

var xxx_messageInfo_MailTitle proto.InternalMessageInfo

func (m *MailTitle) GetMailId() uint64 {
	if m != nil && m.MailId != nil {
		return *m.MailId
	}
	return 0
}

func (m *MailTitle) GetMailTitle() string {
	if m != nil && m.MailTitle != nil {
		return *m.MailTitle
	}
	return ""
}

func (m *MailTitle) GetIsHaveAttach() int32 {
	if m != nil && m.IsHaveAttach != nil {
		return *m.IsHaveAttach
	}
	return 0
}

func (m *MailTitle) GetIsRead() int32 {
	if m != nil && m.IsRead != nil {
		return *m.IsRead
	}
	return 0
}

func (m *MailTitle) GetCreateTime() string {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return ""
}

// msgid:MAILSVR_GET_MAIL_LIST_REQ = 0x5003; 	// 获取邮件消息列表请求
// 获取邮件消息列表请求
type MailSvrGetMailListReq struct {
	PlayerId             *uint64  `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrGetMailListReq) Reset()         { *m = MailSvrGetMailListReq{} }
func (m *MailSvrGetMailListReq) String() string { return proto.CompactTextString(m) }
func (*MailSvrGetMailListReq) ProtoMessage()    {}
func (*MailSvrGetMailListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{4}
}
func (m *MailSvrGetMailListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrGetMailListReq.Unmarshal(m, b)
}
func (m *MailSvrGetMailListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrGetMailListReq.Marshal(b, m, deterministic)
}
func (dst *MailSvrGetMailListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrGetMailListReq.Merge(dst, src)
}
func (m *MailSvrGetMailListReq) XXX_Size() int {
	return xxx_messageInfo_MailSvrGetMailListReq.Size(m)
}
func (m *MailSvrGetMailListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrGetMailListReq.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrGetMailListReq proto.InternalMessageInfo

func (m *MailSvrGetMailListReq) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// msgid:MAILSVR_GET_MAIL_LIST_RSP = 0x5004; 	// 获取邮件消息列表应答
// 获取邮件消息列表回复
type MailSvrGetMailListRsp struct {
	ErrCode              *int32       `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc              *string      `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	MailList             []*MailTitle `protobuf:"bytes,3,rep,name=mail_list,json=mailList" json:"mail_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MailSvrGetMailListRsp) Reset()         { *m = MailSvrGetMailListRsp{} }
func (m *MailSvrGetMailListRsp) String() string { return proto.CompactTextString(m) }
func (*MailSvrGetMailListRsp) ProtoMessage()    {}
func (*MailSvrGetMailListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{5}
}
func (m *MailSvrGetMailListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrGetMailListRsp.Unmarshal(m, b)
}
func (m *MailSvrGetMailListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrGetMailListRsp.Marshal(b, m, deterministic)
}
func (dst *MailSvrGetMailListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrGetMailListRsp.Merge(dst, src)
}
func (m *MailSvrGetMailListRsp) XXX_Size() int {
	return xxx_messageInfo_MailSvrGetMailListRsp.Size(m)
}
func (m *MailSvrGetMailListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrGetMailListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrGetMailListRsp proto.InternalMessageInfo

func (m *MailSvrGetMailListRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MailSvrGetMailListRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *MailSvrGetMailListRsp) GetMailList() []*MailTitle {
	if m != nil {
		return m.MailList
	}
	return nil
}

// 邮件详情信息
type MailDetail struct {
	MailId               *uint64  `protobuf:"varint,1,opt,name=mail_id,json=mailId" json:"mail_id,omitempty"`
	MailTitle            *string  `protobuf:"bytes,2,opt,name=mail_title,json=mailTitle" json:"mail_title,omitempty"`
	IsHaveAttach         *int32   `protobuf:"varint,3,opt,name=is_have_attach,json=isHaveAttach" json:"is_have_attach,omitempty"`
	IsRead               *int32   `protobuf:"varint,4,opt,name=is_read,json=isRead" json:"is_read,omitempty"`
	CreateTime           *string  `protobuf:"bytes,5,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	Content              *string  `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	AttachGoods          *Goods   `protobuf:"bytes,7,opt,name=attach_goods,json=attachGoods" json:"attach_goods,omitempty"`
	DelTime              *string  `protobuf:"bytes,8,opt,name=del_time,json=delTime" json:"del_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailDetail) Reset()         { *m = MailDetail{} }
func (m *MailDetail) String() string { return proto.CompactTextString(m) }
func (*MailDetail) ProtoMessage()    {}
func (*MailDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{6}
}
func (m *MailDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailDetail.Unmarshal(m, b)
}
func (m *MailDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailDetail.Marshal(b, m, deterministic)
}
func (dst *MailDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailDetail.Merge(dst, src)
}
func (m *MailDetail) XXX_Size() int {
	return xxx_messageInfo_MailDetail.Size(m)
}
func (m *MailDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_MailDetail.DiscardUnknown(m)
}

var xxx_messageInfo_MailDetail proto.InternalMessageInfo

func (m *MailDetail) GetMailId() uint64 {
	if m != nil && m.MailId != nil {
		return *m.MailId
	}
	return 0
}

func (m *MailDetail) GetMailTitle() string {
	if m != nil && m.MailTitle != nil {
		return *m.MailTitle
	}
	return ""
}

func (m *MailDetail) GetIsHaveAttach() int32 {
	if m != nil && m.IsHaveAttach != nil {
		return *m.IsHaveAttach
	}
	return 0
}

func (m *MailDetail) GetIsRead() int32 {
	if m != nil && m.IsRead != nil {
		return *m.IsRead
	}
	return 0
}

func (m *MailDetail) GetCreateTime() string {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return ""
}

func (m *MailDetail) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *MailDetail) GetAttachGoods() *Goods {
	if m != nil {
		return m.AttachGoods
	}
	return nil
}

func (m *MailDetail) GetDelTime() string {
	if m != nil && m.DelTime != nil {
		return *m.DelTime
	}
	return ""
}

// msgid:MAILSVR_GET_MAIL_DETAIL_REQ = 0x5005; 	// 获取指定邮件详情请求
// 获取指定邮件详情请求
type MailSvrGetMailDetailReq struct {
	MailId               *uint64  `protobuf:"varint,1,opt,name=mail_id,json=mailId" json:"mail_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrGetMailDetailReq) Reset()         { *m = MailSvrGetMailDetailReq{} }
func (m *MailSvrGetMailDetailReq) String() string { return proto.CompactTextString(m) }
func (*MailSvrGetMailDetailReq) ProtoMessage()    {}
func (*MailSvrGetMailDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{7}
}
func (m *MailSvrGetMailDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrGetMailDetailReq.Unmarshal(m, b)
}
func (m *MailSvrGetMailDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrGetMailDetailReq.Marshal(b, m, deterministic)
}
func (dst *MailSvrGetMailDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrGetMailDetailReq.Merge(dst, src)
}
func (m *MailSvrGetMailDetailReq) XXX_Size() int {
	return xxx_messageInfo_MailSvrGetMailDetailReq.Size(m)
}
func (m *MailSvrGetMailDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrGetMailDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrGetMailDetailReq proto.InternalMessageInfo

func (m *MailSvrGetMailDetailReq) GetMailId() uint64 {
	if m != nil && m.MailId != nil {
		return *m.MailId
	}
	return 0
}

// msgid:MAILSVR_GET_MAIL_DETAIL_RSP = 0x5006; 	// 获取指定邮件详情应答
// 获取指定邮件详情回复
type MailSvrGetMailDetailRsp struct {
	ErrCode              *int32      `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc              *string     `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	Detail               *MailDetail `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MailSvrGetMailDetailRsp) Reset()         { *m = MailSvrGetMailDetailRsp{} }
func (m *MailSvrGetMailDetailRsp) String() string { return proto.CompactTextString(m) }
func (*MailSvrGetMailDetailRsp) ProtoMessage()    {}
func (*MailSvrGetMailDetailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{8}
}
func (m *MailSvrGetMailDetailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrGetMailDetailRsp.Unmarshal(m, b)
}
func (m *MailSvrGetMailDetailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrGetMailDetailRsp.Marshal(b, m, deterministic)
}
func (dst *MailSvrGetMailDetailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrGetMailDetailRsp.Merge(dst, src)
}
func (m *MailSvrGetMailDetailRsp) XXX_Size() int {
	return xxx_messageInfo_MailSvrGetMailDetailRsp.Size(m)
}
func (m *MailSvrGetMailDetailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrGetMailDetailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrGetMailDetailRsp proto.InternalMessageInfo

func (m *MailSvrGetMailDetailRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MailSvrGetMailDetailRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *MailSvrGetMailDetailRsp) GetDetail() *MailDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

// msgid:MAILSVR_SET_READ_TAG_REQ = 0x5007; 		// 标记邮件为已读请求
// 标记邮件为已读请求
type MailSvrSetReadTagReq struct {
	MailId               *uint64  `protobuf:"varint,1,opt,name=mail_id,json=mailId" json:"mail_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrSetReadTagReq) Reset()         { *m = MailSvrSetReadTagReq{} }
func (m *MailSvrSetReadTagReq) String() string { return proto.CompactTextString(m) }
func (*MailSvrSetReadTagReq) ProtoMessage()    {}
func (*MailSvrSetReadTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{9}
}
func (m *MailSvrSetReadTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrSetReadTagReq.Unmarshal(m, b)
}
func (m *MailSvrSetReadTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrSetReadTagReq.Marshal(b, m, deterministic)
}
func (dst *MailSvrSetReadTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrSetReadTagReq.Merge(dst, src)
}
func (m *MailSvrSetReadTagReq) XXX_Size() int {
	return xxx_messageInfo_MailSvrSetReadTagReq.Size(m)
}
func (m *MailSvrSetReadTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrSetReadTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrSetReadTagReq proto.InternalMessageInfo

func (m *MailSvrSetReadTagReq) GetMailId() uint64 {
	if m != nil && m.MailId != nil {
		return *m.MailId
	}
	return 0
}

// msgid:MAILSVR_SET_READ_TAG_RSP = 0x5008; 		// 标记邮件为已读应答
// 标记邮件为已读回复
type MailSvrSetReadTagRsp struct {
	ErrCode              *int32   `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc              *string  `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrSetReadTagRsp) Reset()         { *m = MailSvrSetReadTagRsp{} }
func (m *MailSvrSetReadTagRsp) String() string { return proto.CompactTextString(m) }
func (*MailSvrSetReadTagRsp) ProtoMessage()    {}
func (*MailSvrSetReadTagRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{10}
}
func (m *MailSvrSetReadTagRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrSetReadTagRsp.Unmarshal(m, b)
}
func (m *MailSvrSetReadTagRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrSetReadTagRsp.Marshal(b, m, deterministic)
}
func (dst *MailSvrSetReadTagRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrSetReadTagRsp.Merge(dst, src)
}
func (m *MailSvrSetReadTagRsp) XXX_Size() int {
	return xxx_messageInfo_MailSvrSetReadTagRsp.Size(m)
}
func (m *MailSvrSetReadTagRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrSetReadTagRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrSetReadTagRsp proto.InternalMessageInfo

func (m *MailSvrSetReadTagRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MailSvrSetReadTagRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

// msgid:MAILSVR_DEL_MAIL_REQ = 0x5009; 			// 删除邮件请求
// 删除邮件请求
type MailSvrDelMailReq struct {
	MailId               *uint64  `protobuf:"varint,1,opt,name=mail_id,json=mailId" json:"mail_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrDelMailReq) Reset()         { *m = MailSvrDelMailReq{} }
func (m *MailSvrDelMailReq) String() string { return proto.CompactTextString(m) }
func (*MailSvrDelMailReq) ProtoMessage()    {}
func (*MailSvrDelMailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{11}
}
func (m *MailSvrDelMailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrDelMailReq.Unmarshal(m, b)
}
func (m *MailSvrDelMailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrDelMailReq.Marshal(b, m, deterministic)
}
func (dst *MailSvrDelMailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrDelMailReq.Merge(dst, src)
}
func (m *MailSvrDelMailReq) XXX_Size() int {
	return xxx_messageInfo_MailSvrDelMailReq.Size(m)
}
func (m *MailSvrDelMailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrDelMailReq.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrDelMailReq proto.InternalMessageInfo

func (m *MailSvrDelMailReq) GetMailId() uint64 {
	if m != nil && m.MailId != nil {
		return *m.MailId
	}
	return 0
}

// msgid:MAILSVR_DEL_MAIL_RSP = 0x500A; 			// 删除邮件应答
// 删除邮件回复
type MailSvrDelMailRsp struct {
	ErrCode              *int32   `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc              *string  `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrDelMailRsp) Reset()         { *m = MailSvrDelMailRsp{} }
func (m *MailSvrDelMailRsp) String() string { return proto.CompactTextString(m) }
func (*MailSvrDelMailRsp) ProtoMessage()    {}
func (*MailSvrDelMailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{12}
}
func (m *MailSvrDelMailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrDelMailRsp.Unmarshal(m, b)
}
func (m *MailSvrDelMailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrDelMailRsp.Marshal(b, m, deterministic)
}
func (dst *MailSvrDelMailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrDelMailRsp.Merge(dst, src)
}
func (m *MailSvrDelMailRsp) XXX_Size() int {
	return xxx_messageInfo_MailSvrDelMailRsp.Size(m)
}
func (m *MailSvrDelMailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrDelMailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrDelMailRsp proto.InternalMessageInfo

func (m *MailSvrDelMailRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MailSvrDelMailRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

// msgid:MAILSVR_AWARD_ATTACH_REQ = 0x500B; 		// 领取附件奖励请求
// 领取附件奖励请求
type MailSvrAwardAttachReq struct {
	MailId               *uint64  `protobuf:"varint,1,opt,name=mail_id,json=mailId" json:"mail_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrAwardAttachReq) Reset()         { *m = MailSvrAwardAttachReq{} }
func (m *MailSvrAwardAttachReq) String() string { return proto.CompactTextString(m) }
func (*MailSvrAwardAttachReq) ProtoMessage()    {}
func (*MailSvrAwardAttachReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{13}
}
func (m *MailSvrAwardAttachReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrAwardAttachReq.Unmarshal(m, b)
}
func (m *MailSvrAwardAttachReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrAwardAttachReq.Marshal(b, m, deterministic)
}
func (dst *MailSvrAwardAttachReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrAwardAttachReq.Merge(dst, src)
}
func (m *MailSvrAwardAttachReq) XXX_Size() int {
	return xxx_messageInfo_MailSvrAwardAttachReq.Size(m)
}
func (m *MailSvrAwardAttachReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrAwardAttachReq.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrAwardAttachReq proto.InternalMessageInfo

func (m *MailSvrAwardAttachReq) GetMailId() uint64 {
	if m != nil && m.MailId != nil {
		return *m.MailId
	}
	return 0
}

// msgid:MAILSVR_AWARD_ATTACH_RSP = 0x500C; 		// 领取附件奖励应答
// 领取附件奖励回复
type MailSvrAwardAttachRsp struct {
	ErrCode              *int32   `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc              *string  `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	AttachGoods          *Goods   `protobuf:"bytes,3,opt,name=attach_goods,json=attachGoods" json:"attach_goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrAwardAttachRsp) Reset()         { *m = MailSvrAwardAttachRsp{} }
func (m *MailSvrAwardAttachRsp) String() string { return proto.CompactTextString(m) }
func (*MailSvrAwardAttachRsp) ProtoMessage()    {}
func (*MailSvrAwardAttachRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{14}
}
func (m *MailSvrAwardAttachRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrAwardAttachRsp.Unmarshal(m, b)
}
func (m *MailSvrAwardAttachRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrAwardAttachRsp.Marshal(b, m, deterministic)
}
func (dst *MailSvrAwardAttachRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrAwardAttachRsp.Merge(dst, src)
}
func (m *MailSvrAwardAttachRsp) XXX_Size() int {
	return xxx_messageInfo_MailSvrAwardAttachRsp.Size(m)
}
func (m *MailSvrAwardAttachRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrAwardAttachRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrAwardAttachRsp proto.InternalMessageInfo

func (m *MailSvrAwardAttachRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MailSvrAwardAttachRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *MailSvrAwardAttachRsp) GetAttachGoods() *Goods {
	if m != nil {
		return m.AttachGoods
	}
	return nil
}

// AD信息
type ADInfo struct {
	AdId                 *uint64  `protobuf:"varint,1,opt,name=ad_id,json=adId" json:"ad_id,omitempty"`
	AdTick               *int32   `protobuf:"varint,2,opt,name=ad_tick,json=adTick" json:"ad_tick,omitempty"`
	PicUrl               *string  `protobuf:"bytes,3,opt,name=pic_url,json=picUrl" json:"pic_url,omitempty"`
	GoUrl                *string  `protobuf:"bytes,4,opt,name=go_url,json=goUrl" json:"go_url,omitempty"`
	AdParam              *string  `protobuf:"bytes,5,opt,name=ad_param,json=adParam" json:"ad_param,omitempty"`
	GoType               *int32   `protobuf:"varint,6,opt,name=go_type,json=goType" json:"go_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ADInfo) Reset()         { *m = ADInfo{} }
func (m *ADInfo) String() string { return proto.CompactTextString(m) }
func (*ADInfo) ProtoMessage()    {}
func (*ADInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{15}
}
func (m *ADInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ADInfo.Unmarshal(m, b)
}
func (m *ADInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ADInfo.Marshal(b, m, deterministic)
}
func (dst *ADInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ADInfo.Merge(dst, src)
}
func (m *ADInfo) XXX_Size() int {
	return xxx_messageInfo_ADInfo.Size(m)
}
func (m *ADInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ADInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ADInfo proto.InternalMessageInfo

func (m *ADInfo) GetAdId() uint64 {
	if m != nil && m.AdId != nil {
		return *m.AdId
	}
	return 0
}

func (m *ADInfo) GetAdTick() int32 {
	if m != nil && m.AdTick != nil {
		return *m.AdTick
	}
	return 0
}

func (m *ADInfo) GetPicUrl() string {
	if m != nil && m.PicUrl != nil {
		return *m.PicUrl
	}
	return ""
}

func (m *ADInfo) GetGoUrl() string {
	if m != nil && m.GoUrl != nil {
		return *m.GoUrl
	}
	return ""
}

func (m *ADInfo) GetAdParam() string {
	if m != nil && m.AdParam != nil {
		return *m.AdParam
	}
	return ""
}

func (m *ADInfo) GetGoType() int32 {
	if m != nil && m.GoType != nil {
		return *m.GoType
	}
	return 0
}

// msgid:MAILSVR_GET_AD_REQ = 0x500D; 			// 获取广告位请求
// 获取广告位请求
type MailSvrGetADReq struct {
	PlayerId             *uint64  `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailSvrGetADReq) Reset()         { *m = MailSvrGetADReq{} }
func (m *MailSvrGetADReq) String() string { return proto.CompactTextString(m) }
func (*MailSvrGetADReq) ProtoMessage()    {}
func (*MailSvrGetADReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{16}
}
func (m *MailSvrGetADReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrGetADReq.Unmarshal(m, b)
}
func (m *MailSvrGetADReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrGetADReq.Marshal(b, m, deterministic)
}
func (dst *MailSvrGetADReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrGetADReq.Merge(dst, src)
}
func (m *MailSvrGetADReq) XXX_Size() int {
	return xxx_messageInfo_MailSvrGetADReq.Size(m)
}
func (m *MailSvrGetADReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrGetADReq.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrGetADReq proto.InternalMessageInfo

func (m *MailSvrGetADReq) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// msgid:MAILSVR_GET_AD_RSP = 0x500E; 			// 获取广告位应答
// 获取广告位回复
type MailSvrGetADRsp struct {
	ErrCode              *int32    `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc              *string   `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	AdList               []*ADInfo `protobuf:"bytes,3,rep,name=ad_list,json=adList" json:"ad_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MailSvrGetADRsp) Reset()         { *m = MailSvrGetADRsp{} }
func (m *MailSvrGetADRsp) String() string { return proto.CompactTextString(m) }
func (*MailSvrGetADRsp) ProtoMessage()    {}
func (*MailSvrGetADRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_mailserver_1699ef0d1481fc4e, []int{17}
}
func (m *MailSvrGetADRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSvrGetADRsp.Unmarshal(m, b)
}
func (m *MailSvrGetADRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSvrGetADRsp.Marshal(b, m, deterministic)
}
func (dst *MailSvrGetADRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSvrGetADRsp.Merge(dst, src)
}
func (m *MailSvrGetADRsp) XXX_Size() int {
	return xxx_messageInfo_MailSvrGetADRsp.Size(m)
}
func (m *MailSvrGetADRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSvrGetADRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MailSvrGetADRsp proto.InternalMessageInfo

func (m *MailSvrGetADRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MailSvrGetADRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *MailSvrGetADRsp) GetAdList() []*ADInfo {
	if m != nil {
		return m.AdList
	}
	return nil
}

func init() {
	proto.RegisterType((*Goods)(nil), "msgserver.Goods")
	proto.RegisterType((*MailSvrGetUnReadSumReq)(nil), "msgserver.MailSvrGetUnReadSumReq")
	proto.RegisterType((*MailSvrGetUnReadSumRsp)(nil), "msgserver.MailSvrGetUnReadSumRsp")
	proto.RegisterType((*MailTitle)(nil), "msgserver.MailTitle")
	proto.RegisterType((*MailSvrGetMailListReq)(nil), "msgserver.MailSvrGetMailListReq")
	proto.RegisterType((*MailSvrGetMailListRsp)(nil), "msgserver.MailSvrGetMailListRsp")
	proto.RegisterType((*MailDetail)(nil), "msgserver.MailDetail")
	proto.RegisterType((*MailSvrGetMailDetailReq)(nil), "msgserver.MailSvrGetMailDetailReq")
	proto.RegisterType((*MailSvrGetMailDetailRsp)(nil), "msgserver.MailSvrGetMailDetailRsp")
	proto.RegisterType((*MailSvrSetReadTagReq)(nil), "msgserver.MailSvrSetReadTagReq")
	proto.RegisterType((*MailSvrSetReadTagRsp)(nil), "msgserver.MailSvrSetReadTagRsp")
	proto.RegisterType((*MailSvrDelMailReq)(nil), "msgserver.MailSvrDelMailReq")
	proto.RegisterType((*MailSvrDelMailRsp)(nil), "msgserver.MailSvrDelMailRsp")
	proto.RegisterType((*MailSvrAwardAttachReq)(nil), "msgserver.MailSvrAwardAttachReq")
	proto.RegisterType((*MailSvrAwardAttachRsp)(nil), "msgserver.MailSvrAwardAttachRsp")
	proto.RegisterType((*ADInfo)(nil), "msgserver.ADInfo")
	proto.RegisterType((*MailSvrGetADReq)(nil), "msgserver.MailSvrGetADReq")
	proto.RegisterType((*MailSvrGetADRsp)(nil), "msgserver.MailSvrGetADRsp")
	proto.RegisterEnum("msgserver.GoodsType", GoodsType_name, GoodsType_value)
	proto.RegisterEnum("msgserver.GoType", GoType_name, GoType_value)
}

func init() { proto.RegisterFile("mailserver.proto", fileDescriptor_mailserver_1699ef0d1481fc4e) }

var fileDescriptor_mailserver_1699ef0d1481fc4e = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x5d, 0x4f, 0xdb, 0x3c,
	0x14, 0x26, 0xb4, 0x4d, 0xdb, 0x53, 0x04, 0x25, 0xc0, 0x4b, 0x78, 0x3f, 0xf4, 0x56, 0xd1, 0x2e,
	0x2a, 0x34, 0xca, 0x56, 0xb6, 0x1f, 0xd0, 0xad, 0xa8, 0xab, 0x04, 0xb4, 0x4a, 0x8b, 0xa6, 0xed,
	0xc6, 0xf3, 0xe2, 0xb3, 0x60, 0x91, 0x34, 0x59, 0xe2, 0x76, 0xe2, 0x66, 0x9a, 0xf6, 0x03, 0xf6,
	0x03, 0x76, 0xbb, 0x3f, 0x3a, 0xd9, 0x0e, 0x2d, 0x74, 0x05, 0xa6, 0x5e, 0xed, 0xce, 0x3e, 0x5f,
	0xcf, 0xe3, 0xe7, 0x1c, 0xdb, 0x50, 0x0d, 0x29, 0x0f, 0x52, 0x4c, 0x26, 0x98, 0x34, 0xe2, 0x24,
	0x12, 0x91, 0x55, 0x0e, 0x53, 0x5f, 0x1b, 0x1c, 0x01, 0x85, 0x4e, 0x14, 0xb1, 0xd4, 0x3a, 0x02,
	0xf0, 0xe5, 0x82, 0x88, 0xab, 0x18, 0x6d, 0xa3, 0x66, 0xd4, 0xd7, 0x9b, 0xdb, 0x8d, 0x69, 0x60,
	0x43, 0x45, 0x0d, 0xaf, 0x62, 0x74, 0xcb, 0xfe, 0xf5, 0xd2, 0xda, 0x83, 0x92, 0x4e, 0xe2, 0xcc,
	0x5e, 0xad, 0x19, 0xf5, 0x82, 0x5b, 0x54, 0xfb, 0x2e, 0xb3, 0xfe, 0x01, 0x1d, 0x47, 0x46, 0xe3,
	0xd0, 0xce, 0x29, 0x9f, 0x8e, 0x3d, 0x1b, 0x87, 0xce, 0x73, 0xf8, 0xeb, 0x94, 0xf2, 0x60, 0x30,
	0x49, 0x3a, 0x28, 0xce, 0x47, 0x2e, 0x52, 0x36, 0x18, 0x87, 0x2e, 0x7e, 0x94, 0x69, 0x71, 0x40,
	0xaf, 0x30, 0x91, 0x25, 0x25, 0x8b, 0xbc, 0x5b, 0xd2, 0x86, 0x2e, 0x73, 0xde, 0x2d, 0x4e, 0x4b,
	0x63, 0x49, 0x04, 0x93, 0x84, 0x78, 0x11, 0xd3, 0xdc, 0x0b, 0x6e, 0x11, 0x93, 0xe4, 0x65, 0xc4,
	0xf0, 0xda, 0xc5, 0x30, 0xf5, 0x14, 0xc7, 0xb2, 0x72, 0xb5, 0x31, 0xf5, 0xac, 0x2a, 0xe4, 0xd2,
	0x29, 0x3b, 0xb9, 0x74, 0x7e, 0x18, 0x50, 0x96, 0x10, 0x43, 0x2e, 0x02, 0xb4, 0x76, 0xa1, 0x28,
	0xb5, 0x9b, 0x51, 0x31, 0xe5, 0xb6, 0xcb, 0xac, 0xff, 0x00, 0x94, 0x43, 0xc8, 0xb0, 0xac, 0x6a,
	0x39, 0x9c, 0xe6, 0x3d, 0x82, 0x75, 0x9e, 0x92, 0x0b, 0x3a, 0x41, 0x42, 0x85, 0xa0, 0xde, 0x45,
	0x06, 0xb1, 0xc6, 0xd3, 0x57, 0x74, 0x82, 0x2d, 0x65, 0x93, 0xd5, 0x79, 0x4a, 0x12, 0xa4, 0xcc,
	0xce, 0x2b, 0xb7, 0xc9, 0x53, 0x79, 0x24, 0xeb, 0x7f, 0xa8, 0x78, 0x09, 0x52, 0x81, 0x44, 0xf0,
	0x10, 0xed, 0x82, 0x2a, 0x0f, 0xda, 0x34, 0xe4, 0x21, 0x3a, 0xcf, 0x60, 0x67, 0xa6, 0x83, 0x5c,
	0x9d, 0xf0, 0x54, 0x3c, 0xa8, 0xde, 0x17, 0x63, 0x61, 0xda, 0xd2, 0xea, 0x3d, 0x05, 0x75, 0x64,
	0x12, 0xf0, 0x54, 0xd8, 0xb9, 0x5a, 0xae, 0x5e, 0xb9, 0x35, 0x30, 0x53, 0x19, 0xdd, 0x52, 0x98,
	0x61, 0x39, 0xdf, 0x56, 0x01, 0xa4, 0xbd, 0x8d, 0x82, 0xf2, 0xe0, 0x4f, 0xd5, 0xd7, 0xb2, 0xa1,
	0xe8, 0x45, 0x23, 0x81, 0x23, 0x61, 0x9b, 0xfa, 0xcc, 0xd9, 0xd6, 0x3a, 0x82, 0x35, 0x8d, 0x48,
	0xd4, 0x2c, 0xdb, 0xc5, 0x9a, 0x51, 0xaf, 0x34, 0xab, 0xf3, 0xf7, 0xc4, 0xad, 0xe8, 0x28, 0x7d,
	0xb5, 0xf6, 0xa0, 0xc4, 0x30, 0xd0, 0x60, 0x25, 0x5d, 0x8f, 0x61, 0xa0, 0x3a, 0xd9, 0x84, 0xdd,
	0xdb, 0x2d, 0xd1, 0xca, 0xc8, 0x5e, 0xde, 0x25, 0x8e, 0xf3, 0xf9, 0x8e, 0x9c, 0xa5, 0x1b, 0x79,
	0x00, 0x26, 0x53, 0x25, 0x94, 0x8c, 0x95, 0xe6, 0xce, 0x5c, 0x17, 0xb3, 0xfa, 0x59, 0x90, 0x73,
	0x08, 0xdb, 0x19, 0xfe, 0x00, 0x85, 0x14, 0x74, 0x48, 0xfd, 0x7b, 0x09, 0x9f, 0x2c, 0x4a, 0x58,
	0x96, 0xad, 0xf3, 0x18, 0x36, 0xb3, 0x6a, 0x6d, 0x0c, 0x4e, 0x1f, 0x12, 0xab, 0xfb, 0x4b, 0xf4,
	0xd2, 0xc0, 0x4f, 0xa6, 0xd7, 0xa7, 0xf5, 0x89, 0x26, 0x4c, 0x4f, 0xd9, 0xbd, 0xe0, 0x5f, 0x8d,
	0x85, 0x29, 0x4b, 0x37, 0x6a, 0x7e, 0xfa, 0x72, 0xbf, 0x31, 0x7d, 0xce, 0x77, 0x03, 0xcc, 0x56,
	0xbb, 0x3b, 0xfa, 0x10, 0x59, 0x5b, 0x50, 0xa0, 0x6c, 0x46, 0x33, 0x4f, 0x59, 0x97, 0x49, 0xf6,
	0x94, 0x11, 0xc1, 0xbd, 0xcb, 0xec, 0x09, 0x37, 0x29, 0x1b, 0x72, 0xef, 0x52, 0x3a, 0x62, 0xee,
	0x91, 0x71, 0xa2, 0xe7, 0xa2, 0xec, 0x9a, 0x31, 0xf7, 0xce, 0x93, 0xc0, 0xda, 0x01, 0xd3, 0x8f,
	0x94, 0x3d, 0xaf, 0xec, 0x05, 0x3f, 0x92, 0xe6, 0x3d, 0x28, 0x51, 0x46, 0x62, 0x9a, 0xd0, 0x30,
	0xbb, 0x53, 0x45, 0xca, 0xfa, 0x72, 0x2b, 0x4b, 0xf9, 0x91, 0xfe, 0x59, 0x4c, 0x8d, 0xe1, 0x47,
	0xf2, 0x03, 0x71, 0x1a, 0xb0, 0x31, 0x9b, 0xe5, 0x56, 0xfb, 0xc1, 0x37, 0x2c, 0x9d, 0x8b, 0x5f,
	0x5a, 0xca, 0x7d, 0x75, 0xea, 0x1b, 0x4f, 0xd7, 0xe6, 0x0d, 0x15, 0xb5, 0x5c, 0x52, 0x08, 0xf9,
	0x6a, 0xed, 0xd7, 0xa0, 0x3c, 0xfd, 0xfd, 0xac, 0x2d, 0xd8, 0xe8, 0xf4, 0x7a, 0xed, 0xc1, 0xf0,
	0x4d, 0xff, 0x98, 0xf4, 0xdd, 0x5e, 0x7f, 0x50, 0x5d, 0xd9, 0x3f, 0x00, 0xb3, 0xa3, 0x0e, 0x64,
	0x01, 0x98, 0x9d, 0x1e, 0x39, 0x77, 0x4f, 0xaa, 0x2b, 0x56, 0x05, 0x8a, 0x9d, 0x1e, 0xe9, 0xb4,
	0x4e, 0x8f, 0xab, 0x46, 0xe6, 0x78, 0x7d, 0xd6, 0xae, 0xae, 0xbe, 0xf8, 0xf7, 0xed, 0xdf, 0xa9,
	0xc0, 0x09, 0x1e, 0x7a, 0x01, 0xc7, 0x91, 0x20, 0xf1, 0xfb, 0xc3, 0xd9, 0x1f, 0xfd, 0x33, 0x00,
	0x00, 0xff, 0xff, 0xd3, 0x84, 0xaf, 0x22, 0xb0, 0x07, 0x00, 0x00,
}
