// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_common.proto

package room

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "steve/client_pb/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Card 卡牌
type Card struct {
	Color            *CardColor `protobuf:"varint,1,opt,name=color,enum=room.CardColor" json:"color,omitempty"`
	Point            *int32     `protobuf:"varint,2,opt,name=point" json:"point,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Card) GetColor() CardColor {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return CardColor_CC_WAN
}

func (m *Card) GetPoint() int32 {
	if m != nil && m.Point != nil {
		return *m.Point
	}
	return 0
}

// Fan 番型
type Fan struct {
	Name             *FanType `protobuf:"varint,1,opt,name=name,enum=room.FanType" json:"name,omitempty"`
	Value            *int32   `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Type             *uint32  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Fan) Reset()                    { *m = Fan{} }
func (m *Fan) String() string            { return proto.CompactTextString(m) }
func (*Fan) ProtoMessage()               {}
func (*Fan) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *Fan) GetName() FanType {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return FanType_FT_PINGHU
}

func (m *Fan) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *Fan) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// RoomStartGameNtf 游戏开始通知。
type RoomStartGameNtf struct {
	// TODO
	Reserve          *uint32 `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	NeedHsz          *bool   `protobuf:"varint,2,opt,name=need_hsz,json=needHsz" json:"need_hsz,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomStartGameNtf) Reset()                    { *m = RoomStartGameNtf{} }
func (m *RoomStartGameNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomStartGameNtf) ProtoMessage()               {}
func (*RoomStartGameNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *RoomStartGameNtf) GetReserve() uint32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

func (m *RoomStartGameNtf) GetNeedHsz() bool {
	if m != nil && m.NeedHsz != nil {
		return *m.NeedHsz
	}
	return false
}

// RoomXipaiNtf 洗牌通知
type RoomXipaiNtf struct {
	Dices            []uint32 `protobuf:"varint,1,rep,name=dices" json:"dices,omitempty"`
	TotalCard        *uint32  `protobuf:"varint,2,opt,name=total_card,json=totalCard" json:"total_card,omitempty"`
	BankerSeat       *uint32  `protobuf:"varint,3,opt,name=banker_seat,json=bankerSeat" json:"banker_seat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RoomXipaiNtf) Reset()                    { *m = RoomXipaiNtf{} }
func (m *RoomXipaiNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomXipaiNtf) ProtoMessage()               {}
func (*RoomXipaiNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *RoomXipaiNtf) GetDices() []uint32 {
	if m != nil {
		return m.Dices
	}
	return nil
}

func (m *RoomXipaiNtf) GetTotalCard() uint32 {
	if m != nil && m.TotalCard != nil {
		return *m.TotalCard
	}
	return 0
}

func (m *RoomXipaiNtf) GetBankerSeat() uint32 {
	if m != nil && m.BankerSeat != nil {
		return *m.BankerSeat
	}
	return 0
}

// PlayerCardCount 玩家手牌数量
type PlayerCardCount struct {
	PlayerId         *uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	CardCount        *uint32 `protobuf:"varint,2,opt,name=card_count,json=cardCount" json:"card_count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerCardCount) Reset()                    { *m = PlayerCardCount{} }
func (m *PlayerCardCount) String() string            { return proto.CompactTextString(m) }
func (*PlayerCardCount) ProtoMessage()               {}
func (*PlayerCardCount) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *PlayerCardCount) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *PlayerCardCount) GetCardCount() uint32 {
	if m != nil && m.CardCount != nil {
		return *m.CardCount
	}
	return 0
}

// RoomFapaiNtf 发牌通知
type RoomFapaiNtf struct {
	Cards            []uint32           `protobuf:"varint,1,rep,name=cards" json:"cards,omitempty"`
	PlayerCardCounts []*PlayerCardCount `protobuf:"bytes,2,rep,name=player_card_counts,json=playerCardCounts" json:"player_card_counts,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *RoomFapaiNtf) Reset()                    { *m = RoomFapaiNtf{} }
func (m *RoomFapaiNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomFapaiNtf) ProtoMessage()               {}
func (*RoomFapaiNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *RoomFapaiNtf) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *RoomFapaiNtf) GetPlayerCardCounts() []*PlayerCardCount {
	if m != nil {
		return m.PlayerCardCounts
	}
	return nil
}

// RoomHuansanzhangNtf 换三张通知
type RoomHuansanzhangNtf struct {
	HszCard          []*Card `protobuf:"bytes,1,rep,name=hsz_card,json=hszCard" json:"hsz_card,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomHuansanzhangNtf) Reset()                    { *m = RoomHuansanzhangNtf{} }
func (m *RoomHuansanzhangNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomHuansanzhangNtf) ProtoMessage()               {}
func (*RoomHuansanzhangNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *RoomHuansanzhangNtf) GetHszCard() []*Card {
	if m != nil {
		return m.HszCard
	}
	return nil
}

// RoomHuansanzhangReq 换三张请求
type RoomHuansanzhangReq struct {
	Cards            []uint32 `protobuf:"varint,1,rep,name=cards" json:"cards,omitempty"`
	Sure             *bool    `protobuf:"varint,2,opt,name=sure" json:"sure,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RoomHuansanzhangReq) Reset()                    { *m = RoomHuansanzhangReq{} }
func (m *RoomHuansanzhangReq) String() string            { return proto.CompactTextString(m) }
func (*RoomHuansanzhangReq) ProtoMessage()               {}
func (*RoomHuansanzhangReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *RoomHuansanzhangReq) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *RoomHuansanzhangReq) GetSure() bool {
	if m != nil && m.Sure != nil {
		return *m.Sure
	}
	return false
}

// RoomHuansanzhangRsp 换三张应答
type RoomHuansanzhangRsp struct {
	ErrCode          *RoomError `protobuf:"varint,1,opt,name=err_code,json=errCode,enum=room.RoomError" json:"err_code,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RoomHuansanzhangRsp) Reset()                    { *m = RoomHuansanzhangRsp{} }
func (m *RoomHuansanzhangRsp) String() string            { return proto.CompactTextString(m) }
func (*RoomHuansanzhangRsp) ProtoMessage()               {}
func (*RoomHuansanzhangRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *RoomHuansanzhangRsp) GetErrCode() RoomError {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return RoomError_SUCCESS
}

// RoomHuansanzhangFinishNtf 换三张完成通知
type RoomHuansanzhangFinishNtf struct {
	InCards          []uint32   `protobuf:"varint,1,rep,name=in_cards,json=inCards" json:"in_cards,omitempty"`
	OutCards         []uint32   `protobuf:"varint,2,rep,name=out_cards,json=outCards" json:"out_cards,omitempty"`
	Direction        *Direction `protobuf:"varint,3,opt,name=direction,enum=room.Direction" json:"direction,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RoomHuansanzhangFinishNtf) Reset()                    { *m = RoomHuansanzhangFinishNtf{} }
func (m *RoomHuansanzhangFinishNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomHuansanzhangFinishNtf) ProtoMessage()               {}
func (*RoomHuansanzhangFinishNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *RoomHuansanzhangFinishNtf) GetInCards() []uint32 {
	if m != nil {
		return m.InCards
	}
	return nil
}

func (m *RoomHuansanzhangFinishNtf) GetOutCards() []uint32 {
	if m != nil {
		return m.OutCards
	}
	return nil
}

func (m *RoomHuansanzhangFinishNtf) GetDirection() Direction {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return Direction_ClockWise
}

// RoomDingqueNtf 定缺通知
type RoomDingqueNtf struct {
	Color            *CardColor `protobuf:"varint,1,opt,name=color,enum=room.CardColor" json:"color,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RoomDingqueNtf) Reset()                    { *m = RoomDingqueNtf{} }
func (m *RoomDingqueNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomDingqueNtf) ProtoMessage()               {}
func (*RoomDingqueNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *RoomDingqueNtf) GetColor() CardColor {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return CardColor_CC_WAN
}

// RoomDingqueReq 定缺请求
type RoomDingqueReq struct {
	Color            *CardColor `protobuf:"varint,1,opt,name=color,enum=room.CardColor" json:"color,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RoomDingqueReq) Reset()                    { *m = RoomDingqueReq{} }
func (m *RoomDingqueReq) String() string            { return proto.CompactTextString(m) }
func (*RoomDingqueReq) ProtoMessage()               {}
func (*RoomDingqueReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *RoomDingqueReq) GetColor() CardColor {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return CardColor_CC_WAN
}

// RoomDingqueRsp 定缺响应
type RoomDingqueRsp struct {
	ErrCode          *RoomError `protobuf:"varint,1,opt,name=err_code,json=errCode,enum=room.RoomError" json:"err_code,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RoomDingqueRsp) Reset()                    { *m = RoomDingqueRsp{} }
func (m *RoomDingqueRsp) String() string            { return proto.CompactTextString(m) }
func (*RoomDingqueRsp) ProtoMessage()               {}
func (*RoomDingqueRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

func (m *RoomDingqueRsp) GetErrCode() RoomError {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return RoomError_SUCCESS
}

// PlayerDingqueColor 玩家定缺花色
type PlayerDingqueColor struct {
	PlayerId         *uint64    `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Color            *CardColor `protobuf:"varint,2,opt,name=color,enum=room.CardColor" json:"color,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PlayerDingqueColor) Reset()                    { *m = PlayerDingqueColor{} }
func (m *PlayerDingqueColor) String() string            { return proto.CompactTextString(m) }
func (*PlayerDingqueColor) ProtoMessage()               {}
func (*PlayerDingqueColor) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

func (m *PlayerDingqueColor) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *PlayerDingqueColor) GetColor() CardColor {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return CardColor_CC_WAN
}

// RoomDingqueFinishNtf 定缺完成通知
type RoomDingqueFinishNtf struct {
	PlayerDingqueColor []*PlayerDingqueColor `protobuf:"bytes,1,rep,name=player_dingque_color,json=playerDingqueColor" json:"player_dingque_color,omitempty"`
	XXX_unrecognized   []byte                `json:"-"`
}

func (m *RoomDingqueFinishNtf) Reset()                    { *m = RoomDingqueFinishNtf{} }
func (m *RoomDingqueFinishNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomDingqueFinishNtf) ProtoMessage()               {}
func (*RoomDingqueFinishNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

func (m *RoomDingqueFinishNtf) GetPlayerDingqueColor() []*PlayerDingqueColor {
	if m != nil {
		return m.PlayerDingqueColor
	}
	return nil
}

// RoomChiInfo 吃牌信息
type RoomChiInfo struct {
	Cards            []uint32 `protobuf:"varint,1,rep,name=cards" json:"cards,omitempty"`
	ChiCard          *uint32  `protobuf:"varint,2,opt,name=chi_card,json=chiCard" json:"chi_card,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RoomChiInfo) Reset()                    { *m = RoomChiInfo{} }
func (m *RoomChiInfo) String() string            { return proto.CompactTextString(m) }
func (*RoomChiInfo) ProtoMessage()               {}
func (*RoomChiInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{15} }

func (m *RoomChiInfo) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *RoomChiInfo) GetChiCard() uint32 {
	if m != nil && m.ChiCard != nil {
		return *m.ChiCard
	}
	return 0
}

// RoomChupaiWenxunNtf 出牌问询通知
type RoomChupaiWenxunNtf struct {
	Card             *uint32      `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
	EnablePeng       *bool        `protobuf:"varint,2,opt,name=enable_peng,json=enablePeng" json:"enable_peng,omitempty"`
	EnableMinggang   *bool        `protobuf:"varint,3,opt,name=enable_minggang,json=enableMinggang" json:"enable_minggang,omitempty"`
	EnableDianpao    *bool        `protobuf:"varint,4,opt,name=enable_dianpao,json=enableDianpao" json:"enable_dianpao,omitempty"`
	EnableQi         *bool        `protobuf:"varint,5,opt,name=enable_qi,json=enableQi" json:"enable_qi,omitempty"`
	ChiInfo          *RoomChiInfo `protobuf:"bytes,6,opt,name=chi_info,json=chiInfo" json:"chi_info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RoomChupaiWenxunNtf) Reset()                    { *m = RoomChupaiWenxunNtf{} }
func (m *RoomChupaiWenxunNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomChupaiWenxunNtf) ProtoMessage()               {}
func (*RoomChupaiWenxunNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{16} }

func (m *RoomChupaiWenxunNtf) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *RoomChupaiWenxunNtf) GetEnablePeng() bool {
	if m != nil && m.EnablePeng != nil {
		return *m.EnablePeng
	}
	return false
}

func (m *RoomChupaiWenxunNtf) GetEnableMinggang() bool {
	if m != nil && m.EnableMinggang != nil {
		return *m.EnableMinggang
	}
	return false
}

func (m *RoomChupaiWenxunNtf) GetEnableDianpao() bool {
	if m != nil && m.EnableDianpao != nil {
		return *m.EnableDianpao
	}
	return false
}

func (m *RoomChupaiWenxunNtf) GetEnableQi() bool {
	if m != nil && m.EnableQi != nil {
		return *m.EnableQi
	}
	return false
}

func (m *RoomChupaiWenxunNtf) GetChiInfo() *RoomChiInfo {
	if m != nil {
		return m.ChiInfo
	}
	return nil
}

// RoomXingpaiActionReq 执行行牌动作请求
type RoomXingpaiActionReq struct {
	ActionId         *XingpaiAction `protobuf:"varint,1,opt,name=action_id,json=actionId,enum=room.XingpaiAction" json:"action_id,omitempty"`
	GangCard         *uint32        `protobuf:"varint,2,opt,name=gang_card,json=gangCard" json:"gang_card,omitempty"`
	GangType         *GangType      `protobuf:"varint,3,opt,name=gang_type,json=gangType,enum=room.GangType" json:"gang_type,omitempty"`
	ChiCards         []uint32       `protobuf:"varint,4,rep,name=chi_cards,json=chiCards" json:"chi_cards,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RoomXingpaiActionReq) Reset()                    { *m = RoomXingpaiActionReq{} }
func (m *RoomXingpaiActionReq) String() string            { return proto.CompactTextString(m) }
func (*RoomXingpaiActionReq) ProtoMessage()               {}
func (*RoomXingpaiActionReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{17} }

func (m *RoomXingpaiActionReq) GetActionId() XingpaiAction {
	if m != nil && m.ActionId != nil {
		return *m.ActionId
	}
	return XingpaiAction_XA_CHI
}

func (m *RoomXingpaiActionReq) GetGangCard() uint32 {
	if m != nil && m.GangCard != nil {
		return *m.GangCard
	}
	return 0
}

func (m *RoomXingpaiActionReq) GetGangType() GangType {
	if m != nil && m.GangType != nil {
		return *m.GangType
	}
	return GangType_MingGang
}

func (m *RoomXingpaiActionReq) GetChiCards() []uint32 {
	if m != nil {
		return m.ChiCards
	}
	return nil
}

// RoomChiNtf 吃牌通知
type RoomChiNtf struct {
	ToPlayerId       *uint64  `protobuf:"varint,1,opt,name=to_player_id,json=toPlayerId" json:"to_player_id,omitempty"`
	FromPlayerId     *uint64  `protobuf:"varint,2,opt,name=from_player_id,json=fromPlayerId" json:"from_player_id,omitempty"`
	Cards            []uint32 `protobuf:"varint,3,rep,name=cards" json:"cards,omitempty"`
	ChiCard          *uint32  `protobuf:"varint,4,opt,name=chi_card,json=chiCard" json:"chi_card,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RoomChiNtf) Reset()                    { *m = RoomChiNtf{} }
func (m *RoomChiNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomChiNtf) ProtoMessage()               {}
func (*RoomChiNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{18} }

func (m *RoomChiNtf) GetToPlayerId() uint64 {
	if m != nil && m.ToPlayerId != nil {
		return *m.ToPlayerId
	}
	return 0
}

func (m *RoomChiNtf) GetFromPlayerId() uint64 {
	if m != nil && m.FromPlayerId != nil {
		return *m.FromPlayerId
	}
	return 0
}

func (m *RoomChiNtf) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *RoomChiNtf) GetChiCard() uint32 {
	if m != nil && m.ChiCard != nil {
		return *m.ChiCard
	}
	return 0
}

// RoomPengNtf 玩家碰通知
type RoomPengNtf struct {
	ToPlayerId       *uint64 `protobuf:"varint,1,opt,name=to_player_id,json=toPlayerId" json:"to_player_id,omitempty"`
	FromPlayerId     *uint64 `protobuf:"varint,2,opt,name=from_player_id,json=fromPlayerId" json:"from_player_id,omitempty"`
	Card             *uint32 `protobuf:"varint,3,opt,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomPengNtf) Reset()                    { *m = RoomPengNtf{} }
func (m *RoomPengNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomPengNtf) ProtoMessage()               {}
func (*RoomPengNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{19} }

func (m *RoomPengNtf) GetToPlayerId() uint64 {
	if m != nil && m.ToPlayerId != nil {
		return *m.ToPlayerId
	}
	return 0
}

func (m *RoomPengNtf) GetFromPlayerId() uint64 {
	if m != nil && m.FromPlayerId != nil {
		return *m.FromPlayerId
	}
	return 0
}

func (m *RoomPengNtf) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

// RoomGangNtf 杠通知
type RoomGangNtf struct {
	ToPlayerId       *uint64   `protobuf:"varint,1,opt,name=to_player_id,json=toPlayerId" json:"to_player_id,omitempty"`
	FromPlayerId     *uint64   `protobuf:"varint,2,opt,name=from_player_id,json=fromPlayerId" json:"from_player_id,omitempty"`
	Card             *uint32   `protobuf:"varint,3,opt,name=card" json:"card,omitempty"`
	GangType         *GangType `protobuf:"varint,4,opt,name=gang_type,json=gangType,enum=room.GangType" json:"gang_type,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *RoomGangNtf) Reset()                    { *m = RoomGangNtf{} }
func (m *RoomGangNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomGangNtf) ProtoMessage()               {}
func (*RoomGangNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{20} }

func (m *RoomGangNtf) GetToPlayerId() uint64 {
	if m != nil && m.ToPlayerId != nil {
		return *m.ToPlayerId
	}
	return 0
}

func (m *RoomGangNtf) GetFromPlayerId() uint64 {
	if m != nil && m.FromPlayerId != nil {
		return *m.FromPlayerId
	}
	return 0
}

func (m *RoomGangNtf) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *RoomGangNtf) GetGangType() GangType {
	if m != nil && m.GangType != nil {
		return *m.GangType
	}
	return GangType_MingGang
}

// TingCardInfo 听牌信息
type TingCardInfo struct {
	TingCard         *uint32 `protobuf:"varint,1,opt,name=ting_card,json=tingCard" json:"ting_card,omitempty"`
	Times            *uint32 `protobuf:"varint,2,opt,name=times" json:"times,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TingCardInfo) Reset()                    { *m = TingCardInfo{} }
func (m *TingCardInfo) String() string            { return proto.CompactTextString(m) }
func (*TingCardInfo) ProtoMessage()               {}
func (*TingCardInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{21} }

func (m *TingCardInfo) GetTingCard() uint32 {
	if m != nil && m.TingCard != nil {
		return *m.TingCard
	}
	return 0
}

func (m *TingCardInfo) GetTimes() uint32 {
	if m != nil && m.Times != nil {
		return *m.Times
	}
	return 0
}

// CanTingCardInfo 出本张牌可以听
type CanTingCardInfo struct {
	OutCard          *uint32         `protobuf:"varint,1,opt,name=out_card,json=outCard" json:"out_card,omitempty"`
	TingCardInfo     []*TingCardInfo `protobuf:"bytes,2,rep,name=ting_card_info,json=tingCardInfo" json:"ting_card_info,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *CanTingCardInfo) Reset()                    { *m = CanTingCardInfo{} }
func (m *CanTingCardInfo) String() string            { return proto.CompactTextString(m) }
func (*CanTingCardInfo) ProtoMessage()               {}
func (*CanTingCardInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{22} }

func (m *CanTingCardInfo) GetOutCard() uint32 {
	if m != nil && m.OutCard != nil {
		return *m.OutCard
	}
	return 0
}

func (m *CanTingCardInfo) GetTingCardInfo() []*TingCardInfo {
	if m != nil {
		return m.TingCardInfo
	}
	return nil
}

// RoomZixunNtf 自询通知
type RoomZixunNtf struct {
	EnableAngangCards []uint32           `protobuf:"varint,1,rep,name=enable_angang_cards,json=enableAngangCards" json:"enable_angang_cards,omitempty"`
	EnableBugangCards []uint32           `protobuf:"varint,2,rep,name=enable_bugang_cards,json=enableBugangCards" json:"enable_bugang_cards,omitempty"`
	EnableZimo        *bool              `protobuf:"varint,3,opt,name=enable_zimo,json=enableZimo" json:"enable_zimo,omitempty"`
	EnableChupaiCards []uint32           `protobuf:"varint,4,rep,name=enable_chupai_cards,json=enableChupaiCards" json:"enable_chupai_cards,omitempty"`
	CanTingCardInfo   []*CanTingCardInfo `protobuf:"bytes,5,rep,name=can_ting_card_info,json=canTingCardInfo" json:"can_ting_card_info,omitempty"`
	EnableQi          *bool              `protobuf:"varint,6,opt,name=enable_qi,json=enableQi" json:"enable_qi,omitempty"`
	HuType            *HuType            `protobuf:"varint,7,opt,name=hu_type,json=huType,enum=room.HuType" json:"hu_type,omitempty"`
	EnableTing        *bool              `protobuf:"varint,8,opt,name=enable_ting,json=enableTing" json:"enable_ting,omitempty"`
	TingType          *TingType          `protobuf:"varint,9,opt,name=ting_type,json=tingType,enum=room.TingType" json:"ting_type,omitempty"`
	XXX_unrecognized  []byte             `json:"-"`
}

func (m *RoomZixunNtf) Reset()                    { *m = RoomZixunNtf{} }
func (m *RoomZixunNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomZixunNtf) ProtoMessage()               {}
func (*RoomZixunNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{23} }

func (m *RoomZixunNtf) GetEnableAngangCards() []uint32 {
	if m != nil {
		return m.EnableAngangCards
	}
	return nil
}

func (m *RoomZixunNtf) GetEnableBugangCards() []uint32 {
	if m != nil {
		return m.EnableBugangCards
	}
	return nil
}

func (m *RoomZixunNtf) GetEnableZimo() bool {
	if m != nil && m.EnableZimo != nil {
		return *m.EnableZimo
	}
	return false
}

func (m *RoomZixunNtf) GetEnableChupaiCards() []uint32 {
	if m != nil {
		return m.EnableChupaiCards
	}
	return nil
}

func (m *RoomZixunNtf) GetCanTingCardInfo() []*CanTingCardInfo {
	if m != nil {
		return m.CanTingCardInfo
	}
	return nil
}

func (m *RoomZixunNtf) GetEnableQi() bool {
	if m != nil && m.EnableQi != nil {
		return *m.EnableQi
	}
	return false
}

func (m *RoomZixunNtf) GetHuType() HuType {
	if m != nil && m.HuType != nil {
		return *m.HuType
	}
	return HuType_HT_GANGHOUPAO
}

func (m *RoomZixunNtf) GetEnableTing() bool {
	if m != nil && m.EnableTing != nil {
		return *m.EnableTing
	}
	return false
}

func (m *RoomZixunNtf) GetTingType() TingType {
	if m != nil && m.TingType != nil {
		return *m.TingType
	}
	return TingType_TT_NORMAL_TING
}

// TingAction 听牌动作
type TingAction struct {
	EnableTing       *bool     `protobuf:"varint,1,opt,name=enable_ting,json=enableTing" json:"enable_ting,omitempty"`
	TingType         *TingType `protobuf:"varint,2,opt,name=ting_type,json=tingType,enum=room.TingType" json:"ting_type,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *TingAction) Reset()                    { *m = TingAction{} }
func (m *TingAction) String() string            { return proto.CompactTextString(m) }
func (*TingAction) ProtoMessage()               {}
func (*TingAction) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{24} }

func (m *TingAction) GetEnableTing() bool {
	if m != nil && m.EnableTing != nil {
		return *m.EnableTing
	}
	return false
}

func (m *TingAction) GetTingType() TingType {
	if m != nil && m.TingType != nil {
		return *m.TingType
	}
	return TingType_TT_NORMAL_TING
}

// RoomChupaiReq 请求出牌
type RoomChupaiReq struct {
	Card             *uint32     `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
	TingAction       *TingAction `protobuf:"bytes,2,opt,name=ting_action,json=tingAction" json:"ting_action,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *RoomChupaiReq) Reset()                    { *m = RoomChupaiReq{} }
func (m *RoomChupaiReq) String() string            { return proto.CompactTextString(m) }
func (*RoomChupaiReq) ProtoMessage()               {}
func (*RoomChupaiReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{25} }

func (m *RoomChupaiReq) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *RoomChupaiReq) GetTingAction() *TingAction {
	if m != nil {
		return m.TingAction
	}
	return nil
}

// RoomChupaiNtf 出牌通知
type RoomChupaiNtf struct {
	Player           *uint64     `protobuf:"varint,1,opt,name=player" json:"player,omitempty"`
	Card             *uint32     `protobuf:"varint,2,opt,name=card" json:"card,omitempty"`
	TingAction       *TingAction `protobuf:"bytes,3,opt,name=ting_action,json=tingAction" json:"ting_action,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *RoomChupaiNtf) Reset()                    { *m = RoomChupaiNtf{} }
func (m *RoomChupaiNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomChupaiNtf) ProtoMessage()               {}
func (*RoomChupaiNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{26} }

func (m *RoomChupaiNtf) GetPlayer() uint64 {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return 0
}

func (m *RoomChupaiNtf) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *RoomChupaiNtf) GetTingAction() *TingAction {
	if m != nil {
		return m.TingAction
	}
	return nil
}

// RoomMopaiNtf 摸牌通知
type RoomMopaiNtf struct {
	Card             *uint32 `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
	Player           *uint64 `protobuf:"varint,2,opt,name=player" json:"player,omitempty"`
	Back             *bool   `protobuf:"varint,3,opt,name=back" json:"back,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomMopaiNtf) Reset()                    { *m = RoomMopaiNtf{} }
func (m *RoomMopaiNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomMopaiNtf) ProtoMessage()               {}
func (*RoomMopaiNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{27} }

func (m *RoomMopaiNtf) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *RoomMopaiNtf) GetPlayer() uint64 {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return 0
}

func (m *RoomMopaiNtf) GetBack() bool {
	if m != nil && m.Back != nil {
		return *m.Back
	}
	return false
}

// RoomWaitQianggangHuNtf 等待抢杠胡通知
type RoomWaitQianggangHuNtf struct {
	Card             *uint32 `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
	SelfCan          *bool   `protobuf:"varint,2,opt,name=self_can,json=selfCan" json:"self_can,omitempty"`
	FromPlayerId     *uint64 `protobuf:"varint,3,opt,name=from_player_id,json=fromPlayerId" json:"from_player_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomWaitQianggangHuNtf) Reset()                    { *m = RoomWaitQianggangHuNtf{} }
func (m *RoomWaitQianggangHuNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomWaitQianggangHuNtf) ProtoMessage()               {}
func (*RoomWaitQianggangHuNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{28} }

func (m *RoomWaitQianggangHuNtf) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *RoomWaitQianggangHuNtf) GetSelfCan() bool {
	if m != nil && m.SelfCan != nil {
		return *m.SelfCan
	}
	return false
}

func (m *RoomWaitQianggangHuNtf) GetFromPlayerId() uint64 {
	if m != nil && m.FromPlayerId != nil {
		return *m.FromPlayerId
	}
	return 0
}

// RoomHuNtf 胡通知
type RoomHuNtf struct {
	Players          []uint64 `protobuf:"varint,1,rep,name=players" json:"players,omitempty"`
	FromPlayerId     *uint64  `protobuf:"varint,2,opt,name=from_player_id,json=fromPlayerId" json:"from_player_id,omitempty"`
	Card             *uint32  `protobuf:"varint,3,opt,name=card" json:"card,omitempty"`
	HuType           *HuType  `protobuf:"varint,4,opt,name=hu_type,json=huType,enum=room.HuType" json:"hu_type,omitempty"`
	RealPlayerId     *uint64  `protobuf:"varint,5,opt,name=real_player_id,json=realPlayerId" json:"real_player_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RoomHuNtf) Reset()                    { *m = RoomHuNtf{} }
func (m *RoomHuNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomHuNtf) ProtoMessage()               {}
func (*RoomHuNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{29} }

func (m *RoomHuNtf) GetPlayers() []uint64 {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *RoomHuNtf) GetFromPlayerId() uint64 {
	if m != nil && m.FromPlayerId != nil {
		return *m.FromPlayerId
	}
	return 0
}

func (m *RoomHuNtf) GetCard() uint32 {
	if m != nil && m.Card != nil {
		return *m.Card
	}
	return 0
}

func (m *RoomHuNtf) GetHuType() HuType {
	if m != nil && m.HuType != nil {
		return *m.HuType
	}
	return HuType_HT_GANGHOUPAO
}

func (m *RoomHuNtf) GetRealPlayerId() uint64 {
	if m != nil && m.RealPlayerId != nil {
		return *m.RealPlayerId
	}
	return 0
}

// RoomTingInfoNtf 听牌信息通知
type RoomTingInfoNtf struct {
	TingCardInfos    []*TingCardInfo `protobuf:"bytes,1,rep,name=ting_card_infos,json=tingCardInfos" json:"ting_card_infos,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RoomTingInfoNtf) Reset()                    { *m = RoomTingInfoNtf{} }
func (m *RoomTingInfoNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomTingInfoNtf) ProtoMessage()               {}
func (*RoomTingInfoNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{30} }

func (m *RoomTingInfoNtf) GetTingCardInfos() []*TingCardInfo {
	if m != nil {
		return m.TingCardInfos
	}
	return nil
}

// 麻将组
type CardsGroup struct {
	Cards            []uint32        `protobuf:"varint,1,rep,name=cards" json:"cards,omitempty"`
	Type             *CardsGroupType `protobuf:"varint,2,opt,name=type,enum=room.CardsGroupType" json:"type,omitempty"`
	Pid              *uint64         `protobuf:"varint,3,opt,name=pid" json:"pid,omitempty"`
	IsReal           *bool           `protobuf:"varint,4,opt,name=is_real,json=isReal" json:"is_real,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *CardsGroup) Reset()                    { *m = CardsGroup{} }
func (m *CardsGroup) String() string            { return proto.CompactTextString(m) }
func (*CardsGroup) ProtoMessage()               {}
func (*CardsGroup) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{31} }

func (m *CardsGroup) GetCards() []uint32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *CardsGroup) GetType() CardsGroupType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CardsGroupType_CGT_HAND
}

func (m *CardsGroup) GetPid() uint64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *CardsGroup) GetIsReal() bool {
	if m != nil && m.IsReal != nil {
		return *m.IsReal
	}
	return false
}

// PlayerCardsGroup 玩家麻将组
type PlayerCardsGroup struct {
	PlayerId         *uint64       `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	CardsGroup       []*CardsGroup `protobuf:"bytes,2,rep,name=cards_group,json=cardsGroup" json:"cards_group,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerCardsGroup) Reset()                    { *m = PlayerCardsGroup{} }
func (m *PlayerCardsGroup) String() string            { return proto.CompactTextString(m) }
func (*PlayerCardsGroup) ProtoMessage()               {}
func (*PlayerCardsGroup) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{32} }

func (m *PlayerCardsGroup) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *PlayerCardsGroup) GetCardsGroup() []*CardsGroup {
	if m != nil {
		return m.CardsGroup
	}
	return nil
}

// RoomGameOverNtf 游戏结束通知
type RoomGameOverNtf struct {
	PlayerCardsGroup []*PlayerCardsGroup `protobuf:"bytes,1,rep,name=player_cards_group,json=playerCardsGroup" json:"player_cards_group,omitempty"`
	GameFlow         *bool               `protobuf:"varint,2,opt,name=game_flow,json=gameFlow" json:"game_flow,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *RoomGameOverNtf) Reset()                    { *m = RoomGameOverNtf{} }
func (m *RoomGameOverNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomGameOverNtf) ProtoMessage()               {}
func (*RoomGameOverNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{33} }

func (m *RoomGameOverNtf) GetPlayerCardsGroup() []*PlayerCardsGroup {
	if m != nil {
		return m.PlayerCardsGroup
	}
	return nil
}

func (m *RoomGameOverNtf) GetGameFlow() bool {
	if m != nil && m.GameFlow != nil {
		return *m.GameFlow
	}
	return false
}

// BillDetail 结算账单详情
type BillDetail struct {
	SetleType        *SettleType `protobuf:"varint,1,opt,name=setle_type,json=setleType,enum=room.SettleType" json:"setle_type,omitempty"`
	HuType           *HuType     `protobuf:"varint,2,opt,name=hu_type,json=huType,enum=room.HuType" json:"hu_type,omitempty"`
	FanType          []FanType   `protobuf:"varint,3,rep,name=fan_type,json=fanType,enum=room.FanType" json:"fan_type,omitempty"`
	FanValue         *int32      `protobuf:"varint,4,opt,name=fan_value,json=fanValue" json:"fan_value,omitempty"`
	Score            *int64      `protobuf:"varint,5,opt,name=score" json:"score,omitempty"`
	RelatedPid       []uint64    `protobuf:"varint,6,rep,name=related_pid,json=relatedPid" json:"related_pid,omitempty"`
	GenCount         *uint32     `protobuf:"varint,7,opt,name=gen_count,json=genCount" json:"gen_count,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *BillDetail) Reset()                    { *m = BillDetail{} }
func (m *BillDetail) String() string            { return proto.CompactTextString(m) }
func (*BillDetail) ProtoMessage()               {}
func (*BillDetail) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{34} }

func (m *BillDetail) GetSetleType() SettleType {
	if m != nil && m.SetleType != nil {
		return *m.SetleType
	}
	return SettleType_ST_ANGANG
}

func (m *BillDetail) GetHuType() HuType {
	if m != nil && m.HuType != nil {
		return *m.HuType
	}
	return HuType_HT_GANGHOUPAO
}

func (m *BillDetail) GetFanType() []FanType {
	if m != nil {
		return m.FanType
	}
	return nil
}

func (m *BillDetail) GetFanValue() int32 {
	if m != nil && m.FanValue != nil {
		return *m.FanValue
	}
	return 0
}

func (m *BillDetail) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *BillDetail) GetRelatedPid() []uint64 {
	if m != nil {
		return m.RelatedPid
	}
	return nil
}

func (m *BillDetail) GetGenCount() uint32 {
	if m != nil && m.GenCount != nil {
		return *m.GenCount
	}
	return 0
}

// BillPlayersInfo 结算玩家账单
type BillPlayerInfo struct {
	Pid              *uint64       `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Score            *int64        `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	CurrentScore     *int64        `protobuf:"varint,3,opt,name=current_score,json=currentScore" json:"current_score,omitempty"`
	CardValue        *int32        `protobuf:"varint,4,opt,name=card_value,json=cardValue" json:"card_value,omitempty"`
	CardsGroup       []*CardsGroup `protobuf:"bytes,5,rep,name=cards_group,json=cardsGroup" json:"cards_group,omitempty"`
	BillType         *BillType     `protobuf:"varint,6,opt,name=bill_type,json=billType,enum=room.BillType" json:"bill_type,omitempty"`
	Fan              []*Fan        `protobuf:"bytes,7,rep,name=fan" json:"fan,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *BillPlayerInfo) Reset()                    { *m = BillPlayerInfo{} }
func (m *BillPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*BillPlayerInfo) ProtoMessage()               {}
func (*BillPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{35} }

func (m *BillPlayerInfo) GetPid() uint64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *BillPlayerInfo) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *BillPlayerInfo) GetCurrentScore() int64 {
	if m != nil && m.CurrentScore != nil {
		return *m.CurrentScore
	}
	return 0
}

func (m *BillPlayerInfo) GetCardValue() int32 {
	if m != nil && m.CardValue != nil {
		return *m.CardValue
	}
	return 0
}

func (m *BillPlayerInfo) GetCardsGroup() []*CardsGroup {
	if m != nil {
		return m.CardsGroup
	}
	return nil
}

func (m *BillPlayerInfo) GetBillType() BillType {
	if m != nil && m.BillType != nil {
		return *m.BillType
	}
	return BillType_BILL_GANG
}

func (m *BillPlayerInfo) GetFan() []*Fan {
	if m != nil {
		return m.Fan
	}
	return nil
}

// RoomBalanceInfoRsp 单局结算
type RoomBalanceInfoRsp struct {
	Pid              *uint64           `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	BillDetail       []*BillDetail     `protobuf:"bytes,2,rep,name=bill_detail,json=billDetail" json:"bill_detail,omitempty"`
	BillPlayersInfo  []*BillPlayerInfo `protobuf:"bytes,3,rep,name=bill_players_info,json=billPlayersInfo" json:"bill_players_info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RoomBalanceInfoRsp) Reset()                    { *m = RoomBalanceInfoRsp{} }
func (m *RoomBalanceInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*RoomBalanceInfoRsp) ProtoMessage()               {}
func (*RoomBalanceInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{36} }

func (m *RoomBalanceInfoRsp) GetPid() uint64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *RoomBalanceInfoRsp) GetBillDetail() []*BillDetail {
	if m != nil {
		return m.BillDetail
	}
	return nil
}

func (m *RoomBalanceInfoRsp) GetBillPlayersInfo() []*BillPlayerInfo {
	if m != nil {
		return m.BillPlayersInfo
	}
	return nil
}

// RoomSettleInstantRsp 结算实时消息返回
type RoomSettleInstantRsp struct {
	BillPlayersInfo  []*BillPlayerInfo `protobuf:"bytes,1,rep,name=bill_players_info,json=billPlayersInfo" json:"bill_players_info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RoomSettleInstantRsp) Reset()                    { *m = RoomSettleInstantRsp{} }
func (m *RoomSettleInstantRsp) String() string            { return proto.CompactTextString(m) }
func (*RoomSettleInstantRsp) ProtoMessage()               {}
func (*RoomSettleInstantRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{37} }

func (m *RoomSettleInstantRsp) GetBillPlayersInfo() []*BillPlayerInfo {
	if m != nil {
		return m.BillPlayersInfo
	}
	return nil
}

// RoomResumeGameReq 恢复对局请求
type RoomResumeGameReq struct {
	Reserve          *uint32 `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomResumeGameReq) Reset()                    { *m = RoomResumeGameReq{} }
func (m *RoomResumeGameReq) String() string            { return proto.CompactTextString(m) }
func (*RoomResumeGameReq) ProtoMessage()               {}
func (*RoomResumeGameReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{38} }

func (m *RoomResumeGameReq) GetReserve() uint32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

// GamePlayerInfo 游戏中的玩家信息
type GamePlayerInfo struct {
	PlayerInfo       *RoomPlayerInfo `protobuf:"bytes,1,opt,name=player_info,json=playerInfo" json:"player_info,omitempty"`
	Color            *CardColor      `protobuf:"varint,2,opt,name=color,enum=room.CardColor" json:"color,omitempty"`
	CardsGroup       []*CardsGroup   `protobuf:"bytes,3,rep,name=cards_group,json=cardsGroup" json:"cards_group,omitempty"`
	HandCardCount    *uint32         `protobuf:"varint,4,opt,name=hand_card_count,json=handCardCount" json:"hand_card_count,omitempty"`
	IsTuoguan        *bool           `protobuf:"varint,5,opt,name=is_tuoguan,json=isTuoguan" json:"is_tuoguan,omitempty"`
	XpState          *XingPaiState   `protobuf:"varint,6,opt,name=xp_state,json=xpState,enum=room.XingPaiState" json:"xp_state,omitempty"`
	TingCardInfos    []*TingCardInfo `protobuf:"bytes,7,rep,name=ting_card_infos,json=tingCardInfos" json:"ting_card_infos,omitempty"`
	HuType           *HuType         `protobuf:"varint,8,opt,name=hu_type,json=huType,enum=room.HuType" json:"hu_type,omitempty"`
	IsTing           *bool           `protobuf:"varint,9,opt,name=is_ting,json=isTing" json:"is_ting,omitempty"`
	TingType         *TingType       `protobuf:"varint,10,opt,name=ting_type,json=tingType,enum=room.TingType" json:"ting_type,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GamePlayerInfo) Reset()                    { *m = GamePlayerInfo{} }
func (m *GamePlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*GamePlayerInfo) ProtoMessage()               {}
func (*GamePlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{39} }

func (m *GamePlayerInfo) GetPlayerInfo() *RoomPlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *GamePlayerInfo) GetColor() CardColor {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return CardColor_CC_WAN
}

func (m *GamePlayerInfo) GetCardsGroup() []*CardsGroup {
	if m != nil {
		return m.CardsGroup
	}
	return nil
}

func (m *GamePlayerInfo) GetHandCardCount() uint32 {
	if m != nil && m.HandCardCount != nil {
		return *m.HandCardCount
	}
	return 0
}

func (m *GamePlayerInfo) GetIsTuoguan() bool {
	if m != nil && m.IsTuoguan != nil {
		return *m.IsTuoguan
	}
	return false
}

func (m *GamePlayerInfo) GetXpState() XingPaiState {
	if m != nil && m.XpState != nil {
		return *m.XpState
	}
	return XingPaiState_XP_STATE_NORMAL
}

func (m *GamePlayerInfo) GetTingCardInfos() []*TingCardInfo {
	if m != nil {
		return m.TingCardInfos
	}
	return nil
}

func (m *GamePlayerInfo) GetHuType() HuType {
	if m != nil && m.HuType != nil {
		return *m.HuType
	}
	return HuType_HT_GANGHOUPAO
}

func (m *GamePlayerInfo) GetIsTing() bool {
	if m != nil && m.IsTing != nil {
		return *m.IsTing
	}
	return false
}

func (m *GamePlayerInfo) GetTingType() TingType {
	if m != nil && m.TingType != nil {
		return *m.TingType
	}
	return TingType_TT_NORMAL_TING
}

// GameDeskInfo 游戏基本信息
type GameDeskInfo struct {
	GameStage         *GameStage              `protobuf:"varint,1,opt,name=game_stage,json=gameStage,enum=room.GameStage" json:"game_stage,omitempty"`
	Players           []*GamePlayerInfo       `protobuf:"bytes,2,rep,name=players" json:"players,omitempty"`
	Dices             []uint32                `protobuf:"varint,3,rep,name=dices" json:"dices,omitempty"`
	BankerSeat        *uint32                 `protobuf:"varint,4,opt,name=banker_seat,json=bankerSeat" json:"banker_seat,omitempty"`
	EastSeat          *uint32                 `protobuf:"varint,5,opt,name=east_seat,json=eastSeat" json:"east_seat,omitempty"`
	TotalCards        *uint32                 `protobuf:"varint,6,opt,name=total_cards,json=totalCards" json:"total_cards,omitempty"`
	RemainCards       *uint32                 `protobuf:"varint,7,opt,name=remain_cards,json=remainCards" json:"remain_cards,omitempty"`
	CostTime          *uint32                 `protobuf:"varint,8,opt,name=cost_time,json=costTime" json:"cost_time,omitempty"`
	OperatePid        *uint64                 `protobuf:"varint,9,opt,name=operate_pid,json=operatePid" json:"operate_pid,omitempty"`
	DoorCard          *uint32                 `protobuf:"varint,10,opt,name=door_card,json=doorCard" json:"door_card,omitempty"`
	HasZixun          *bool                   `protobuf:"varint,11,opt,name=has_zixun,json=hasZixun" json:"has_zixun,omitempty"`
	ZixunInfo         *RoomZixunNtf           `protobuf:"bytes,12,opt,name=zixun_info,json=zixunInfo" json:"zixun_info,omitempty"`
	HasWenxun         *bool                   `protobuf:"varint,13,opt,name=has_wenxun,json=hasWenxun" json:"has_wenxun,omitempty"`
	WenxunInfo        *RoomChupaiWenxunNtf    `protobuf:"bytes,14,opt,name=wenxun_info,json=wenxunInfo" json:"wenxun_info,omitempty"`
	HasQgh            *bool                   `protobuf:"varint,15,opt,name=has_qgh,json=hasQgh" json:"has_qgh,omitempty"`
	QghInfo           *RoomWaitQianggangHuNtf `protobuf:"bytes,16,opt,name=qgh_info,json=qghInfo" json:"qgh_info,omitempty"`
	NeedHsz           *bool                   `protobuf:"varint,17,opt,name=need_hsz,json=needHsz" json:"need_hsz,omitempty"`
	GameId            *GameId                 `protobuf:"varint,18,opt,name=game_id,json=gameId,enum=room.GameId" json:"game_id,omitempty"`
	HuansanzhangInfo  *RoomHuansanzhangNtf    `protobuf:"bytes,19,opt,name=huansanzhang_info,json=huansanzhangInfo" json:"huansanzhang_info,omitempty"`
	DingqueInfo       *RoomDingqueNtf         `protobuf:"bytes,20,opt,name=dingque_info,json=dingqueInfo" json:"dingque_info,omitempty"`
	LastOutCard       *uint32                 `protobuf:"varint,21,opt,name=last_out_card,json=lastOutCard" json:"last_out_card,omitempty"`
	LastOutCardPlayer *uint64                 `protobuf:"varint,22,opt,name=last_out_card_player,json=lastOutCardPlayer" json:"last_out_card_player,omitempty"`
	XXX_unrecognized  []byte                  `json:"-"`
}

func (m *GameDeskInfo) Reset()                    { *m = GameDeskInfo{} }
func (m *GameDeskInfo) String() string            { return proto.CompactTextString(m) }
func (*GameDeskInfo) ProtoMessage()               {}
func (*GameDeskInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{40} }

func (m *GameDeskInfo) GetGameStage() GameStage {
	if m != nil && m.GameStage != nil {
		return *m.GameStage
	}
	return GameStage_GAMESTAGE_INIT
}

func (m *GameDeskInfo) GetPlayers() []*GamePlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameDeskInfo) GetDices() []uint32 {
	if m != nil {
		return m.Dices
	}
	return nil
}

func (m *GameDeskInfo) GetBankerSeat() uint32 {
	if m != nil && m.BankerSeat != nil {
		return *m.BankerSeat
	}
	return 0
}

func (m *GameDeskInfo) GetEastSeat() uint32 {
	if m != nil && m.EastSeat != nil {
		return *m.EastSeat
	}
	return 0
}

func (m *GameDeskInfo) GetTotalCards() uint32 {
	if m != nil && m.TotalCards != nil {
		return *m.TotalCards
	}
	return 0
}

func (m *GameDeskInfo) GetRemainCards() uint32 {
	if m != nil && m.RemainCards != nil {
		return *m.RemainCards
	}
	return 0
}

func (m *GameDeskInfo) GetCostTime() uint32 {
	if m != nil && m.CostTime != nil {
		return *m.CostTime
	}
	return 0
}

func (m *GameDeskInfo) GetOperatePid() uint64 {
	if m != nil && m.OperatePid != nil {
		return *m.OperatePid
	}
	return 0
}

func (m *GameDeskInfo) GetDoorCard() uint32 {
	if m != nil && m.DoorCard != nil {
		return *m.DoorCard
	}
	return 0
}

func (m *GameDeskInfo) GetHasZixun() bool {
	if m != nil && m.HasZixun != nil {
		return *m.HasZixun
	}
	return false
}

func (m *GameDeskInfo) GetZixunInfo() *RoomZixunNtf {
	if m != nil {
		return m.ZixunInfo
	}
	return nil
}

func (m *GameDeskInfo) GetHasWenxun() bool {
	if m != nil && m.HasWenxun != nil {
		return *m.HasWenxun
	}
	return false
}

func (m *GameDeskInfo) GetWenxunInfo() *RoomChupaiWenxunNtf {
	if m != nil {
		return m.WenxunInfo
	}
	return nil
}

func (m *GameDeskInfo) GetHasQgh() bool {
	if m != nil && m.HasQgh != nil {
		return *m.HasQgh
	}
	return false
}

func (m *GameDeskInfo) GetQghInfo() *RoomWaitQianggangHuNtf {
	if m != nil {
		return m.QghInfo
	}
	return nil
}

func (m *GameDeskInfo) GetNeedHsz() bool {
	if m != nil && m.NeedHsz != nil {
		return *m.NeedHsz
	}
	return false
}

func (m *GameDeskInfo) GetGameId() GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return GameId_GAMEID_XUELIU
}

func (m *GameDeskInfo) GetHuansanzhangInfo() *RoomHuansanzhangNtf {
	if m != nil {
		return m.HuansanzhangInfo
	}
	return nil
}

func (m *GameDeskInfo) GetDingqueInfo() *RoomDingqueNtf {
	if m != nil {
		return m.DingqueInfo
	}
	return nil
}

func (m *GameDeskInfo) GetLastOutCard() uint32 {
	if m != nil && m.LastOutCard != nil {
		return *m.LastOutCard
	}
	return 0
}

func (m *GameDeskInfo) GetLastOutCardPlayer() uint64 {
	if m != nil && m.LastOutCardPlayer != nil {
		return *m.LastOutCardPlayer
	}
	return 0
}

// RoomResumeGameRsp 恢复对局返回
type RoomResumeGameRsp struct {
	ResumeRes        *RoomError    `protobuf:"varint,1,opt,name=resume_res,json=resumeRes,enum=room.RoomError" json:"resume_res,omitempty"`
	GameId           *uint32       `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId          *uint32       `protobuf:"varint,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	MajongInfo       *GameDeskInfo `protobuf:"bytes,4,opt,name=majong_info,json=majongInfo" json:"majong_info,omitempty"`
	DdzInfo          *DDZDeskInfo  `protobuf:"bytes,5,opt,name=ddz_info,json=ddzInfo" json:"ddz_info,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *RoomResumeGameRsp) Reset()                    { *m = RoomResumeGameRsp{} }
func (m *RoomResumeGameRsp) String() string            { return proto.CompactTextString(m) }
func (*RoomResumeGameRsp) ProtoMessage()               {}
func (*RoomResumeGameRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{41} }

func (m *RoomResumeGameRsp) GetResumeRes() RoomError {
	if m != nil && m.ResumeRes != nil {
		return *m.ResumeRes
	}
	return RoomError_SUCCESS
}

func (m *RoomResumeGameRsp) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *RoomResumeGameRsp) GetLevelId() uint32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

func (m *RoomResumeGameRsp) GetMajongInfo() *GameDeskInfo {
	if m != nil {
		return m.MajongInfo
	}
	return nil
}

func (m *RoomResumeGameRsp) GetDdzInfo() *DDZDeskInfo {
	if m != nil {
		return m.DdzInfo
	}
	return nil
}

// RoomTuoGuanReq 托管/取消托管请求
type RoomTuoGuanReq struct {
	Tuoguan          *bool  `protobuf:"varint,1,opt,name=tuoguan" json:"tuoguan,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RoomTuoGuanReq) Reset()                    { *m = RoomTuoGuanReq{} }
func (m *RoomTuoGuanReq) String() string            { return proto.CompactTextString(m) }
func (*RoomTuoGuanReq) ProtoMessage()               {}
func (*RoomTuoGuanReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{42} }

func (m *RoomTuoGuanReq) GetTuoguan() bool {
	if m != nil && m.Tuoguan != nil {
		return *m.Tuoguan
	}
	return false
}

// RoomTuoGuanNtf 托管状态通知
type RoomTuoGuanNtf struct {
	Tuoguan          *bool  `protobuf:"varint,1,opt,name=tuoguan" json:"tuoguan,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RoomTuoGuanNtf) Reset()                    { *m = RoomTuoGuanNtf{} }
func (m *RoomTuoGuanNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomTuoGuanNtf) ProtoMessage()               {}
func (*RoomTuoGuanNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{43} }

func (m *RoomTuoGuanNtf) GetTuoguan() bool {
	if m != nil && m.Tuoguan != nil {
		return *m.Tuoguan
	}
	return false
}

// RoomCancelTuoGuanReq 取消托管请求(@Deprecated)
type RoomCancelTuoGuanReq struct {
	Reserved         *bool  `protobuf:"varint,1,opt,name=reserved" json:"reserved,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RoomCancelTuoGuanReq) Reset()                    { *m = RoomCancelTuoGuanReq{} }
func (m *RoomCancelTuoGuanReq) String() string            { return proto.CompactTextString(m) }
func (*RoomCancelTuoGuanReq) ProtoMessage()               {}
func (*RoomCancelTuoGuanReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{44} }

func (m *RoomCancelTuoGuanReq) GetReserved() bool {
	if m != nil && m.Reserved != nil {
		return *m.Reserved
	}
	return false
}

// RoomUsePropReq 玩家使用道具请求
type RoomUsePropReq struct {
	PlayerId         *uint64          `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	PropId           *common.PropType `protobuf:"varint,2,opt,name=prop_id,json=propId,enum=common.PropType" json:"prop_id,omitempty"`
	GameId           *common.GameId   `protobuf:"varint,3,opt,name=game_id,json=gameId,enum=common.GameId" json:"game_id,omitempty"`
	LevelId          *int32           `protobuf:"varint,4,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *RoomUsePropReq) Reset()                    { *m = RoomUsePropReq{} }
func (m *RoomUsePropReq) String() string            { return proto.CompactTextString(m) }
func (*RoomUsePropReq) ProtoMessage()               {}
func (*RoomUsePropReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{45} }

func (m *RoomUsePropReq) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *RoomUsePropReq) GetPropId() common.PropType {
	if m != nil && m.PropId != nil {
		return *m.PropId
	}
	return common.PropType_INVALID_PROP
}

func (m *RoomUsePropReq) GetGameId() common.GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return common.GameId_GAMEID_XUELIU
}

func (m *RoomUsePropReq) GetLevelId() int32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

// RoomUsePropRsp 玩家使用道具应答，失败才应答
type RoomUsePropRsp struct {
	ErrCode          *RoomError `protobuf:"varint,1,opt,name=err_code,json=errCode,enum=room.RoomError" json:"err_code,omitempty"`
	ErrDesc          *string    `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RoomUsePropRsp) Reset()                    { *m = RoomUsePropRsp{} }
func (m *RoomUsePropRsp) String() string            { return proto.CompactTextString(m) }
func (*RoomUsePropRsp) ProtoMessage()               {}
func (*RoomUsePropRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{46} }

func (m *RoomUsePropRsp) GetErrCode() RoomError {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return RoomError_SUCCESS
}

func (m *RoomUsePropRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

// RoomUsePropNtf 玩家使用道具广播
type RoomUsePropNtf struct {
	FromPlayerId     *uint64          `protobuf:"varint,1,opt,name=from_player_id,json=fromPlayerId" json:"from_player_id,omitempty"`
	ToPlayerId       *uint64          `protobuf:"varint,2,opt,name=to_player_id,json=toPlayerId" json:"to_player_id,omitempty"`
	PropId           *common.PropType `protobuf:"varint,3,opt,name=prop_id,json=propId,enum=common.PropType" json:"prop_id,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *RoomUsePropNtf) Reset()                    { *m = RoomUsePropNtf{} }
func (m *RoomUsePropNtf) String() string            { return proto.CompactTextString(m) }
func (*RoomUsePropNtf) ProtoMessage()               {}
func (*RoomUsePropNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{47} }

func (m *RoomUsePropNtf) GetFromPlayerId() uint64 {
	if m != nil && m.FromPlayerId != nil {
		return *m.FromPlayerId
	}
	return 0
}

func (m *RoomUsePropNtf) GetToPlayerId() uint64 {
	if m != nil && m.ToPlayerId != nil {
		return *m.ToPlayerId
	}
	return 0
}

func (m *RoomUsePropNtf) GetPropId() common.PropType {
	if m != nil && m.PropId != nil {
		return *m.PropId
	}
	return common.PropType_INVALID_PROP
}

// RoomAutoHuReq 自动胡牌请求
type RoomAutoHuReq struct {
	Enable           *bool  `protobuf:"varint,1,opt,name=enable" json:"enable,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RoomAutoHuReq) Reset()                    { *m = RoomAutoHuReq{} }
func (m *RoomAutoHuReq) String() string            { return proto.CompactTextString(m) }
func (*RoomAutoHuReq) ProtoMessage()               {}
func (*RoomAutoHuReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{48} }

func (m *RoomAutoHuReq) GetEnable() bool {
	if m != nil && m.Enable != nil {
		return *m.Enable
	}
	return false
}

// RoomAutoHuRsp 自动胡牌响应
type RoomAutoHuRsp struct {
	ErrCode          *RoomError `protobuf:"varint,1,opt,name=err_code,json=errCode,enum=room.RoomError" json:"err_code,omitempty"`
	Enable           *bool      `protobuf:"varint,2,opt,name=enable" json:"enable,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RoomAutoHuRsp) Reset()                    { *m = RoomAutoHuRsp{} }
func (m *RoomAutoHuRsp) String() string            { return proto.CompactTextString(m) }
func (*RoomAutoHuRsp) ProtoMessage()               {}
func (*RoomAutoHuRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{49} }

func (m *RoomAutoHuRsp) GetErrCode() RoomError {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return RoomError_SUCCESS
}

func (m *RoomAutoHuRsp) GetEnable() bool {
	if m != nil && m.Enable != nil {
		return *m.Enable
	}
	return false
}

type CountDownNtf struct {
	CountDown        *uint32 `protobuf:"varint,1,opt,name=count_down,json=countDown" json:"count_down,omitempty"`
	AddCountDown     *uint32 `protobuf:"varint,2,opt,name=add_count_down,json=addCountDown" json:"add_count_down,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CountDownNtf) Reset()                    { *m = CountDownNtf{} }
func (m *CountDownNtf) String() string            { return proto.CompactTextString(m) }
func (*CountDownNtf) ProtoMessage()               {}
func (*CountDownNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{50} }

func (m *CountDownNtf) GetCountDown() uint32 {
	if m != nil && m.CountDown != nil {
		return *m.CountDown
	}
	return 0
}

func (m *CountDownNtf) GetAddCountDown() uint32 {
	if m != nil && m.AddCountDown != nil {
		return *m.AddCountDown
	}
	return 0
}

func init() {
	proto.RegisterType((*Card)(nil), "room.Card")
	proto.RegisterType((*Fan)(nil), "room.Fan")
	proto.RegisterType((*RoomStartGameNtf)(nil), "room.RoomStartGameNtf")
	proto.RegisterType((*RoomXipaiNtf)(nil), "room.RoomXipaiNtf")
	proto.RegisterType((*PlayerCardCount)(nil), "room.PlayerCardCount")
	proto.RegisterType((*RoomFapaiNtf)(nil), "room.RoomFapaiNtf")
	proto.RegisterType((*RoomHuansanzhangNtf)(nil), "room.RoomHuansanzhangNtf")
	proto.RegisterType((*RoomHuansanzhangReq)(nil), "room.RoomHuansanzhangReq")
	proto.RegisterType((*RoomHuansanzhangRsp)(nil), "room.RoomHuansanzhangRsp")
	proto.RegisterType((*RoomHuansanzhangFinishNtf)(nil), "room.RoomHuansanzhangFinishNtf")
	proto.RegisterType((*RoomDingqueNtf)(nil), "room.RoomDingqueNtf")
	proto.RegisterType((*RoomDingqueReq)(nil), "room.RoomDingqueReq")
	proto.RegisterType((*RoomDingqueRsp)(nil), "room.RoomDingqueRsp")
	proto.RegisterType((*PlayerDingqueColor)(nil), "room.PlayerDingqueColor")
	proto.RegisterType((*RoomDingqueFinishNtf)(nil), "room.RoomDingqueFinishNtf")
	proto.RegisterType((*RoomChiInfo)(nil), "room.RoomChiInfo")
	proto.RegisterType((*RoomChupaiWenxunNtf)(nil), "room.RoomChupaiWenxunNtf")
	proto.RegisterType((*RoomXingpaiActionReq)(nil), "room.RoomXingpaiActionReq")
	proto.RegisterType((*RoomChiNtf)(nil), "room.RoomChiNtf")
	proto.RegisterType((*RoomPengNtf)(nil), "room.RoomPengNtf")
	proto.RegisterType((*RoomGangNtf)(nil), "room.RoomGangNtf")
	proto.RegisterType((*TingCardInfo)(nil), "room.TingCardInfo")
	proto.RegisterType((*CanTingCardInfo)(nil), "room.CanTingCardInfo")
	proto.RegisterType((*RoomZixunNtf)(nil), "room.RoomZixunNtf")
	proto.RegisterType((*TingAction)(nil), "room.TingAction")
	proto.RegisterType((*RoomChupaiReq)(nil), "room.RoomChupaiReq")
	proto.RegisterType((*RoomChupaiNtf)(nil), "room.RoomChupaiNtf")
	proto.RegisterType((*RoomMopaiNtf)(nil), "room.RoomMopaiNtf")
	proto.RegisterType((*RoomWaitQianggangHuNtf)(nil), "room.RoomWaitQianggangHuNtf")
	proto.RegisterType((*RoomHuNtf)(nil), "room.RoomHuNtf")
	proto.RegisterType((*RoomTingInfoNtf)(nil), "room.RoomTingInfoNtf")
	proto.RegisterType((*CardsGroup)(nil), "room.CardsGroup")
	proto.RegisterType((*PlayerCardsGroup)(nil), "room.PlayerCardsGroup")
	proto.RegisterType((*RoomGameOverNtf)(nil), "room.RoomGameOverNtf")
	proto.RegisterType((*BillDetail)(nil), "room.BillDetail")
	proto.RegisterType((*BillPlayerInfo)(nil), "room.BillPlayerInfo")
	proto.RegisterType((*RoomBalanceInfoRsp)(nil), "room.RoomBalanceInfoRsp")
	proto.RegisterType((*RoomSettleInstantRsp)(nil), "room.RoomSettleInstantRsp")
	proto.RegisterType((*RoomResumeGameReq)(nil), "room.RoomResumeGameReq")
	proto.RegisterType((*GamePlayerInfo)(nil), "room.GamePlayerInfo")
	proto.RegisterType((*GameDeskInfo)(nil), "room.GameDeskInfo")
	proto.RegisterType((*RoomResumeGameRsp)(nil), "room.RoomResumeGameRsp")
	proto.RegisterType((*RoomTuoGuanReq)(nil), "room.RoomTuoGuanReq")
	proto.RegisterType((*RoomTuoGuanNtf)(nil), "room.RoomTuoGuanNtf")
	proto.RegisterType((*RoomCancelTuoGuanReq)(nil), "room.RoomCancelTuoGuanReq")
	proto.RegisterType((*RoomUsePropReq)(nil), "room.RoomUsePropReq")
	proto.RegisterType((*RoomUsePropRsp)(nil), "room.RoomUsePropRsp")
	proto.RegisterType((*RoomUsePropNtf)(nil), "room.RoomUsePropNtf")
	proto.RegisterType((*RoomAutoHuReq)(nil), "room.RoomAutoHuReq")
	proto.RegisterType((*RoomAutoHuRsp)(nil), "room.RoomAutoHuRsp")
	proto.RegisterType((*CountDownNtf)(nil), "room.CountDownNtf")
}

func init() { proto.RegisterFile("game_common.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 2487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0xdb, 0x6e, 0x1c, 0xc7,
	0xd1, 0xc6, 0x1e, 0xc8, 0x9d, 0xad, 0x3d, 0x90, 0x1c, 0xd1, 0xf4, 0x52, 0xfa, 0x0d, 0xd3, 0xf3,
	0x5b, 0x31, 0xe3, 0xd8, 0x54, 0xc4, 0x20, 0x70, 0x60, 0x18, 0x49, 0x24, 0x32, 0xa4, 0x18, 0x40,
	0x36, 0x3d, 0x54, 0x6c, 0x41, 0x37, 0x83, 0xde, 0x99, 0xe6, 0xee, 0xc4, 0xbb, 0x3d, 0xc3, 0xe9,
	0x19, 0x51, 0xe2, 0x65, 0x82, 0x3c, 0x42, 0x72, 0x93, 0x3c, 0x42, 0x80, 0xbc, 0x42, 0x9e, 0x23,
	0xf7, 0x79, 0x85, 0x00, 0xb9, 0x4a, 0x50, 0x55, 0x3d, 0x87, 0x1d, 0x1e, 0x44, 0x21, 0xc9, 0xd5,
	0x4e, 0x57, 0x57, 0x57, 0x57, 0x57, 0x7d, 0x5d, 0x5d, 0x55, 0x0b, 0x6b, 0x13, 0x31, 0x97, 0x9e,
	0x1f, 0xcd, 0xe7, 0x91, 0xda, 0x89, 0x93, 0x28, 0x8d, 0xec, 0x76, 0x12, 0x45, 0xf3, 0xbb, 0x3d,
	0x99, 0x24, 0x51, 0xc2, 0xa4, 0xbb, 0x30, 0x16, 0x5a, 0xe6, 0xdf, 0x52, 0x65, 0x73, 0xf3, 0xdd,
	0xaf, 0x2e, 0xbc, 0x3b, 0x24, 0x59, 0x41, 0x70, 0xc1, 0x63, 0x67, 0x0f, 0xda, 0x7b, 0x22, 0x09,
	0xec, 0xfb, 0xb0, 0xe4, 0x47, 0xb3, 0x28, 0x19, 0x35, 0xb6, 0x1a, 0xdb, 0xc3, 0xdd, 0x95, 0x1d,
	0xdc, 0x60, 0x07, 0xa7, 0xf6, 0x90, 0xec, 0xf2, 0xac, 0xbd, 0x0e, 0x4b, 0x71, 0x14, 0xaa, 0x74,
	0xd4, 0xdc, 0x6a, 0x6c, 0x2f, 0xb9, 0x3c, 0x70, 0x5c, 0x68, 0x1d, 0x08, 0x65, 0x7f, 0x00, 0x6d,
	0x25, 0xe6, 0xd2, 0x88, 0x18, 0xb0, 0x88, 0x03, 0xa1, 0x9e, 0xbd, 0x8e, 0xa5, 0x4b, 0x53, 0xb8,
	0xfe, 0xa5, 0x98, 0x65, 0x32, 0x5f, 0x4f, 0x03, 0xdb, 0x86, 0x76, 0xfa, 0x3a, 0x96, 0xa3, 0xd6,
	0x56, 0x63, 0x7b, 0xe0, 0xd2, 0xb7, 0x73, 0x08, 0xab, 0x6e, 0x14, 0xcd, 0x4f, 0x52, 0x91, 0xa4,
	0x87, 0x62, 0x2e, 0xbf, 0x4c, 0x4f, 0xed, 0x11, 0x74, 0x12, 0xa9, 0x65, 0xf2, 0x92, 0xf7, 0x18,
	0xb8, 0xf9, 0xd0, 0xde, 0x04, 0x4b, 0x49, 0x19, 0x78, 0x53, 0x7d, 0x41, 0xa2, 0x2d, 0xb7, 0x83,
	0xe3, 0x27, 0xfa, 0xc2, 0x09, 0xa0, 0x8f, 0x82, 0x9e, 0x87, 0xb1, 0x08, 0x51, 0xc8, 0x3a, 0x2c,
	0x05, 0xa1, 0x2f, 0xf5, 0xa8, 0xb1, 0xd5, 0xda, 0x1e, 0xb8, 0x3c, 0xb0, 0xdf, 0x03, 0x48, 0xa3,
	0x54, 0xcc, 0x3c, 0x5f, 0x24, 0x01, 0x89, 0x18, 0xb8, 0x5d, 0xa2, 0x90, 0x79, 0xde, 0x87, 0xde,
	0x58, 0xa8, 0xef, 0x64, 0xe2, 0x69, 0x29, 0x52, 0xa3, 0x28, 0x30, 0xe9, 0x44, 0x8a, 0xd4, 0x79,
	0x0a, 0x2b, 0xc7, 0x33, 0xf1, 0x5a, 0x26, 0x6c, 0xb2, 0x4c, 0xa5, 0xf6, 0x3d, 0xe8, 0xc6, 0x44,
	0xf2, 0xc2, 0x80, 0xf4, 0x6d, 0xbb, 0x16, 0x13, 0x8e, 0x02, 0xdc, 0x0f, 0x77, 0xf2, 0x7c, 0x64,
	0xcd, 0xf7, 0xf3, 0xf3, 0xb5, 0x4e, 0xc8, 0x4a, 0x1f, 0x88, 0x52, 0x69, 0x9c, 0x2c, 0x94, 0xa6,
	0x81, 0xbd, 0x07, 0xb6, 0xd9, 0xa1, 0x94, 0xa5, 0x47, 0xcd, 0xad, 0xd6, 0x76, 0x6f, 0xf7, 0x1d,
	0x36, 0x7f, 0x4d, 0x29, 0x77, 0x35, 0x5e, 0x24, 0x68, 0xe7, 0x0b, 0xb8, 0x83, 0x5b, 0x3d, 0xc9,
	0x84, 0xd2, 0x42, 0x5d, 0x4c, 0x85, 0x9a, 0xe0, 0x8e, 0xf7, 0xc1, 0x9a, 0xea, 0x0b, 0x36, 0x47,
	0x83, 0x24, 0x42, 0x89, 0x09, 0xb7, 0x33, 0xd5, 0x17, 0xf8, 0xe1, 0xfc, 0xec, 0xf2, 0x6a, 0x57,
	0x9e, 0x5d, 0xa3, 0xaf, 0x0d, 0x6d, 0x9d, 0x25, 0xd2, 0x78, 0x88, 0xbe, 0x9d, 0x47, 0x57, 0x08,
	0xd0, 0xb1, 0xfd, 0x31, 0x58, 0x32, 0x49, 0x3c, 0x3f, 0x0a, 0xe4, 0x22, 0x24, 0x91, 0xf9, 0x17,
	0x08, 0x7b, 0xb7, 0x23, 0x93, 0x64, 0x2f, 0x0a, 0xa4, 0xf3, 0x9b, 0x06, 0x6c, 0xd6, 0x65, 0x1c,
	0x84, 0x2a, 0xd4, 0x53, 0x3c, 0xc8, 0x26, 0x58, 0xa1, 0xf2, 0xaa, 0xda, 0x74, 0x42, 0xb5, 0x47,
	0xfa, 0xdc, 0x83, 0x6e, 0x94, 0xa5, 0x66, 0xae, 0x49, 0x73, 0x56, 0x94, 0xa5, 0x3c, 0xf9, 0x29,
	0x74, 0x83, 0x30, 0x91, 0x7e, 0x1a, 0x46, 0x8a, 0x1c, 0x5e, 0xa8, 0xb0, 0x9f, 0x93, 0xdd, 0x92,
	0xc3, 0xf9, 0x0c, 0x86, 0xa8, 0xc3, 0x7e, 0xa8, 0x26, 0x67, 0x99, 0x64, 0x0b, 0xde, 0xe6, 0x4a,
	0xd5, 0x16, 0xa2, 0xf1, 0x6e, 0xb9, 0xf0, 0x8b, 0xc5, 0x85, 0x6f, 0x69, 0xb4, 0xe7, 0x60, 0x33,
	0x36, 0xcc, 0x7a, 0x12, 0x7d, 0x33, 0x66, 0x0b, 0xbd, 0x9a, 0x37, 0xea, 0x35, 0x86, 0xf5, 0x8a,
	0x5e, 0xa5, 0x23, 0x7e, 0x09, 0xeb, 0x46, 0x76, 0xc0, 0x53, 0x5e, 0x7e, 0x4a, 0x44, 0xd7, 0xa8,
	0x8a, 0xd7, 0xaa, 0x4e, 0xae, 0xc1, 0x78, 0x95, 0xe6, 0xfc, 0x14, 0x7a, 0xb8, 0xc7, 0xde, 0x34,
	0x3c, 0x52, 0xa7, 0xd1, 0x35, 0x70, 0xdb, 0x04, 0xcb, 0x9f, 0x86, 0xd5, 0x1b, 0xdd, 0xf1, 0xa7,
	0x21, 0xc1, 0xf6, 0xef, 0x0d, 0x86, 0xdd, 0xde, 0x34, 0x8b, 0x45, 0xf8, 0xad, 0x54, 0xaf, 0x32,
	0x85, 0x3a, 0xda, 0xd0, 0x36, 0x88, 0xa7, 0x48, 0xe4, 0x9b, 0xbb, 0x2f, 0x95, 0x18, 0xcf, 0xa4,
	0x17, 0x4b, 0x35, 0x31, 0xe0, 0x05, 0x26, 0x1d, 0x4b, 0x35, 0xb1, 0x3f, 0x82, 0x15, 0xc3, 0x30,
	0x0f, 0xd5, 0x64, 0x22, 0xd4, 0x84, 0xf0, 0x62, 0xb9, 0x43, 0x26, 0x3f, 0x35, 0x54, 0xfb, 0x3e,
	0x18, 0x8a, 0x17, 0x84, 0x42, 0xc5, 0x22, 0x1a, 0xb5, 0x89, 0x6f, 0xc0, 0xd4, 0x7d, 0x26, 0xa2,
	0x13, 0x0c, 0xdb, 0x59, 0x38, 0x5a, 0x22, 0x0e, 0x8b, 0x09, 0x5f, 0x87, 0xf6, 0x27, 0x7c, 0xa8,
	0x50, 0x9d, 0x46, 0xa3, 0xe5, 0xad, 0xc6, 0x76, 0x6f, 0x77, 0xad, 0xf4, 0xb1, 0xb1, 0x07, 0x9d,
	0x13, 0x3f, 0x9c, 0xbf, 0x34, 0xd8, 0x19, 0xcf, 0x43, 0x35, 0x89, 0x45, 0xf8, 0x88, 0x61, 0x2b,
	0xcf, 0xec, 0x1f, 0x42, 0x57, 0xd0, 0x20, 0x77, 0xf4, 0x70, 0xf7, 0x0e, 0xcb, 0x59, 0x64, 0xb5,
	0x98, 0xeb, 0x28, 0x40, 0xad, 0xf0, 0x10, 0x55, 0x73, 0x5a, 0x48, 0xa0, 0xf8, 0xf8, 0x03, 0x33,
	0x59, 0x84, 0xf1, 0xe1, 0xee, 0x90, 0xc5, 0x1d, 0x0a, 0x35, 0xa1, 0x07, 0x80, 0x98, 0xf1, 0x0b,
	0x25, 0xe5, 0x7e, 0xd1, 0xa3, 0x36, 0x5f, 0x3b, 0xe3, 0x18, 0xed, 0xfc, 0xae, 0x01, 0x60, 0x8e,
	0x82, 0x0e, 0xd9, 0x82, 0x7e, 0x1a, 0x79, 0x75, 0x4c, 0x42, 0x1a, 0x1d, 0xe7, 0xa8, 0xfc, 0x10,
	0x86, 0xa7, 0x49, 0x34, 0xaf, 0xf0, 0x34, 0x89, 0xa7, 0x8f, 0xd4, 0x82, 0xab, 0x40, 0x48, 0xeb,
	0x3a, 0x84, 0xb4, 0x17, 0x11, 0x12, 0x32, 0xc2, 0xd0, 0xc1, 0xff, 0x4d, 0x3d, 0x72, 0x80, 0xb5,
	0x4a, 0x80, 0x39, 0x7f, 0x68, 0xf0, 0x5e, 0x87, 0xe2, 0x7f, 0xbe, 0xd7, 0xa2, 0xa3, 0xda, 0x37,
	0x3b, 0xca, 0x79, 0x04, 0xfd, 0x67, 0x21, 0x7b, 0x98, 0xae, 0xd9, 0x3d, 0xe8, 0xa6, 0x61, 0x0e,
	0x01, 0xbe, 0x22, 0x56, 0x6a, 0x18, 0xd0, 0xc2, 0x69, 0x38, 0x97, 0xda, 0x60, 0x83, 0x07, 0xce,
	0x29, 0xac, 0xec, 0x09, 0xb5, 0x20, 0x65, 0x13, 0xac, 0x3c, 0xea, 0xe6, 0xcf, 0xb8, 0x09, 0xba,
	0xf6, 0x4f, 0x60, 0x58, 0x6c, 0xc0, 0x10, 0xe7, 0xc7, 0xcc, 0x66, 0x15, 0xab, 0x62, 0xdc, 0x7e,
	0x5a, 0x19, 0x39, 0xbf, 0x6f, 0xf1, 0x8b, 0xf9, 0x22, 0x34, 0x37, 0x79, 0x07, 0xee, 0x98, 0x4b,
	0x24, 0x54, 0x81, 0xdb, 0x3c, 0x40, 0xac, 0xf1, 0xd4, 0x23, 0x95, 0x03, 0x58, 0x57, 0xf8, 0xc7,
	0x59, 0x85, 0xbf, 0x59, 0xe5, 0x7f, 0x9c, 0x95, 0xfc, 0x65, 0x54, 0xb8, 0x08, 0xe7, 0x91, 0xb9,
	0xf0, 0x26, 0x2a, 0xbc, 0x08, 0xe7, 0x51, 0x45, 0xa0, 0x4f, 0x41, 0x66, 0x01, 0xef, 0x46, 0x20,
	0x87, 0x1f, 0x16, 0xf8, 0x18, 0x6c, 0x5f, 0x28, 0xaf, 0x76, 0xfe, 0xa5, 0xea, 0x63, 0x5e, 0xb3,
	0xa4, 0xbb, 0xe2, 0xd7, 0x4c, 0xbb, 0x10, 0x39, 0x96, 0x6b, 0x91, 0xe3, 0x3e, 0x74, 0xa6, 0x19,
	0x3b, 0xbe, 0x43, 0x8e, 0xef, 0xb3, 0xd4, 0x27, 0x19, 0xb9, 0x7d, 0x79, 0x4a, 0xbf, 0x95, 0x83,
	0xa1, 0x2a, 0x23, 0xab, 0x7a, 0x30, 0xdc, 0x0c, 0x21, 0x44, 0x4a, 0x92, 0xa4, 0x6e, 0x15, 0x42,
	0x38, 0xcd, 0x10, 0x4a, 0xcd, 0x97, 0xf3, 0x02, 0x00, 0xa9, 0x1c, 0x4d, 0xea, 0xb2, 0x1b, 0x37,
	0xcb, 0x6e, 0xbe, 0x41, 0xf6, 0x37, 0x30, 0x28, 0x63, 0x38, 0x06, 0xb5, 0xab, 0xa2, 0xf7, 0x43,
	0xe8, 0x91, 0x44, 0x8e, 0x63, 0x24, 0xb3, 0xb7, 0xbb, 0x5a, 0xca, 0x34, 0x71, 0x0e, 0xd2, 0xe2,
	0xdb, 0x51, 0x55, 0xb9, 0x88, 0xa5, 0x0d, 0x58, 0xe6, 0x9b, 0x66, 0xae, 0xa2, 0x19, 0x15, 0xfb,
	0x35, 0xaf, 0xdf, 0xaf, 0x75, 0x8b, 0xfd, 0xbe, 0x64, 0xe8, 0x3e, 0x8d, 0xcc, 0x76, 0x57, 0x1d,
	0xa3, 0x54, 0xa1, 0x59, 0x57, 0x61, 0x2c, 0xfc, 0xef, 0x0c, 0xfe, 0xe8, 0xdb, 0x99, 0xc3, 0x06,
	0xca, 0xfb, 0x56, 0x84, 0xe9, 0xd7, 0xa1, 0xe0, 0xb7, 0xe7, 0x49, 0x76, 0x9d, 0xe4, 0x4d, 0xb0,
	0xb4, 0x9c, 0x9d, 0x7a, 0xbe, 0x50, 0x79, 0xea, 0x8c, 0xe3, 0x3d, 0xa1, 0xae, 0x08, 0x33, 0xad,
	0xcb, 0x61, 0xc6, 0xf9, 0x73, 0x03, 0xba, 0x9c, 0x7e, 0x99, 0x1c, 0x9d, 0xd9, 0xf9, 0xae, 0xb5,
	0xdd, 0x7c, 0xf8, 0x1f, 0x04, 0xad, 0x0a, 0x72, 0xdb, 0x37, 0x20, 0xf7, 0x43, 0x18, 0x26, 0x52,
	0xcc, 0x2a, 0x1b, 0x2c, 0xf1, 0x06, 0x48, 0x2d, 0xd4, 0x7d, 0x0a, 0x2b, 0xa8, 0x2d, 0xfa, 0x02,
	0xef, 0x0c, 0xea, 0xfc, 0x39, 0xac, 0x2c, 0x5e, 0x3b, 0x6d, 0x92, 0x92, 0xab, 0xe2, 0xce, 0xa0,
	0x1a, 0x77, 0xb4, 0x73, 0x0e, 0x40, 0xf7, 0xf7, 0x30, 0x89, 0xb2, 0xf8, 0x9a, 0x44, 0x64, 0xdb,
	0xd4, 0x37, 0x0c, 0xe8, 0xf5, 0x32, 0x6f, 0xe2, 0x55, 0x5c, 0x1f, 0x21, 0x87, 0xbd, 0x0a, 0xad,
	0xb8, 0x30, 0x33, 0x7e, 0xda, 0xef, 0x42, 0x27, 0xd4, 0x1e, 0x9e, 0xc0, 0x24, 0x0b, 0xcb, 0xa1,
	0x76, 0xa5, 0x98, 0x39, 0x63, 0x58, 0x2d, 0x93, 0x7b, 0xb3, 0xfd, 0x8d, 0xe9, 0xdb, 0x43, 0xe8,
	0x91, 0x3a, 0xde, 0x04, 0x79, 0x4d, 0x64, 0x5d, 0xad, 0x2b, 0xe3, 0x52, 0x5d, 0xc2, 0xdf, 0x4e,
	0xca, 0xb6, 0xc2, 0xfa, 0xeb, 0xab, 0x97, 0x32, 0x41, 0x5b, 0xed, 0x2f, 0xd4, 0x1c, 0xb9, 0x30,
	0x36, 0xd7, 0x46, 0xbd, 0xe6, 0x30, 0x22, 0x2b, 0x45, 0x47, 0xa9, 0x28, 0x15, 0xa2, 0xa7, 0xb3,
	0xe8, 0xdc, 0xa0, 0xce, 0x42, 0xc2, 0xc1, 0x2c, 0x3a, 0x77, 0xfe, 0xd5, 0x00, 0x78, 0x1c, 0xce,
	0x66, 0xfb, 0x32, 0x15, 0xe1, 0xcc, 0x7e, 0x00, 0xa0, 0x65, 0x8a, 0x31, 0x03, 0x6d, 0xc8, 0xb9,
	0x8a, 0x51, 0xfb, 0x44, 0xa6, 0xe9, 0x4c, 0x92, 0xfd, 0xba, 0xc4, 0x43, 0x38, 0xa8, 0xc0, 0xa5,
	0x79, 0x03, 0x5c, 0xb6, 0xc1, 0x3a, 0xc5, 0x80, 0xcb, 0x29, 0x4b, 0xeb, 0x72, 0xc9, 0xda, 0x39,
	0xe5, 0x0f, 0xd4, 0x16, 0x39, 0xb9, 0x72, 0x6d, 0x53, 0xe5, 0x8a, 0x4b, 0xbf, 0xa1, 0xe2, 0x75,
	0x1d, 0x96, 0xb4, 0x1f, 0x25, 0x92, 0xc0, 0xd6, 0x72, 0x79, 0x80, 0x91, 0x2e, 0x91, 0x33, 0x91,
	0xca, 0xc0, 0x43, 0x87, 0x2e, 0xd3, 0x55, 0x00, 0x43, 0x3a, 0x0e, 0x39, 0x9d, 0x92, 0xca, 0xd4,
	0x7f, 0x1d, 0x93, 0x4e, 0x49, 0xc5, 0xe5, 0xdf, 0x3f, 0x1b, 0x30, 0x44, 0x0b, 0x18, 0xd0, 0x62,
	0x68, 0x37, 0xc8, 0x68, 0x94, 0xc8, 0x28, 0x36, 0x6e, 0x56, 0x37, 0xfe, 0x7f, 0x18, 0xf8, 0x59,
	0x92, 0x48, 0x95, 0x7a, 0x3c, 0xdb, 0xa2, 0xd9, 0xbe, 0x21, 0x9e, 0x10, 0x53, 0x5e, 0x7d, 0x56,
	0x4f, 0x44, 0xd5, 0x27, 0x1f, 0xa9, 0x86, 0x94, 0xa5, 0x37, 0x23, 0x05, 0x03, 0xf7, 0x38, 0x9c,
	0xcd, 0xd8, 0x9a, 0xcb, 0xd5, 0xc0, 0x8d, 0xe7, 0xe0, 0xc0, 0x3d, 0x36, 0x5f, 0xf6, 0x3d, 0x68,
	0x9d, 0x0a, 0x35, 0xea, 0x90, 0xdc, 0x6e, 0x61, 0x74, 0x17, 0xa9, 0xce, 0x1f, 0x1b, 0x60, 0x23,
	0xe8, 0x1e, 0x8b, 0x99, 0x50, 0xbe, 0xa4, 0x3b, 0xa7, 0xe3, 0x2b, 0xce, 0xff, 0x10, 0x7a, 0xb4,
	0x65, 0x40, 0x30, 0x59, 0xc4, 0x73, 0x09, 0x1f, 0x17, 0xc6, 0x25, 0x94, 0x7e, 0x0e, 0x6b, 0xb4,
	0xc4, 0x84, 0x24, 0x7e, 0x62, 0x5b, 0xb4, 0x70, 0xbd, 0x5c, 0x58, 0x5a, 0xdd, 0x5d, 0x19, 0x17,
	0x63, 0x4d, 0x79, 0xc6, 0x73, 0xce, 0xa7, 0x19, 0x78, 0x47, 0x4a, 0xa7, 0x42, 0xa5, 0xa8, 0xde,
	0x95, 0x92, 0x1b, 0x6f, 0x23, 0xf9, 0x53, 0x58, 0x43, 0xc9, 0xae, 0xd4, 0xd9, 0x5c, 0xe2, 0x8d,
	0xc3, 0x17, 0xed, 0xda, 0x8e, 0x87, 0xf3, 0xd7, 0x16, 0x0c, 0x91, 0xab, 0x02, 0x91, 0x1f, 0x43,
	0x2f, 0xbf, 0xfd, 0xbc, 0x7b, 0xa3, 0xdc, 0x9d, 0x72, 0xd9, 0x72, 0x77, 0x88, 0xcb, 0x65, 0xb7,
	0x2b, 0xeb, 0xea, 0xa0, 0x68, 0xdd, 0x02, 0x14, 0xdf, 0x83, 0x95, 0xa9, 0x50, 0x41, 0xa5, 0x3b,
	0x61, 0xb2, 0xec, 0x01, 0x92, 0xcb, 0x4e, 0xc9, 0x7b, 0x00, 0xa1, 0xf6, 0xd2, 0x2c, 0x9a, 0x64,
	0x42, 0x99, 0x8a, 0xa7, 0x1b, 0xea, 0x67, 0x4c, 0xb0, 0x3f, 0x05, 0xeb, 0x55, 0xec, 0xe9, 0x54,
	0xa4, 0x39, 0xb4, 0xec, 0xb2, 0x54, 0x39, 0x16, 0xe1, 0x09, 0xce, 0xb8, 0x9d, 0x57, 0x31, 0x7d,
	0x5c, 0x15, 0xcd, 0x3b, 0xb7, 0x8c, 0xe6, 0xd5, 0xd0, 0x61, 0xdd, 0x10, 0x3a, 0x38, 0x28, 0x53,
	0x0e, 0xd3, 0xcd, 0x83, 0xf2, 0xe5, 0xfc, 0x05, 0xde, 0x90, 0xbf, 0xfc, 0x63, 0x19, 0xfa, 0xe8,
	0xc2, 0x7d, 0xa9, 0xbf, 0x23, 0x4f, 0xec, 0x00, 0x50, 0x54, 0xd4, 0xa9, 0x98, 0xd4, 0x2a, 0x78,
	0xe4, 0x3b, 0x41, 0xb2, 0x4b, 0x81, 0x93, 0x3e, 0xed, 0x9d, 0xf2, 0xad, 0x6d, 0x56, 0xa1, 0xb6,
	0x88, 0x8b, 0xf2, 0x05, 0x2e, 0x5a, 0x5f, 0xad, 0x6a, 0xeb, 0xab, 0xd6, 0xdb, 0x6a, 0xd7, 0x7b,
	0x5b, 0x94, 0x55, 0x0a, 0x9d, 0xf2, 0xf4, 0x12, 0x87, 0x2a, 0x24, 0xd0, 0xe4, 0xfb, 0xd0, 0x2b,
	0x1b, 0x67, 0x9a, 0xfc, 0x33, 0x70, 0xa1, 0xe8, 0x9c, 0x69, 0xfb, 0x03, 0xe8, 0x27, 0x72, 0x2e,
	0x8a, 0x1e, 0x0c, 0xc7, 0xba, 0x1e, 0xd3, 0x8a, 0x3e, 0x8c, 0x1f, 0xe9, 0xd4, 0xc3, 0x92, 0x81,
	0xec, 0x8e, 0x05, 0x61, 0xa4, 0xd3, 0x67, 0xe1, 0x9c, 0x22, 0x69, 0x14, 0xcb, 0x44, 0xa4, 0x92,
	0x22, 0x69, 0x97, 0x8b, 0x21, 0x43, 0x32, 0x91, 0x34, 0x88, 0x22, 0x7e, 0x8f, 0xc8, 0xe6, 0x03,
	0xd7, 0x42, 0x02, 0x55, 0x14, 0xf7, 0xa0, 0x3b, 0x15, 0xda, 0xbb, 0xc0, 0xb2, 0x60, 0xd4, 0xe3,
	0x87, 0x66, 0x2a, 0x34, 0x95, 0x09, 0xf6, 0x43, 0x00, 0x9a, 0xe0, 0xfb, 0xd2, 0xa7, 0xfb, 0x62,
	0x97, 0xf7, 0x25, 0xaf, 0x25, 0xdc, 0x2e, 0x71, 0x91, 0x8b, 0xde, 0x03, 0x40, 0x79, 0xe7, 0xd4,
	0x31, 0x18, 0x0d, 0x18, 0xaa, 0x53, 0xa1, 0xb9, 0x85, 0x60, 0x7f, 0x0e, 0x3d, 0x9e, 0x62, 0x91,
	0x43, 0x12, 0xb9, 0x59, 0x2d, 0xd0, 0x17, 0xfa, 0x0d, 0x2e, 0x30, 0x37, 0x89, 0x7e, 0x17, 0x3a,
	0x28, 0xfa, 0x6c, 0x32, 0x1d, 0xad, 0x30, 0xa8, 0xa6, 0x42, 0x7f, 0x3d, 0x99, 0xda, 0x9f, 0x81,
	0x75, 0x36, 0x99, 0xb2, 0xc4, 0x55, 0x92, 0xf8, 0x7f, 0xa5, 0xc4, 0xcb, 0x59, 0x9e, 0xdb, 0x39,
	0x9b, 0x4c, 0xf3, 0x4a, 0xab, 0xe8, 0x8a, 0xae, 0x2d, 0x74, 0x45, 0x11, 0xe8, 0x04, 0xb5, 0x30,
	0x18, 0xd9, 0x55, 0xa0, 0x23, 0x74, 0x8e, 0x02, 0x77, 0x79, 0x42, 0xbf, 0xf6, 0x01, 0xac, 0x4d,
	0x2b, 0x5d, 0x35, 0xd6, 0xe1, 0x4e, 0xfd, 0x54, 0xb5, 0xde, 0xa1, 0xbb, 0x5a, 0x5d, 0x43, 0x9a,
	0x7c, 0x06, 0xfd, 0xbc, 0xe9, 0x43, 0x22, 0xd6, 0xeb, 0xb1, 0xa9, 0xec, 0x9b, 0xb9, 0x3d, 0xc3,
	0x49, 0x0b, 0x1d, 0x18, 0xcc, 0x10, 0x7b, 0x45, 0xc5, 0xf8, 0x0e, 0xc3, 0x07, 0x89, 0x5f, 0x99,
	0xaa, 0xf1, 0x01, 0xac, 0x2f, 0xf0, 0x98, 0x20, 0x3c, 0xda, 0x20, 0xa8, 0xac, 0x55, 0x58, 0xf9,
	0x52, 0x38, 0x7f, 0x6b, 0x5c, 0x8a, 0xb5, 0x3a, 0xc6, 0xdb, 0x97, 0x10, 0xc1, 0x4b, 0xa8, 0x3b,
	0x7c, 0x65, 0xff, 0xac, 0xcb, 0x2c, 0xae, 0xd4, 0xe8, 0xaf, 0xdc, 0x84, 0x5c, 0x00, 0xe4, 0x46,
	0xdb, 0x04, 0x6b, 0x26, 0x5f, 0xca, 0x59, 0x9e, 0x30, 0x0f, 0xdc, 0x0e, 0x8d, 0x8f, 0x02, 0xfb,
	0x47, 0xd0, 0x9b, 0x8b, 0x5f, 0x47, 0xb9, 0x25, 0xdb, 0x55, 0xc8, 0x55, 0x43, 0x81, 0x0b, 0xcc,
	0x46, 0x36, 0xf8, 0x04, 0xac, 0x20, 0xb8, 0xc8, 0xeb, 0xc1, 0x4a, 0xcb, 0x67, 0x7f, 0xff, 0x45,
	0xb1, 0xa0, 0x13, 0x04, 0x17, 0xf4, 0x8e, 0x7c, 0xcc, 0x6d, 0xc1, 0x67, 0x59, 0x74, 0x98, 0x09,
	0x65, 0x1e, 0x91, 0x3c, 0xb6, 0x72, 0xc5, 0x95, 0x0f, 0x6b, 0xbc, 0x26, 0x7d, 0xbf, 0x86, 0x77,
	0x97, 0x5f, 0xbe, 0x3d, 0x7c, 0x94, 0x67, 0x15, 0xe9, 0x77, 0xc1, 0x32, 0x6f, 0x52, 0x60, 0x96,
	0x14, 0x63, 0xe7, 0x4f, 0x0d, 0xde, 0xe0, 0x57, 0x5a, 0x1e, 0x27, 0x51, 0x8c, 0xec, 0x37, 0xa6,
	0xa8, 0xdf, 0x87, 0x4e, 0x9c, 0x44, 0x71, 0x6e, 0x52, 0xcc, 0xf3, 0xcc, 0xbf, 0x17, 0xb8, 0x9c,
	0x43, 0x30, 0x32, 0x1c, 0x05, 0xf6, 0x47, 0xa5, 0xf5, 0xf3, 0x7e, 0x93, 0x61, 0xad, 0x41, 0xb8,
	0xea, 0x0d, 0xce, 0x74, 0x72, 0x6f, 0x38, 0xdf, 0x2e, 0x6a, 0xf7, 0x76, 0x1d, 0x54, 0x14, 0x8c,
	0xbc, 0x81, 0xd4, 0x3e, 0x69, 0xdb, 0xa5, 0xa9, 0x7d, 0xa9, 0x7d, 0xe7, 0xb7, 0x8b, 0xe7, 0x46,
	0xc3, 0x5e, 0xae, 0x7e, 0x1a, 0x57, 0x54, 0x3f, 0xf5, 0xd6, 0x4f, 0xf3, 0x52, 0xeb, 0xa7, 0x62,
	0xa2, 0xd6, 0xcd, 0x26, 0x72, 0x3e, 0xe2, 0x3a, 0xf6, 0x51, 0x96, 0x46, 0x4f, 0x32, 0xb4, 0xfd,
	0x06, 0x2c, 0x73, 0xad, 0x6d, 0x1c, 0x65, 0x46, 0xce, 0xc9, 0x02, 0xe3, 0x5b, 0x9a, 0xa1, 0x14,
	0xda, 0xac, 0x09, 0xed, 0xd3, 0xeb, 0xbe, 0x1f, 0x9d, 0x13, 0xb2, 0x30, 0xe7, 0xc4, 0xb1, 0x17,
	0x44, 0xe7, 0xca, 0x64, 0x33, 0x5d, 0x3f, 0xe7, 0x40, 0xfb, 0x88, 0xc0, 0x64, 0x09, 0xcc, 0xc2,
	0x97, 0xaa, 0x2f, 0x82, 0xa0, 0x90, 0xf3, 0x78, 0xe3, 0xc5, 0xba, 0x4e, 0xe5, 0x4b, 0xf9, 0xc0,
	0x9f, 0x85, 0x98, 0xe2, 0xc6, 0xe3, 0x07, 0xa8, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xee,
	0x31, 0x90, 0xb7, 0x23, 0x1b, 0x00, 0x00,
}
