log_level: debug 
log_dir: ./log
log_prefix: web
log_stderr: true 

rpc_addr: 127.0.0.1
rpc_port: 36901
health_port: 36902
rpc_server_name: web

redis_addr: 127.0.0.1:6379
redis_passwd: 

consul_addr: 127.0.0.1:8500

nsqd_addr: 127.0.0.1:4150
nsqlookupd_addrs: 
  - 127.0.0.1:4161

pprofExposeType:
pprofHttpPort: 36903

node: 1

# http 监听地址
http_listen_addr: 0.0.0.0:36900